"use client";
import {useState} from "react";
const nav=["Übersicht","Kalender","Teams","Events","Chat","Mitglieder","Beiträge","Protokolle","Verwaltung"];
const events=[["06","AUG","Training Herren I","18:30 · Hemberghalle"],["09","AUG","Heimspiel vs. RSC Cronenberg","16:00 · Hemberghalle"],["12","AUG","Vorstandssitzung","19:30 · Vereinsheim"]];
const members=[["Marco Schulte","marco@ergi.de","Sys-Admin · Vorstand · Spieler","Herren I","Bezahlt"],["Claudia Berg","claudia@ergi.de","Geschäftsführung · Mitglied","—","Bezahlt"],["Sabine Thomas","sabine@ergi.de","Eltern · Mitglied","U11","Offen"],["Timo Krüger","timo@ergi.de","Trainer · Mitglied","U15","Bezahlt"],["Helga Thomas","helga@ergi.de","Fan","—","Bezahlt"]];
function Sponsor(){return <div className="sponsor"><span>PARTNER DER ERG</span><b>Ihre Marke im Mittelpunkt</b><button>Slot anfragen →</button></div>}
function Dashboard({notify}:{notify:(x:string)=>void}){return <><header><div><small>SAMSTAG, 1. AUGUST</small><h1>Guten Morgen, Marco.</h1><p>Alles Wichtige rund um deinen Verein – auf einen Blick.</p></div><button className="primary" onClick={()=>notify("Ein neuer Eintrag kann angelegt werden")}>＋ Neu anlegen</button></header><section className="countdown"><div><label>NÄCHSTES TRAINING</label><h2>Herren I · Mannschaftstraining</h2><p>Donnerstag, 6. August · 18:30 Uhr · Hemberghalle</p></div><div className="timer"><b>04</b><i>Tage</i><b>06</b><i>Std.</i><b>24</b><i>Min.</i></div><button onClick={()=>notify("Zusage gespeichert")}>Zusagen</button></section><div className="stats">{[["MITGLIEDER","247","↑ 8 dieses Jahr"],["BEITRÄGE 2026","92%","19 noch offen"],["ANSTEHENDE EVENTS","8","Nächste 30 Tage"],["OFFENE AUFGABEN","12","3 überfällig"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></article>)}</div><Sponsor/><div className="columns"><section className="panel"><div className="title"><h2>Was als Nächstes ansteht</h2><button>Alle Termine →</button></div>{events.map((e,i)=><div className="event" key={e[2]}><div className={`date d${i}`}><b>{e[0]}</b><small>{e[1]}</small></div><div><span>{i===0?"TRAINING":i===1?"SPIELTAG":"SITZUNG"}</span><h3>{e[2]}</h3><p>{e[3]}</p></div><button>•••</button></div>)}</section><aside><section className="panel"><div className="title"><h2>Aufgaben</h2><button>Alle →</button></div>{["Catering für Heimspiel klären","Trikots U11 bestellen","Protokoll freigeben"].map((x,i)=><label className="task" key={x}><input type="checkbox"/><div><b>{x}</b><small>{i===0?"Heute · Marco Schulte":"Diese Woche · Vorstand"}</small></div></label>)}</section><Sponsor/></aside></div></>}
function Members(){return <><header><div><small>VERWALTUNG</small><h1>Mitglieder</h1><p>Profile, Mannschaften und Rollen zentral verwalten.</p></div><button className="primary">＋ Mitglied einladen</button></header><div className="filters"><input placeholder="Mitglied suchen …"/><button>Alle Rollen⌄</button><button>Exportieren</button></div><section className="panel table"><table><thead><tr><th>MITGLIED</th><th>ROLLEN</th><th>TEAM</th><th>BEITRAG</th></tr></thead><tbody>{members.map(m=><tr key={m[1]}><td><i>{m[0].split(" ").map(x=>x[0]).join("")}</i><div><b>{m[0]}</b><small>{m[1]}</small></div></td><td>{m[2].split(" · ").map(r=><span className="role" key={r}>{r}</span>)}</td><td>{m[3]}</td><td><span className={m[4]==="Offen"?"open":"paid"}>{m[4]}</span></td></tr>)}</tbody></table></section></>}
function Module({name}:{name:string}){let data:Record<string,string[]>={Kalender:["Training Herren I","Heimspiel am 9. August","Vorstandssitzung"],Teams:["Herren I · 18 Aktive","U15 · 14 Aktive","U11 · 17 Aktive"],Events:["Heimspiel & Helferplanung","Sommerfest 2026","Jugendturnier U11"],Chat:["Vereins-News","Herren I","Vorstand · Intern"],Beiträge:["226 Beiträge bezahlt","19 Zahlungen offen","4 Erinnerungen versendet"],Protokolle:["Vorstandssitzung 12.07.","Jahreshauptversammlung","Sportausschuss"],Verwaltung:["Rollen & Rechte","Sponsor-Slots","System & Kanäle"]};return <><header><div><small>ERG ISERLOHN</small><h1>{name}</h1><p>Alles aktuell, übersichtlich und an einem Ort.</p></div><button className="primary">＋ Neu anlegen</button></header><div className="cards">{(data[name]||[]).map((x,i)=><article key={x}><strong>{["◇","◎","≡"][i]}</strong><span>AKTUELL</span><h2>{x}</h2><p>Details, Zuständigkeiten und Rückmeldungen anzeigen und bearbeiten.</p><button>Details ansehen →</button></article>)}</div><Sponsor/></>}
export default function Home(){const[a,setA]=useState("Übersicht"),[toast,setToast]=useState("");const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)};return <div className="app"><aside className="side"><div className="brand"><b>ERG</b><div><strong>ERG ISERLOHN</strong><small>Rollhockey. Seit 1965.</small></div></div><nav>{nav.map((n,i)=><button key={n} className={a===n?"active":""} onClick={()=>setA(n)}><span>{["⌂","□","◎","◇","◌","♙","€","≡","⚙"][i]}</span>{n}{n==="Chat"&&<em>3</em>}</button>)}</nav><div className="profile"><i>MS</i><div><b>Marco Schulte</b><small>Sys-Admin · Vorstand</small></div></div></aside><main><div className="top"><input placeholder="⌕  Suchen …"/><button>♢</button></div><div className="content">{a==="Übersicht"?<Dashboard notify={notify}/>:a==="Mitglieder"?<Members/>:<Module name={a}/>}</div></main>{toast&&<div className="toast">✓ {toast}</div>}</div>}
