/* Sprachen der App.
 *
 * WARUM EINE EIGENE DATEI
 * page.tsx hat rund 11.000 Zeilen. Die Texte dort hineinzuschreiben haette sie
 * um Tausende weitere verlaengert - und beim Uebersetzen muesste man jedes Mal
 * durch die ganze App scrollen. Hier stehen sie beieinander und lassen sich
 * Sprache fuer Sprache vervollstaendigen.
 *
 * WIE DIE UEBERSETZUNG FEHLSCHLAEGT
 * Fehlt ein Schluessel in einer Sprache, faellt t() auf Deutsch zurueck - nicht
 * auf den Schluessel selbst. Ein Nutzer sieht dann einen deutschen Satz, was
 * unschoen ist; er saehe sonst "profil.titel", was unbrauchbar ist.
 *
 * STAND
 * Uebersetzt sind die Bildschirme, die ein neuer Nutzer zuerst sieht:
 * Sprachwahl, Anmeldung, Registrierung. Der Rest der App bleibt vorerst
 * deutsch - die Umstellung erfolgt in Schritten, damit nicht die halbe App
 * zwischen zwei Sprachen steht.
 */

export const SPRACHEN = [
  { code: "de", name: "Deutsch",    flagge: "🇩🇪" },
  { code: "en", name: "English",    flagge: "🇬🇧" },
  { code: "es", name: "Español",    flagge: "🇪🇸" },
  { code: "pt", name: "Português",  flagge: "🇵🇹" },
  { code: "it", name: "Italiano",   flagge: "🇮🇹" },
  { code: "tr", name: "Türkçe",     flagge: "🇹🇷" },
  { code: "fr", name: "Français",   flagge: "🇫🇷" },
] as const;

export type Sprachcode = (typeof SPRACHEN)[number]["code"];

type Woerterbuch = Record<string, string>;

const de: Woerterbuch = {
  "sys.demoDaten": "Demo-Daten",
  "sys.jaZuruecksetzen": "Ja, zurücksetzen",
  "verein.logo": "Profilbild des Vereins",
  "verein.logoHinweis": "JPG, PNG oder WebP · maximal 2 MB",
  "verein.farben": "Vereinsfarben",
  "mit.offeneAntraege": "Offene Mitgliedsanträge",
  "mit.antraegeLaden": "Mitgliedsanträge werden geladen …",
  "mit.keineAntraegeKurz": "Keine offenen Anträge",
  "mit.registrierung": "Registrierung",
  "mit.freigeben": "Freigeben",
  "allg.listeAktualisieren": "Liste aktualisieren",
  "mit.verwalten": "Mitgliedschaften verwalten",
  "mit.laden": "Mitglieder werden geladen …",
  "mit.sperren": "Sperren",
  "mit.keineVorhanden": "Keine Mitgliedschaften vorhanden.",
  "mit.sperrliste": "Sperrliste",
  "verein.funktionenFrage": "Welche Funktionen braucht ihr?",
  "rol.niemand": "Niemand hat aktuell diese Rolle.",
  "sys.profileZusammen": "Profile ohne Konto zusammenführen",
  "sys.platzhalter": "Platzhalter-Profil (ohne Konto) …",
  "allg.nochNichts": "Noch nichts da",
  "sys.nichtBereit": "Die App ist nicht einsatzbereit",
  "store.apple": "Im App Store laden",
  "store.google": "Bei Google Play laden",
  "verein.waehlen": "Verein auswählen …",
  "verein.namePlatzhalter": "Vereinsname, z. B. TuS Beispieldorf",
  "kal.woechentlich": "Wöchentlich · Sonntagabend",
  "kal.monatlich": "Monatlich",
  "kal.verbinden": "Mit Gerätekalender verbinden",
  "recht.bedingungen": "Bedingungen",
  "konto.loeschenLang": "Konto und persönliche Daten löschen",
  "sais.beendet": "Abstimmung beendet — Ergebnis final",
  "sais.ehrung": "Athlet/in der Saison — Ehrung beim Sommerfest",
  "tipp.jeTeam": "Tippspiel je Mannschaft",
  "tipp.niemand": "Noch niemand in dieser Runde.",
  "tipp.wartet": "Wartet auf Ergebnis",
  "tipp.ergebnisse": "Ergebnisse & Punkte",
  "prot.keineAufgaben": "Keine offenen Aufgaben — sehr gut! 🎉",
  "prot.neu": "Neues Protokoll erfassen",
  "prot.teilnehmer": "Teilnehmer:innen",
  "prot.speichern": "Protokoll & Aufgaben speichern",
  "prot.pflicht": "Bitte Titel und Protokolltext ausfüllen.",
  "prot.vergangene": "Vergangene Protokolle",
  "bei.erinnerungen": "Automatische Zahlungserinnerungen",
  "bei.keineOffenen": "Aktuell keine offenen Beiträge. 🎉",
  "sp.nichtFrei": "Eigene Sponsoren sind noch nicht freigeschaltet",
  "sp.zuSehen": "Zu sehen:",
  "sp.derSponsor": "Der Sponsor",
  "sp.dieAktion": "Die Aktion (optional)",
  "sp.stehtAufPlatz": "Der Sponsor steht auf dem Platz",
  "sp.entfernen": "Sponsor von diesem Platz entfernen",
  "umf.neu": "Neue Mitmach-Umfrage",
  "umf.mindestens": "Mindestens zwei Antwortmöglichkeiten eintragen.",
  "allg.veroeffentlichen": "Veröffentlichen",
  "tm.mannschaftWaehlen2": "Mannschaft auswählen …",
  "chat.kanaele": "Chat-Kanäle",
  "sys.konten": "Konten-Übersicht",
  "straf.titel": "Strafen",
  "straf.keineAktiven": "Keine aktiven Strafen.",
  "straf.historie": "Strafen-Historie",
  "auf.titel": "Aufgaben",
  "auf.keineEingetragen": "Für keine Aufgabe eingetragen.",
  "fahr.titel": "Fahrgemeinschaften",
  "fahr.keineKurz": "Keine Fahrgemeinschaften.",
  "mit.keineAnfragen": "Aktuell keine offenen Beitrittsanfragen.",
  "verein.profilBearbeiten": "Vereinsprofil bearbeiten",
  "status.aktiv": "Aktiv",
  "status.ausstehend": "Ausstehend",
  "status.inaktiv": "Inaktiv",
  "status.gesperrt": "Gesperrt",
  "tm.athletenTeams": "Athleten-Mannschaften",
  "feld.telefonnummern": "Telefonnummern",
  "feld.geburtstagZeigen": "Geburtstag im Verein anzeigen",
  "gesch.w": "Weiblich",
  "gesch.m": "Männlich",
  "gesch.d": "Divers",
  "gesch.k": "Keine Angabe",
  "push.aufGeraet": "Push-Benachrichtigungen auf diesem Gerät",
  "sich.autoLogout": "Automatischer Logout",
  "sich.tage30": "Nach 30 Tagen",
  "sich.tage60": "Nach 60 Tagen",
  "sich.tage90": "Nach 90 Tagen",
  "zug.werben": "Vereine werben Vereine",
  "zug.codeKopieren": "Code kopieren",
  "kal.abonnieren": "Termine abonnieren",
  "kal.aktualisierung": "Aktualisierung",
  "kal.nie": "Nie automatisch",
  "kal.taeglich": "Täglich",
  "kal.auswahlAufheben": "Auswahl aufheben — meine Mannschaften verwenden",
  "straf.verwaltung": "Strafenverwaltung",
  "straf.bisherige": "Bisherige Strafen",
  "straf.alle": "Alle Strafen",
  "straf.historieLaedt": "Historie wird geladen …",
  "tm.athletWaehlen2": "Athlet/in wählen …",
  "allg.aendern": "Ändern",
  "feld.personen": "Personen",
  "auf.ganzerVerein": "Ganzer Verein",
  "auf.verantwortlich": "Verantwortlich (mehrere möglich)",
  "auf.laden": "Aufgaben werden geladen …",
  "auf.keine": "Aktuell keine offenen Vereinsaufgaben.",
  "auf.uebernehmeIch": "Ich übernehme das",
  "auf.zurueckziehen": "Zurückziehen",
  "fz.keine": "Noch keine Fahrzeuge hinterlegt.",
  "fz.kalenderLaedt": "Kalender wird geladen …",
  "fz.keineBuchungen": "Keine Buchungen in diesem Monat.",
  "fz.privat": "Private Buchung (keine Mannschaft)",
  "tm.mannschaftWaehlen": "Mannschaft wählen …",
  "tel.laedt": "Telefonnummer wird geladen …",
  "tel.keine": "Keine Telefonnummer hinterlegt.",
  "helf.satzVorladen": "Satz vorladen …",
  "helf.stationen": "Stationen an diesem Termin",
  "helf.alleEntfernen": "Alle entfernen",
  "helf.keineSaetze": "Noch keine Sätze angelegt.",
  "helf.satzLoeschen": "Satz löschen",
  "zug.zurueckziehen": "Anfrage zurückziehen",
  "sp.eigene": "Eigene Sponsoren zeigen",
  "zug.vollzugang": "Vollzugang anfragen",
  "zug.keinAbo": "Kein eigenes Abo nötig",
  "mit.keine": "Keine Mitglieder gefunden.",
  "vid.keine": "Für deine aktuellen Rollen gibt es noch keine Videos.",
  "chat.wiederAnzeigen": "Tippe einen Namen an, um die Person wieder anzuzeigen.",
  "chat.melden": "Melden",
  "chat.blockieren": "Blockieren",
  "chat.keiner": "Noch kein Chat für dich",
  "chat.ausgeblendet": "Für dich ausgeblendet",
  "news.keineVeroeffentlicht": "Noch keine News veröffentlicht.",
  "bei.bezahlt": "Bezahlt",
  "bei.offen": "Noch nicht bezahlt",
  "bei.keineDaten": "Noch keine Beitragsdatensätze vorhanden.",
  "bei.anzahlPersonen": "Anzahl der Personen insgesamt",
  "bei.weitereNamen": "Weitere Namen ohne Benutzerkonto",
  "bei.kommaHinweis": "Mehrere Namen bitte durch Komma trennen.",
  "fam.verknuepfung": "Familienverknüpfung",
  "fam.rolle": "Rolle in der Verknüpfung",
  "fam.verbinden": "Verbinden",
  "fam.keinProfil": "Kein passendes Profil gefunden.",
  "fam.kindAnlegen": "Kind ohne Account vorläufig anlegen",
  "tm.kapitaenZuweisen": "Kapitänsrolle zuweisen",
  "tm.athletWaehlen": "Athlet/in auswählen …",
  "tm.keineZuordnung": "Du bist aktuell keiner Mannschaft zugeordnet.",
  "tm.neuAnlegen": "Neue Mannschaft anlegen",
  "tm.erwachsene": "Erwachsenenmannschaft?",
  "tm.keineZuordnungKurz": "Noch keiner Mannschaft zugeordnet.",
  "home.keinSpiel": "Für diese Mannschaft ist derzeit kein Spiel geplant.",
  "helf.niemandEingeteilt": "Für diesen Termin ist niemand eingeteilt.",
  "fahr.keine": "Noch keine Fahrgemeinschaft für diesen Termin.",
  "ev.reiheFrage": "Nur diesen Termin oder die ganze Reihe?",
  "home.geburtstag": "Heute Geburtstag:",
  "home.willkommenKomma": "Willkommen zurück,",
  "login.demo": "Demo-Zugänge zum Ausprobieren",
  "sys.vorschlag": "Vorschlag · Name stimmt überein",
  "login.bleiben": "Angemeldet bleiben",
  "reg.alsWas": "Ich registriere mich als",
  "reg.akzeptiere": "Ich akzeptiere die",
  "recht.datenschutzerklaerung": "Datenschutzerklärung",
  "mit.alle": "Alle Mitglieder",
  "mit.weitere": "Weitere Vereinsmitglieder",
  "umf.tippen": "Tippe, um abzustimmen",
  "allg.jetztEintragen": "Jetzt eintragen",
  "allg.alleAnsehen": "Alle ansehen",
  "allg.listeLaedt": "Liste wird geladen …",
  "news.keine": "Noch keine News.",
  "helf.niemand": "Noch niemand eingetragen",
  "helf.jemanden": "Jemanden eintragen",
  "helf.gesucht": "Helfer:innen gesucht",
  "fahr.mitfahren": "Mitfahren",
  "fahr.loeschen": "Fahrgemeinschaft löschen",
  "fahr.anbieten": "Platz anbieten",
  "ev.nurDiesen": "Nur diesen Termin",
  "ev.ganzeReihe": "Ganze Reihe löschen",
  "ev.wirklichLoeschen": "Diesen Termin wirklich löschen?",
  "bei.art": "Beitragsart",
  "bei.mitglied": "Mitgliedsbeitrag",
  "bei.familie": "Familienbeitrag",
  "verein.wechseln": "Verein wechseln",
  "verein.deine": "Deine Vereine",
  "verein.beitrittAnfragen": "Beitritt anfragen",
  "verein.beitrittAls": "Ich trete bei als",
  "verein.finden": "Verein finden",
  "verein.findenHinweis": "Suche den Verein, dem du beitreten möchtest.",
  "verein.laden": "Vereine werden geladen …",
  "verein.ladenFehler": "Die Vereinsliste konnte nicht geladen werden.",
  "verein.neuAnlegen": "Neuen Verein registrieren",
  "verein.anlegen": "Verein anlegen",
  "verein.zurueckAuswahl": "Zurück zur Vereinsauswahl",
  "verein.eigeneFarben": "Eigene Farben",
  "allg.erneut": "Erneut versuchen",
  "allg.entsperren": "Entsperren",
  "allg.gesperrt": "Diesen Bereich schaltet der Verein frei.",
  "allg.mehr": "Mehr erfahren",
  "tm.laden": "Mannschaften werden geladen …",
  "tm.keine": "Noch keine Mannschaften angelegt.",
  "straf.waehlen": "Strafe wählen …",
  "straf.keine": "Noch keine Strafen vergeben.",
  "feld.beschreibung": "Beschreibung (optional)",
  "feld.nutzerSuchen": "Nutzer suchen",
  "feld.mannschaftFiltern": "Mannschaft filtern",
  "kal.vorher": "Vorheriger Monat",
  "kal.naechster": "Nächster Monat",
  "sp.zurAktion": "Zur Aktion",
  "sp.website": "Website ansehen",
  "konto.loeschenFrage": "Konto endgültig löschen?",
  "allg.entfernen": "Entfernen",
  "allg.anlegen": "Anlegen",
  "allg.hinzufuegen": "Hinzufügen",
  "allg.abmelden": "Abmelden",
  "allg.laedt": "Wird geladen …",
  "allg.niemandGefunden": "Niemand gefunden.",
  "allg.ablehnen": "Ablehnen",
  "allg.annehmen": "Annehmen",
  "allg.austragen": "Austragen",
  "allg.uebernehmen": "Übernehmen",
  "allg.eintragenKnopf": "Eintragen",
  "feld.vollerName": "Vor- und Nachname",
  "feld.rueckennummer": "Rückennummer",
  "feld.stadt": "Stadt",
  "feld.gegner": "Gegner",
  "tm.mannschaften": "Mannschaften",
  "recht.impressum": "Impressum",
  "recht.datenschutz": "Datenschutz",
  "recht.nutzung": "Nutzungsbedingungen",
  "tm.meineTeams": "Meine Teams",
  "tm.alleTeams": "Alle Mannschaften",
  "tm.kader": "Athlet/innen",
  "tm.meinTeam": "Mein Team",
  "tm.mannschaft": "Mannschaft",
  "pf.einstellungen": "Einstellungen",
  "pf.persoenlich": "Persönliche Daten",
  "pf.konto": "Konto & Sicherheit",
  "pf.vereinMitglied": "Verein & Mitgliedschaft",
  "pf.benachrichtigungen": "Benachrichtigungen & Kalender",
  "pf.zugang": "Zugang & Empfehlungen",
  "pf.support": "Support & Feedback",
  "pf.einladen": "Freunde einladen",
  "pf.kontoLoeschen": "Konto löschen",
  "pf.vereinVerwalten": "Verein verwalten",
  "pf.vereinseinstellungen": "Vereinseinstellungen",
  "ev.titel": "Termine",
  "ev.eintragen": "Termin eintragen",
  "ev.alle": "Alle",
  "ev.training": "Training",
  "ev.spiele": "Spiele",
  "ev.events": "Events",
  "ev.alleTeams": "Alle Mannschaften",
  "ev.datum": "Datum",
  "ev.beginn": "Beginn",
  "ev.ende": "Ende",
  "ev.heimspiel": "Heimspiel",
  "ev.spiel": "Spiel",
  "ev.vereinsevent": "Vereins-Event",
  "ev.wiederholend": "Wiederholend",
  "ev.werDabei": "Wer ist dabei?",
  "ev.bistDuDabei": "Bist du dabei?",
  "ev.zugesagt": "Zugesagt",
  "ev.abgesagt": "Abgesagt",
  "ev.absagen": "Absagen",
  "ev.absageGrund": "Warum wird abgesagt?",
  "ev.jetztAbsagen": "Jetzt absagen",
  "ev.keineTermine": "Keine Termine in diesem Zeitraum.",
  "home.willkommen": "Willkommen zurück",
  "home.naechstesSpiel": "Nächstes Spiel",
  "home.naechstesTraining": "Nächstes Training",
  "home.mitmachen": "Mitmachen",
  "home.aktionen": "Aktionen & Abstimmungen",
  "home.tage": "TAGE",
  "home.std": "STD",
  "home.min": "MIN",
  "allg.speichern": "Speichern",
  "allg.abbrechen": "Abbrechen",
  "allg.loeschen": "Löschen",
  "allg.bearbeiten": "Bearbeiten",
  "allg.schliessen": "Schließen",
  "allg.zurueck": "Zurück",
  "allg.weiter": "Weiter",
  "allg.suchen": "Suchen …",
  "allg.keineEintraege": "Noch keine Einträge.",
  "nav.home": "Home",
  "nav.events": "Termine",
  "nav.teams": "Teams",
  "nav.chat": "Chat",
  "nav.profile": "Profil",
  "nav.fees": "Beiträge",
  "nav.news": "Redaktion",
  "nav.admin": "Verwaltung",
  "nav.sponsors": "Sponsoren",
  "sub.season": "Athlet/in der Saison",
  "sub.tipp": "Tippspiel",
  "sub.duty": "Helferplanung",
  "sub.postfach": "Benachrichtigungen",
  "sprache.titel": "Sprache wählen",
  "sprache.hinweis": "In welcher Sprache möchtest du die App nutzen? Du kannst das später im Profil ändern.",
  "sprache.weiter": "Weiter",

  "login.willkommen": "Willkommen zurück",
  "login.email": "E-Mail-Adresse",
  "login.passwort": "Passwort",
  "login.vergessen": "Passwort vergessen?",
  "login.anmelden": "Anmelden",
  "login.keinKonto": "Noch kein Konto?",
  "login.registrieren": "Jetzt registrieren",

  "reg.titel": "Konto erstellen",
  "reg.vorname": "Vorname",
  "reg.nachname": "Nachname",
  "reg.schonMitglied": "Schon Mitglied?",
  "reg.anmelden": "Anmelden",
  "reg.fastGeschafft": "Fast geschafft",
  "reg.bestaetigen": "Du erhältst eine E-Mail. Bitte bestätige sie, damit wir sicher gehen können, dass deine Daten korrekt sind.",
  "reg.danach": "Anschließend kannst du dich anmelden.",
  "reg.jetztAnmelden": "Jetzt anmelden",
  "reg.keineMail": "Keine E-Mail erhalten? Sieh im Spam-Ordner nach — sie kommt meist innerhalb einer Minute.",

  "profil.sprache": "Sprache",
  "profil.spracheHinweis": "Sprache der App",
};

const en: Woerterbuch = {
  "sys.demoDaten": "Demo data",
  "sys.jaZuruecksetzen": "Yes, reset",
  "verein.logo": "Club logo",
  "verein.logoHinweis": "JPG, PNG or WebP · max 2 MB",
  "verein.farben": "Club colours",
  "mit.offeneAntraege": "Open join requests",
  "mit.antraegeLaden": "Loading requests …",
  "mit.keineAntraegeKurz": "No open requests",
  "mit.registrierung": "Registration",
  "mit.freigeben": "Approve",
  "allg.listeAktualisieren": "Refresh list",
  "mit.verwalten": "Manage memberships",
  "mit.laden": "Loading members …",
  "mit.sperren": "Block",
  "mit.keineVorhanden": "No memberships yet.",
  "mit.sperrliste": "Blocked list",
  "verein.funktionenFrage": "Which features does your club need?",
  "rol.niemand": "Nobody has this role right now.",
  "sys.profileZusammen": "Merge profiles without an account",
  "sys.platzhalter": "Placeholder profile (no account) …",
  "allg.nochNichts": "Nothing here yet",
  "sys.nichtBereit": "The app is not ready to use",
  "store.apple": "Download on the App Store",
  "store.google": "Get it on Google Play",
  "verein.waehlen": "Choose a club …",
  "verein.namePlatzhalter": "Club name, e.g. Example FC",
  "kal.woechentlich": "Weekly · Sunday evening",
  "kal.monatlich": "Monthly",
  "kal.verbinden": "Connect to device calendar",
  "recht.bedingungen": "Terms",
  "konto.loeschenLang": "Delete account and personal data",
  "sais.beendet": "Voting closed — final result",
  "sais.ehrung": "Athlete of the season — awarded at the summer party",
  "tipp.jeTeam": "Prediction game per team",
  "tipp.niemand": "Nobody in this round yet.",
  "tipp.wartet": "Waiting for the result",
  "tipp.ergebnisse": "Results & points",
  "prot.keineAufgaben": "No open tasks — well done! 🎉",
  "prot.neu": "New minutes",
  "prot.teilnehmer": "Attendees",
  "prot.speichern": "Save minutes & tasks",
  "prot.pflicht": "Please fill in a title and the minutes.",
  "prot.vergangene": "Past minutes",
  "bei.erinnerungen": "Automatic payment reminders",
  "bei.keineOffenen": "No outstanding fees. 🎉",
  "sp.nichtFrei": "Your own sponsors are not enabled yet",
  "sp.zuSehen": "Currently showing:",
  "sp.derSponsor": "The sponsor",
  "sp.dieAktion": "The offer (optional)",
  "sp.stehtAufPlatz": "The sponsor appears in this slot",
  "sp.entfernen": "Remove sponsor from this slot",
  "umf.neu": "New club poll",
  "umf.mindestens": "Enter at least two answer options.",
  "allg.veroeffentlichen": "Publish",
  "tm.mannschaftWaehlen2": "Choose a team …",
  "chat.kanaele": "Chat channels",
  "sys.konten": "Accounts overview",
  "straf.titel": "Fines",
  "straf.keineAktiven": "No open fines.",
  "straf.historie": "Fine history",
  "auf.titel": "Tasks",
  "auf.keineEingetragen": "Not signed up for any task.",
  "fahr.titel": "Carpools",
  "fahr.keineKurz": "No carpools.",
  "mit.keineAnfragen": "No open join requests.",
  "verein.profilBearbeiten": "Edit club profile",
  "status.aktiv": "Active",
  "status.ausstehend": "Pending",
  "status.inaktiv": "Inactive",
  "status.gesperrt": "Blocked",
  "tm.athletenTeams": "Playing teams",
  "feld.telefonnummern": "Phone numbers",
  "feld.geburtstagZeigen": "Show birthday in the club",
  "gesch.w": "Female",
  "gesch.m": "Male",
  "gesch.d": "Non-binary",
  "gesch.k": "Prefer not to say",
  "push.aufGeraet": "Push notifications on this device",
  "sich.autoLogout": "Automatic sign-out",
  "sich.tage30": "After 30 days",
  "sich.tage60": "After 60 days",
  "sich.tage90": "After 90 days",
  "zug.werben": "Clubs refer clubs",
  "zug.codeKopieren": "Copy code",
  "kal.abonnieren": "Subscribe to events",
  "kal.aktualisierung": "Refresh",
  "kal.nie": "Never automatically",
  "kal.taeglich": "Daily",
  "kal.auswahlAufheben": "Clear selection — use my teams",
  "straf.verwaltung": "Fines",
  "straf.bisherige": "Fines so far",
  "straf.alle": "All fines",
  "straf.historieLaedt": "Loading history …",
  "tm.athletWaehlen2": "Choose a player …",
  "allg.aendern": "Change",
  "feld.personen": "People",
  "auf.ganzerVerein": "Whole club",
  "auf.verantwortlich": "Responsible (several possible)",
  "auf.laden": "Loading tasks …",
  "auf.keine": "No open club tasks right now.",
  "auf.uebernehmeIch": "I'll do it",
  "auf.zurueckziehen": "Withdraw",
  "fz.keine": "No vehicles added yet.",
  "fz.kalenderLaedt": "Loading calendar …",
  "fz.keineBuchungen": "No bookings this month.",
  "fz.privat": "Private booking (no team)",
  "tm.mannschaftWaehlen": "Choose a team …",
  "tel.laedt": "Loading phone number …",
  "tel.keine": "No phone number saved.",
  "helf.satzVorladen": "Load a set …",
  "helf.stationen": "Stations for this event",
  "helf.alleEntfernen": "Remove all",
  "helf.keineSaetze": "No sets created yet.",
  "helf.satzLoeschen": "Delete set",
  "zug.zurueckziehen": "Withdraw request",
  "sp.eigene": "Show your own sponsors",
  "zug.vollzugang": "Request full access",
  "zug.keinAbo": "No subscription of your own needed",
  "mit.keine": "No members found.",
  "vid.keine": "No videos for your current roles yet.",
  "chat.wiederAnzeigen": "Tap a name to show that person again.",
  "chat.melden": "Report",
  "chat.blockieren": "Block",
  "chat.keiner": "No chats for you yet",
  "chat.ausgeblendet": "Hidden for you",
  "news.keineVeroeffentlicht": "No news published yet.",
  "bei.bezahlt": "Paid",
  "bei.offen": "Not paid yet",
  "bei.keineDaten": "No fee records yet.",
  "bei.anzahlPersonen": "Total number of people",
  "bei.weitereNamen": "Other names without an account",
  "bei.kommaHinweis": "Separate several names with commas.",
  "fam.verknuepfung": "Family link",
  "fam.rolle": "Role in the link",
  "fam.verbinden": "Connect",
  "fam.keinProfil": "No matching profile found.",
  "fam.kindAnlegen": "Add a child without an account",
  "tm.kapitaenZuweisen": "Assign captain",
  "tm.athletWaehlen": "Choose a player …",
  "tm.keineZuordnung": "You are not assigned to a team yet.",
  "tm.neuAnlegen": "Create a new team",
  "tm.erwachsene": "Adult team?",
  "tm.keineZuordnungKurz": "Not assigned to a team yet.",
  "home.keinSpiel": "No match scheduled for this team right now.",
  "helf.niemandEingeteilt": "Nobody assigned to this event.",
  "fahr.keine": "No carpool for this event yet.",
  "ev.reiheFrage": "This date only or the whole series?",
  "home.geburtstag": "Birthday today:",
  "home.willkommenKomma": "Welcome back,",
  "login.demo": "Demo logins to try it out",
  "sys.vorschlag": "Suggestion · name matches",
  "login.bleiben": "Stay signed in",
  "reg.alsWas": "I'm signing up as",
  "reg.akzeptiere": "I accept the",
  "recht.datenschutzerklaerung": "privacy policy",
  "mit.alle": "All members",
  "mit.weitere": "Other club members",
  "umf.tippen": "Tap to vote",
  "allg.jetztEintragen": "Sign up now",
  "allg.alleAnsehen": "View all",
  "allg.listeLaedt": "Loading list …",
  "news.keine": "No news yet.",
  "helf.niemand": "Nobody signed up yet",
  "helf.jemanden": "Assign someone",
  "helf.gesucht": "Volunteers needed",
  "fahr.mitfahren": "Get a lift",
  "fahr.loeschen": "Delete carpool",
  "fahr.anbieten": "Offer a seat",
  "ev.nurDiesen": "This date only",
  "ev.ganzeReihe": "Delete whole series",
  "ev.wirklichLoeschen": "Really delete this event?",
  "bei.art": "Fee type",
  "bei.mitglied": "Membership fee",
  "bei.familie": "Family fee",
  "verein.wechseln": "Switch club",
  "verein.deine": "Your clubs",
  "verein.beitrittAnfragen": "Request to join",
  "verein.beitrittAls": "I'm joining as",
  "verein.finden": "Find your club",
  "verein.findenHinweis": "Search for the club you want to join.",
  "verein.laden": "Loading clubs …",
  "verein.ladenFehler": "The club list could not be loaded.",
  "verein.neuAnlegen": "Register a new club",
  "verein.anlegen": "Create club",
  "verein.zurueckAuswahl": "Back to club selection",
  "verein.eigeneFarben": "Custom colours",
  "allg.erneut": "Try again",
  "allg.entsperren": "Unblock",
  "allg.gesperrt": "Your club needs to enable this section.",
  "allg.mehr": "Learn more",
  "tm.laden": "Loading teams …",
  "tm.keine": "No teams yet.",
  "straf.waehlen": "Choose a fine …",
  "straf.keine": "No fines issued yet.",
  "feld.beschreibung": "Description (optional)",
  "feld.nutzerSuchen": "Search members",
  "feld.mannschaftFiltern": "Filter by team",
  "kal.vorher": "Previous month",
  "kal.naechster": "Next month",
  "sp.zurAktion": "View offer",
  "sp.website": "Visit website",
  "konto.loeschenFrage": "Delete account permanently?",
  "allg.entfernen": "Remove",
  "allg.anlegen": "Create",
  "allg.hinzufuegen": "Add",
  "allg.abmelden": "Sign out",
  "allg.laedt": "Loading …",
  "allg.niemandGefunden": "Nobody found.",
  "allg.ablehnen": "Decline",
  "allg.annehmen": "Accept",
  "allg.austragen": "Sign off",
  "allg.uebernehmen": "Take it",
  "allg.eintragenKnopf": "Add",
  "feld.vollerName": "First and last name",
  "feld.rueckennummer": "Shirt number",
  "feld.stadt": "Town",
  "feld.gegner": "Opponent",
  "tm.mannschaften": "Teams",
  "recht.impressum": "Legal notice",
  "recht.datenschutz": "Privacy",
  "recht.nutzung": "Terms of use",
  "tm.meineTeams": "My teams",
  "tm.alleTeams": "All teams",
  "tm.kader": "Squad",
  "tm.meinTeam": "My team",
  "tm.mannschaft": "Team",
  "pf.einstellungen": "Settings",
  "pf.persoenlich": "Personal details",
  "pf.konto": "Account & security",
  "pf.vereinMitglied": "Club & membership",
  "pf.benachrichtigungen": "Notifications & calendar",
  "pf.zugang": "Access & referrals",
  "pf.support": "Support & feedback",
  "pf.einladen": "Invite friends",
  "pf.kontoLoeschen": "Delete account",
  "pf.vereinVerwalten": "Manage club",
  "pf.vereinseinstellungen": "Club settings",
  "ev.titel": "Schedule",
  "ev.eintragen": "Add event",
  "ev.alle": "All",
  "ev.training": "Training",
  "ev.spiele": "Matches",
  "ev.events": "Events",
  "ev.alleTeams": "All teams",
  "ev.datum": "Date",
  "ev.beginn": "Start",
  "ev.ende": "End",
  "ev.heimspiel": "Home match",
  "ev.spiel": "Match",
  "ev.vereinsevent": "Club event",
  "ev.wiederholend": "Recurring",
  "ev.werDabei": "Who's coming?",
  "ev.bistDuDabei": "Are you coming?",
  "ev.zugesagt": "Attending",
  "ev.abgesagt": "Not attending",
  "ev.absagen": "Cancel event",
  "ev.absageGrund": "Why is it cancelled?",
  "ev.jetztAbsagen": "Cancel now",
  "ev.keineTermine": "No events in this period.",
  "home.willkommen": "Welcome back",
  "home.naechstesSpiel": "Next match",
  "home.naechstesTraining": "Next training",
  "home.mitmachen": "Get involved",
  "home.aktionen": "Activities & votes",
  "home.tage": "DAYS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Save",
  "allg.abbrechen": "Cancel",
  "allg.loeschen": "Delete",
  "allg.bearbeiten": "Edit",
  "allg.schliessen": "Close",
  "allg.zurueck": "Back",
  "allg.weiter": "Continue",
  "allg.suchen": "Search …",
  "allg.keineEintraege": "Nothing here yet.",
  "nav.home": "Home",
  "nav.events": "Schedule",
  "nav.teams": "Teams",
  "nav.chat": "Chat",
  "nav.profile": "Profile",
  "nav.fees": "Fees",
  "nav.news": "News desk",
  "nav.admin": "Admin",
  "nav.sponsors": "Sponsors",
  "sub.season": "Athlete of the season",
  "sub.tipp": "Prediction game",
  "sub.duty": "Volunteer roster",
  "sub.postfach": "Notifications",
  "sprache.titel": "Choose your language",
  "sprache.hinweis": "Which language would you like to use? You can change this later in your profile.",
  "sprache.weiter": "Continue",
  "login.willkommen": "Welcome back",
  "login.email": "Email address",
  "login.passwort": "Password",
  "login.vergessen": "Forgot your password?",
  "login.anmelden": "Sign in",
  "login.keinKonto": "No account yet?",
  "login.registrieren": "Sign up",
  "reg.titel": "Create account",
  "reg.vorname": "First name",
  "reg.nachname": "Last name",
  "reg.schonMitglied": "Already a member?",
  "reg.anmelden": "Sign in",
  "reg.fastGeschafft": "Almost done",
  "reg.bestaetigen": "You will receive an email. Please confirm it so we can be sure your details are correct.",
  "reg.danach": "After that you can sign in.",
  "reg.jetztAnmelden": "Sign in now",
  "reg.keineMail": "No email? Check your spam folder — it usually arrives within a minute.",
  "profil.sprache": "Language",
  "profil.spracheHinweis": "App language",
};

const es: Woerterbuch = {
  "sys.demoDaten": "Datos de prueba",
  "sys.jaZuruecksetzen": "Sí, restablecer",
  "verein.logo": "Escudo del club",
  "verein.logoHinweis": "JPG, PNG o WebP · máx. 2 MB",
  "verein.farben": "Colores del club",
  "mit.offeneAntraege": "Solicitudes pendientes",
  "mit.antraegeLaden": "Cargando solicitudes …",
  "mit.keineAntraegeKurz": "Sin solicitudes",
  "mit.registrierung": "Registro",
  "mit.freigeben": "Aprobar",
  "allg.listeAktualisieren": "Actualizar lista",
  "mit.verwalten": "Gestionar miembros",
  "mit.laden": "Cargando miembros …",
  "mit.sperren": "Bloquear",
  "mit.keineVorhanden": "Todavía no hay miembros.",
  "mit.sperrliste": "Lista de bloqueados",
  "verein.funktionenFrage": "¿Qué funciones necesita tu club?",
  "rol.niemand": "Ahora mismo nadie tiene este rol.",
  "sys.profileZusammen": "Unir perfiles sin cuenta",
  "sys.platzhalter": "Perfil provisional (sin cuenta) …",
  "allg.nochNichts": "Todavía no hay nada",
  "sys.nichtBereit": "La aplicación no está lista",
  "store.apple": "Descargar en el App Store",
  "store.google": "Disponible en Google Play",
  "verein.waehlen": "Elegir club …",
  "verein.namePlatzhalter": "Nombre del club, p. ej. CD Ejemplo",
  "kal.woechentlich": "Semanal · domingo por la tarde",
  "kal.monatlich": "Mensual",
  "kal.verbinden": "Conectar con el calendario",
  "recht.bedingungen": "Condiciones",
  "konto.loeschenLang": "Eliminar cuenta y datos personales",
  "sais.beendet": "Votación cerrada — resultado final",
  "sais.ehrung": "Atleta de la temporada — entrega en la fiesta de verano",
  "tipp.jeTeam": "Quiniela por equipo",
  "tipp.niemand": "Todavía nadie en esta ronda.",
  "tipp.wartet": "Esperando el resultado",
  "tipp.ergebnisse": "Resultados y puntos",
  "prot.keineAufgaben": "Sin tareas pendientes — ¡bien! 🎉",
  "prot.neu": "Nueva acta",
  "prot.teilnehmer": "Asistentes",
  "prot.speichern": "Guardar acta y tareas",
  "prot.pflicht": "Escribe un título y el texto del acta.",
  "prot.vergangene": "Actas anteriores",
  "bei.erinnerungen": "Recordatorios de pago automáticos",
  "bei.keineOffenen": "No hay cuotas pendientes. 🎉",
  "sp.nichtFrei": "Tus patrocinadores aún no están activados",
  "sp.zuSehen": "Se muestra:",
  "sp.derSponsor": "El patrocinador",
  "sp.dieAktion": "La oferta (opcional)",
  "sp.stehtAufPlatz": "El patrocinador aparece en este espacio",
  "sp.entfernen": "Quitar patrocinador de este espacio",
  "umf.neu": "Nueva encuesta del club",
  "umf.mindestens": "Introduce al menos dos respuestas.",
  "allg.veroeffentlichen": "Publicar",
  "tm.mannschaftWaehlen2": "Elegir equipo …",
  "chat.kanaele": "Canales de chat",
  "sys.konten": "Resumen de cuentas",
  "straf.titel": "Sanciones",
  "straf.keineAktiven": "Sin sanciones abiertas.",
  "straf.historie": "Historial de sanciones",
  "auf.titel": "Tareas",
  "auf.keineEingetragen": "No estás apuntado a ninguna tarea.",
  "fahr.titel": "Viajes compartidos",
  "fahr.keineKurz": "Sin viajes compartidos.",
  "mit.keineAnfragen": "No hay solicitudes pendientes.",
  "verein.profilBearbeiten": "Editar perfil del club",
  "status.aktiv": "Activo",
  "status.ausstehend": "Pendiente",
  "status.inaktiv": "Inactivo",
  "status.gesperrt": "Bloqueado",
  "tm.athletenTeams": "Equipos en los que juego",
  "feld.telefonnummern": "Teléfonos",
  "feld.geburtstagZeigen": "Mostrar cumpleaños en el club",
  "gesch.w": "Mujer",
  "gesch.m": "Hombre",
  "gesch.d": "No binario",
  "gesch.k": "Prefiero no decirlo",
  "push.aufGeraet": "Notificaciones en este dispositivo",
  "sich.autoLogout": "Cierre de sesión automático",
  "sich.tage30": "A los 30 días",
  "sich.tage60": "A los 60 días",
  "sich.tage90": "A los 90 días",
  "zug.werben": "Clubes recomiendan clubes",
  "zug.codeKopieren": "Copiar código",
  "kal.abonnieren": "Suscribirse a la agenda",
  "kal.aktualisierung": "Actualización",
  "kal.nie": "Nunca automáticamente",
  "kal.taeglich": "Diaria",
  "kal.auswahlAufheben": "Quitar selección — usar mis equipos",
  "straf.verwaltung": "Sanciones",
  "straf.bisherige": "Sanciones anteriores",
  "straf.alle": "Todas las sanciones",
  "straf.historieLaedt": "Cargando historial …",
  "tm.athletWaehlen2": "Elegir jugador …",
  "allg.aendern": "Cambiar",
  "feld.personen": "Personas",
  "auf.ganzerVerein": "Todo el club",
  "auf.verantwortlich": "Responsable (varios posibles)",
  "auf.laden": "Cargando tareas …",
  "auf.keine": "Ahora no hay tareas abiertas.",
  "auf.uebernehmeIch": "Me encargo",
  "auf.zurueckziehen": "Retirar",
  "fz.keine": "Aún no hay vehículos.",
  "fz.kalenderLaedt": "Cargando calendario …",
  "fz.keineBuchungen": "Sin reservas este mes.",
  "fz.privat": "Reserva privada (sin equipo)",
  "tm.mannschaftWaehlen": "Elegir equipo …",
  "tel.laedt": "Cargando teléfono …",
  "tel.keine": "Sin teléfono guardado.",
  "helf.satzVorladen": "Cargar una plantilla …",
  "helf.stationen": "Puestos de este evento",
  "helf.alleEntfernen": "Quitar todo",
  "helf.keineSaetze": "Aún no hay plantillas.",
  "helf.satzLoeschen": "Eliminar plantilla",
  "zug.zurueckziehen": "Retirar solicitud",
  "sp.eigene": "Mostrar tus patrocinadores",
  "zug.vollzugang": "Solicitar acceso completo",
  "zug.keinAbo": "No necesitas suscripción propia",
  "mit.keine": "No se encontraron miembros.",
  "vid.keine": "Todavía no hay vídeos para tus roles.",
  "chat.wiederAnzeigen": "Toca un nombre para volver a mostrar a esa persona.",
  "chat.melden": "Denunciar",
  "chat.blockieren": "Bloquear",
  "chat.keiner": "Todavía no tienes chats",
  "chat.ausgeblendet": "Oculto para ti",
  "news.keineVeroeffentlicht": "Aún no hay noticias publicadas.",
  "bei.bezahlt": "Pagado",
  "bei.offen": "Sin pagar",
  "bei.keineDaten": "Todavía no hay registros de cuotas.",
  "bei.anzahlPersonen": "Número total de personas",
  "bei.weitereNamen": "Otros nombres sin cuenta",
  "bei.kommaHinweis": "Separa varios nombres con comas.",
  "fam.verknuepfung": "Vínculo familiar",
  "fam.rolle": "Rol en el vínculo",
  "fam.verbinden": "Vincular",
  "fam.keinProfil": "No se encontró ningún perfil.",
  "fam.kindAnlegen": "Añadir un hijo sin cuenta",
  "tm.kapitaenZuweisen": "Asignar capitán",
  "tm.athletWaehlen": "Elegir jugador …",
  "tm.keineZuordnung": "Todavía no estás en ningún equipo.",
  "tm.neuAnlegen": "Crear un equipo",
  "tm.erwachsene": "¿Equipo de adultos?",
  "tm.keineZuordnungKurz": "Sin equipo asignado.",
  "home.keinSpiel": "Ahora mismo no hay partido para este equipo.",
  "helf.niemandEingeteilt": "Nadie asignado a este evento.",
  "fahr.keine": "Aún no hay viaje compartido.",
  "ev.reiheFrage": "¿Solo esta fecha o toda la serie?",
  "home.geburtstag": "Cumpleaños hoy:",
  "home.willkommenKomma": "Bienvenido de nuevo,",
  "login.demo": "Accesos de prueba",
  "sys.vorschlag": "Sugerencia · el nombre coincide",
  "login.bleiben": "Mantener sesión",
  "reg.alsWas": "Me registro como",
  "reg.akzeptiere": "Acepto la",
  "recht.datenschutzerklaerung": "política de privacidad",
  "mit.alle": "Todos los miembros",
  "mit.weitere": "Otros miembros del club",
  "umf.tippen": "Toca para votar",
  "allg.jetztEintragen": "Apuntarme",
  "allg.alleAnsehen": "Ver todo",
  "allg.listeLaedt": "Cargando lista …",
  "news.keine": "Todavía no hay noticias.",
  "helf.niemand": "Nadie apuntado aún",
  "helf.jemanden": "Asignar a alguien",
  "helf.gesucht": "Se buscan voluntarios",
  "fahr.mitfahren": "Ir con alguien",
  "fahr.loeschen": "Eliminar el viaje",
  "fahr.anbieten": "Ofrecer plaza",
  "ev.nurDiesen": "Solo esta fecha",
  "ev.ganzeReihe": "Eliminar toda la serie",
  "ev.wirklichLoeschen": "¿Eliminar este evento?",
  "bei.art": "Tipo de cuota",
  "bei.mitglied": "Cuota de socio",
  "bei.familie": "Cuota familiar",
  "verein.wechseln": "Cambiar de club",
  "verein.deine": "Tus clubes",
  "verein.beitrittAnfragen": "Solicitar unirse",
  "verein.beitrittAls": "Me uno como",
  "verein.finden": "Encontrar tu club",
  "verein.findenHinweis": "Busca el club al que quieres unirte.",
  "verein.laden": "Cargando clubes …",
  "verein.ladenFehler": "No se pudo cargar la lista de clubes.",
  "verein.neuAnlegen": "Registrar un club nuevo",
  "verein.anlegen": "Crear club",
  "verein.zurueckAuswahl": "Volver a la selección de club",
  "verein.eigeneFarben": "Colores propios",
  "allg.erneut": "Intentar de nuevo",
  "allg.entsperren": "Desbloquear",
  "allg.gesperrt": "Tu club debe activar esta sección.",
  "allg.mehr": "Saber más",
  "tm.laden": "Cargando equipos …",
  "tm.keine": "Todavía no hay equipos.",
  "straf.waehlen": "Elegir sanción …",
  "straf.keine": "Aún no hay sanciones.",
  "feld.beschreibung": "Descripción (opcional)",
  "feld.nutzerSuchen": "Buscar miembros",
  "feld.mannschaftFiltern": "Filtrar por equipo",
  "kal.vorher": "Mes anterior",
  "kal.naechster": "Mes siguiente",
  "sp.zurAktion": "Ver oferta",
  "sp.website": "Ver web",
  "konto.loeschenFrage": "¿Eliminar la cuenta definitivamente?",
  "allg.entfernen": "Quitar",
  "allg.anlegen": "Crear",
  "allg.hinzufuegen": "Añadir",
  "allg.abmelden": "Cerrar sesión",
  "allg.laedt": "Cargando …",
  "allg.niemandGefunden": "Nadie encontrado.",
  "allg.ablehnen": "Rechazar",
  "allg.annehmen": "Aceptar",
  "allg.austragen": "Darse de baja",
  "allg.uebernehmen": "Asumir",
  "allg.eintragenKnopf": "Añadir",
  "feld.vollerName": "Nombre y apellidos",
  "feld.rueckennummer": "Dorsal",
  "feld.stadt": "Ciudad",
  "feld.gegner": "Rival",
  "tm.mannschaften": "Equipos",
  "recht.impressum": "Aviso legal",
  "recht.datenschutz": "Privacidad",
  "recht.nutzung": "Condiciones de uso",
  "tm.meineTeams": "Mis equipos",
  "tm.alleTeams": "Todos los equipos",
  "tm.kader": "Plantilla",
  "tm.meinTeam": "Mi equipo",
  "tm.mannschaft": "Equipo",
  "pf.einstellungen": "Ajustes",
  "pf.persoenlich": "Datos personales",
  "pf.konto": "Cuenta y seguridad",
  "pf.vereinMitglied": "Club y membresía",
  "pf.benachrichtigungen": "Notificaciones y calendario",
  "pf.zugang": "Acceso y recomendaciones",
  "pf.support": "Soporte y sugerencias",
  "pf.einladen": "Invitar amigos",
  "pf.kontoLoeschen": "Eliminar cuenta",
  "pf.vereinVerwalten": "Gestionar club",
  "pf.vereinseinstellungen": "Ajustes del club",
  "ev.titel": "Agenda",
  "ev.eintragen": "Añadir evento",
  "ev.alle": "Todos",
  "ev.training": "Entrenamiento",
  "ev.spiele": "Partidos",
  "ev.events": "Eventos",
  "ev.alleTeams": "Todos los equipos",
  "ev.datum": "Fecha",
  "ev.beginn": "Inicio",
  "ev.ende": "Fin",
  "ev.heimspiel": "Partido en casa",
  "ev.spiel": "Partido",
  "ev.vereinsevent": "Evento del club",
  "ev.wiederholend": "Periódico",
  "ev.werDabei": "¿Quién viene?",
  "ev.bistDuDabei": "¿Vienes?",
  "ev.zugesagt": "Asisto",
  "ev.abgesagt": "No asisto",
  "ev.absagen": "Cancelar",
  "ev.absageGrund": "¿Por qué se cancela?",
  "ev.jetztAbsagen": "Cancelar ahora",
  "ev.keineTermine": "No hay eventos en este periodo.",
  "home.willkommen": "Bienvenido de nuevo",
  "home.naechstesSpiel": "Próximo partido",
  "home.naechstesTraining": "Próximo entrenamiento",
  "home.mitmachen": "Participa",
  "home.aktionen": "Actividades y votaciones",
  "home.tage": "DÍAS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Guardar",
  "allg.abbrechen": "Cancelar",
  "allg.loeschen": "Eliminar",
  "allg.bearbeiten": "Editar",
  "allg.schliessen": "Cerrar",
  "allg.zurueck": "Atrás",
  "allg.weiter": "Continuar",
  "allg.suchen": "Buscar …",
  "allg.keineEintraege": "Todavía no hay nada.",
  "nav.home": "Inicio",
  "nav.events": "Agenda",
  "nav.teams": "Equipos",
  "nav.chat": "Chat",
  "nav.profile": "Perfil",
  "nav.fees": "Cuotas",
  "nav.news": "Redacción",
  "nav.admin": "Administración",
  "nav.sponsors": "Patrocinadores",
  "sub.season": "Atleta de la temporada",
  "sub.tipp": "Quiniela",
  "sub.duty": "Turnos de voluntarios",
  "sub.postfach": "Notificaciones",
  "sprache.titel": "Elige tu idioma",
  "sprache.hinweis": "¿En qué idioma quieres usar la aplicación? Puedes cambiarlo más tarde en tu perfil.",
  "sprache.weiter": "Continuar",
  "login.willkommen": "Bienvenido de nuevo",
  "login.email": "Correo electrónico",
  "login.passwort": "Contraseña",
  "login.vergessen": "¿Olvidaste tu contraseña?",
  "login.anmelden": "Iniciar sesión",
  "login.keinKonto": "¿Aún no tienes cuenta?",
  "login.registrieren": "Regístrate",
  "reg.titel": "Crear cuenta",
  "reg.vorname": "Nombre",
  "reg.nachname": "Apellido",
  "reg.schonMitglied": "¿Ya eres miembro?",
  "reg.anmelden": "Iniciar sesión",
  "reg.fastGeschafft": "Casi listo",
  "reg.bestaetigen": "Recibirás un correo electrónico. Confírmalo para que podamos asegurarnos de que tus datos son correctos.",
  "reg.danach": "Después podrás iniciar sesión.",
  "reg.jetztAnmelden": "Iniciar sesión",
  "reg.keineMail": "¿No recibiste el correo? Revisa la carpeta de spam — suele llegar en un minuto.",
  "profil.sprache": "Idioma",
  "profil.spracheHinweis": "Idioma de la aplicación",
};

const pt: Woerterbuch = {
  "sys.demoDaten": "Dados de demonstração",
  "sys.jaZuruecksetzen": "Sim, repor",
  "verein.logo": "Emblema do clube",
  "verein.logoHinweis": "JPG, PNG ou WebP · máx. 2 MB",
  "verein.farben": "Cores do clube",
  "mit.offeneAntraege": "Pedidos pendentes",
  "mit.antraegeLaden": "A carregar pedidos …",
  "mit.keineAntraegeKurz": "Sem pedidos",
  "mit.registrierung": "Registo",
  "mit.freigeben": "Aprovar",
  "allg.listeAktualisieren": "Atualizar lista",
  "mit.verwalten": "Gerir membros",
  "mit.laden": "A carregar membros …",
  "mit.sperren": "Bloquear",
  "mit.keineVorhanden": "Ainda não há membros.",
  "mit.sperrliste": "Lista de bloqueados",
  "verein.funktionenFrage": "De que funções precisa o teu clube?",
  "rol.niemand": "Ninguém tem este papel de momento.",
  "sys.profileZusammen": "Juntar perfis sem conta",
  "sys.platzhalter": "Perfil provisório (sem conta) …",
  "allg.nochNichts": "Ainda não há nada",
  "sys.nichtBereit": "A aplicação não está pronta",
  "store.apple": "Descarregar na App Store",
  "store.google": "Disponível no Google Play",
  "verein.waehlen": "Escolher clube …",
  "verein.namePlatzhalter": "Nome do clube, p. ex. CD Exemplo",
  "kal.woechentlich": "Semanal · domingo à noite",
  "kal.monatlich": "Mensal",
  "kal.verbinden": "Ligar ao calendário do telemóvel",
  "recht.bedingungen": "Condições",
  "konto.loeschenLang": "Eliminar conta e dados pessoais",
  "sais.beendet": "Votação encerrada — resultado final",
  "sais.ehrung": "Atleta da época — entrega na festa de verão",
  "tipp.jeTeam": "Bolão por equipa",
  "tipp.niemand": "Ainda ninguém nesta ronda.",
  "tipp.wartet": "À espera do resultado",
  "tipp.ergebnisse": "Resultados e pontos",
  "prot.keineAufgaben": "Sem tarefas em aberto — muito bem! 🎉",
  "prot.neu": "Nova ata",
  "prot.teilnehmer": "Participantes",
  "prot.speichern": "Guardar ata e tarefas",
  "prot.pflicht": "Escreve um título e o texto da ata.",
  "prot.vergangene": "Atas anteriores",
  "bei.erinnerungen": "Lembretes de pagamento automáticos",
  "bei.keineOffenen": "Não há quotas em aberto. 🎉",
  "sp.nichtFrei": "Os teus patrocinadores ainda não estão ativos",
  "sp.zuSehen": "A mostrar:",
  "sp.derSponsor": "O patrocinador",
  "sp.dieAktion": "A promoção (opcional)",
  "sp.stehtAufPlatz": "O patrocinador aparece neste espaço",
  "sp.entfernen": "Retirar patrocinador deste espaço",
  "umf.neu": "Nova sondagem do clube",
  "umf.mindestens": "Indica pelo menos duas respostas.",
  "allg.veroeffentlichen": "Publicar",
  "tm.mannschaftWaehlen2": "Escolher equipa …",
  "chat.kanaele": "Canais de conversa",
  "sys.konten": "Resumo de contas",
  "straf.titel": "Multas",
  "straf.keineAktiven": "Sem multas em aberto.",
  "straf.historie": "Histórico de multas",
  "auf.titel": "Tarefas",
  "auf.keineEingetragen": "Não estás inscrito em nenhuma tarefa.",
  "fahr.titel": "Boleias",
  "fahr.keineKurz": "Sem boleias.",
  "mit.keineAnfragen": "Não há pedidos pendentes.",
  "verein.profilBearbeiten": "Editar perfil do clube",
  "status.aktiv": "Ativo",
  "status.ausstehend": "Pendente",
  "status.inaktiv": "Inativo",
  "status.gesperrt": "Bloqueado",
  "tm.athletenTeams": "Equipas onde jogo",
  "feld.telefonnummern": "Telefones",
  "feld.geburtstagZeigen": "Mostrar aniversário no clube",
  "gesch.w": "Feminino",
  "gesch.m": "Masculino",
  "gesch.d": "Não binário",
  "gesch.k": "Prefiro não dizer",
  "push.aufGeraet": "Notificações neste dispositivo",
  "sich.autoLogout": "Sessão termina automaticamente",
  "sich.tage30": "Ao fim de 30 dias",
  "sich.tage60": "Ao fim de 60 dias",
  "sich.tage90": "Ao fim de 90 dias",
  "zug.werben": "Clubes recomendam clubes",
  "zug.codeKopieren": "Copiar código",
  "kal.abonnieren": "Subscrever a agenda",
  "kal.aktualisierung": "Atualização",
  "kal.nie": "Nunca automaticamente",
  "kal.taeglich": "Diária",
  "kal.auswahlAufheben": "Limpar seleção — usar as minhas equipas",
  "straf.verwaltung": "Multas",
  "straf.bisherige": "Multas anteriores",
  "straf.alle": "Todas as multas",
  "straf.historieLaedt": "A carregar histórico …",
  "tm.athletWaehlen2": "Escolher jogador …",
  "allg.aendern": "Alterar",
  "feld.personen": "Pessoas",
  "auf.ganzerVerein": "Todo o clube",
  "auf.verantwortlich": "Responsável (vários possíveis)",
  "auf.laden": "A carregar tarefas …",
  "auf.keine": "Não há tarefas abertas de momento.",
  "auf.uebernehmeIch": "Eu trato disso",
  "auf.zurueckziehen": "Retirar",
  "fz.keine": "Ainda não há veículos.",
  "fz.kalenderLaedt": "A carregar calendário …",
  "fz.keineBuchungen": "Sem reservas este mês.",
  "fz.privat": "Reserva privada (sem equipa)",
  "tm.mannschaftWaehlen": "Escolher equipa …",
  "tel.laedt": "A carregar telefone …",
  "tel.keine": "Sem telefone guardado.",
  "helf.satzVorladen": "Carregar um modelo …",
  "helf.stationen": "Postos deste evento",
  "helf.alleEntfernen": "Remover todos",
  "helf.keineSaetze": "Ainda não há modelos.",
  "helf.satzLoeschen": "Eliminar modelo",
  "zug.zurueckziehen": "Retirar pedido",
  "sp.eigene": "Mostrar os teus patrocinadores",
  "zug.vollzugang": "Pedir acesso completo",
  "zug.keinAbo": "Não precisas de subscrição própria",
  "mit.keine": "Nenhum membro encontrado.",
  "vid.keine": "Ainda não há vídeos para os teus papéis.",
  "chat.wiederAnzeigen": "Toca num nome para mostrar essa pessoa de novo.",
  "chat.melden": "Denunciar",
  "chat.blockieren": "Bloquear",
  "chat.keiner": "Ainda não tens conversas",
  "chat.ausgeblendet": "Oculto para ti",
  "news.keineVeroeffentlicht": "Ainda não há notícias publicadas.",
  "bei.bezahlt": "Pago",
  "bei.offen": "Por pagar",
  "bei.keineDaten": "Ainda não há registos de quotas.",
  "bei.anzahlPersonen": "Número total de pessoas",
  "bei.weitereNamen": "Outros nomes sem conta",
  "bei.kommaHinweis": "Separa vários nomes por vírgulas.",
  "fam.verknuepfung": "Ligação familiar",
  "fam.rolle": "Papel na ligação",
  "fam.verbinden": "Ligar",
  "fam.keinProfil": "Nenhum perfil encontrado.",
  "fam.kindAnlegen": "Adicionar um filho sem conta",
  "tm.kapitaenZuweisen": "Atribuir capitão",
  "tm.athletWaehlen": "Escolher jogador …",
  "tm.keineZuordnung": "Ainda não estás numa equipa.",
  "tm.neuAnlegen": "Criar uma equipa",
  "tm.erwachsene": "Equipa de adultos?",
  "tm.keineZuordnungKurz": "Sem equipa atribuída.",
  "home.keinSpiel": "Não há jogo marcado para esta equipa.",
  "helf.niemandEingeteilt": "Ninguém atribuído a este evento.",
  "fahr.keine": "Ainda não há boleias para este evento.",
  "ev.reiheFrage": "Só esta data ou toda a série?",
  "home.geburtstag": "Aniversário hoje:",
  "home.willkommenKomma": "Bem-vindo de volta,",
  "login.demo": "Acessos de demonstração",
  "sys.vorschlag": "Sugestão · o nome coincide",
  "login.bleiben": "Manter sessão",
  "reg.alsWas": "Registo-me como",
  "reg.akzeptiere": "Aceito a",
  "recht.datenschutzerklaerung": "política de privacidade",
  "mit.alle": "Todos os membros",
  "mit.weitere": "Outros membros do clube",
  "umf.tippen": "Toca para votar",
  "allg.jetztEintragen": "Inscrever-me",
  "allg.alleAnsehen": "Ver tudo",
  "allg.listeLaedt": "A carregar lista …",
  "news.keine": "Ainda não há notícias.",
  "helf.niemand": "Ainda ninguém inscrito",
  "helf.jemanden": "Atribuir a alguém",
  "helf.gesucht": "Precisamos de voluntários",
  "fahr.mitfahren": "Ir com alguém",
  "fahr.loeschen": "Eliminar boleia",
  "fahr.anbieten": "Oferecer lugar",
  "ev.nurDiesen": "Só esta data",
  "ev.ganzeReihe": "Eliminar toda a série",
  "ev.wirklichLoeschen": "Eliminar mesmo este evento?",
  "bei.art": "Tipo de quota",
  "bei.mitglied": "Quota de sócio",
  "bei.familie": "Quota familiar",
  "verein.wechseln": "Mudar de clube",
  "verein.deine": "Os teus clubes",
  "verein.beitrittAnfragen": "Pedir adesão",
  "verein.beitrittAls": "Adiro como",
  "verein.finden": "Encontrar o teu clube",
  "verein.findenHinweis": "Procura o clube a que queres aderir.",
  "verein.laden": "A carregar clubes …",
  "verein.ladenFehler": "Não foi possível carregar a lista de clubes.",
  "verein.neuAnlegen": "Registar um novo clube",
  "verein.anlegen": "Criar clube",
  "verein.zurueckAuswahl": "Voltar à escolha do clube",
  "verein.eigeneFarben": "Cores próprias",
  "allg.erneut": "Tentar de novo",
  "allg.entsperren": "Desbloquear",
  "allg.gesperrt": "O teu clube tem de ativar esta área.",
  "allg.mehr": "Saber mais",
  "tm.laden": "A carregar equipas …",
  "tm.keine": "Ainda não há equipas.",
  "straf.waehlen": "Escolher multa …",
  "straf.keine": "Ainda não há multas.",
  "feld.beschreibung": "Descrição (opcional)",
  "feld.nutzerSuchen": "Procurar membros",
  "feld.mannschaftFiltern": "Filtrar por equipa",
  "kal.vorher": "Mês anterior",
  "kal.naechster": "Mês seguinte",
  "sp.zurAktion": "Ver oferta",
  "sp.website": "Ver site",
  "konto.loeschenFrage": "Eliminar a conta definitivamente?",
  "allg.entfernen": "Remover",
  "allg.anlegen": "Criar",
  "allg.hinzufuegen": "Adicionar",
  "allg.abmelden": "Terminar sessão",
  "allg.laedt": "A carregar …",
  "allg.niemandGefunden": "Ninguém encontrado.",
  "allg.ablehnen": "Recusar",
  "allg.annehmen": "Aceitar",
  "allg.austragen": "Retirar-me",
  "allg.uebernehmen": "Assumir",
  "allg.eintragenKnopf": "Adicionar",
  "feld.vollerName": "Nome completo",
  "feld.rueckennummer": "Número",
  "feld.stadt": "Cidade",
  "feld.gegner": "Adversário",
  "tm.mannschaften": "Equipas",
  "recht.impressum": "Ficha técnica",
  "recht.datenschutz": "Privacidade",
  "recht.nutzung": "Termos de utilização",
  "tm.meineTeams": "As minhas equipas",
  "tm.alleTeams": "Todas as equipas",
  "tm.kader": "Plantel",
  "tm.meinTeam": "A minha equipa",
  "tm.mannschaft": "Equipa",
  "pf.einstellungen": "Definições",
  "pf.persoenlich": "Dados pessoais",
  "pf.konto": "Conta e segurança",
  "pf.vereinMitglied": "Clube e filiação",
  "pf.benachrichtigungen": "Notificações e calendário",
  "pf.zugang": "Acesso e recomendações",
  "pf.support": "Apoio e sugestões",
  "pf.einladen": "Convidar amigos",
  "pf.kontoLoeschen": "Eliminar conta",
  "pf.vereinVerwalten": "Gerir clube",
  "pf.vereinseinstellungen": "Definições do clube",
  "ev.titel": "Agenda",
  "ev.eintragen": "Adicionar evento",
  "ev.alle": "Todos",
  "ev.training": "Treino",
  "ev.spiele": "Jogos",
  "ev.events": "Eventos",
  "ev.alleTeams": "Todas as equipas",
  "ev.datum": "Data",
  "ev.beginn": "Início",
  "ev.ende": "Fim",
  "ev.heimspiel": "Jogo em casa",
  "ev.spiel": "Jogo",
  "ev.vereinsevent": "Evento do clube",
  "ev.wiederholend": "Recorrente",
  "ev.werDabei": "Quem vem?",
  "ev.bistDuDabei": "Vens?",
  "ev.zugesagt": "Vou",
  "ev.abgesagt": "Não vou",
  "ev.absagen": "Cancelar",
  "ev.absageGrund": "Porquê o cancelamento?",
  "ev.jetztAbsagen": "Cancelar agora",
  "ev.keineTermine": "Não há eventos neste período.",
  "home.willkommen": "Bem-vindo de volta",
  "home.naechstesSpiel": "Próximo jogo",
  "home.naechstesTraining": "Próximo treino",
  "home.mitmachen": "Participa",
  "home.aktionen": "Atividades e votações",
  "home.tage": "DIAS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Guardar",
  "allg.abbrechen": "Cancelar",
  "allg.loeschen": "Eliminar",
  "allg.bearbeiten": "Editar",
  "allg.schliessen": "Fechar",
  "allg.zurueck": "Voltar",
  "allg.weiter": "Continuar",
  "allg.suchen": "Procurar …",
  "allg.keineEintraege": "Ainda não há nada.",
  "nav.home": "Início",
  "nav.events": "Agenda",
  "nav.teams": "Equipas",
  "nav.chat": "Chat",
  "nav.profile": "Perfil",
  "nav.fees": "Quotas",
  "nav.news": "Redação",
  "nav.admin": "Administração",
  "nav.sponsors": "Patrocinadores",
  "sub.season": "Atleta da época",
  "sub.tipp": "Bolão",
  "sub.duty": "Escala de voluntários",
  "sub.postfach": "Notificações",
  "sprache.titel": "Escolhe o teu idioma",
  "sprache.hinweis": "Em que idioma queres usar a aplicação? Podes alterar mais tarde no teu perfil.",
  "sprache.weiter": "Continuar",
  "login.willkommen": "Bem-vindo de volta",
  "login.email": "Endereço de e-mail",
  "login.passwort": "Palavra-passe",
  "login.vergessen": "Esqueceste a palavra-passe?",
  "login.anmelden": "Entrar",
  "login.keinKonto": "Ainda não tens conta?",
  "login.registrieren": "Registar",
  "reg.titel": "Criar conta",
  "reg.vorname": "Nome próprio",
  "reg.nachname": "Apelido",
  "reg.schonMitglied": "Já és membro?",
  "reg.anmelden": "Entrar",
  "reg.fastGeschafft": "Quase pronto",
  "reg.bestaetigen": "Vais receber um e-mail. Confirma-o para termos a certeza de que os teus dados estão corretos.",
  "reg.danach": "Depois disso podes entrar.",
  "reg.jetztAnmelden": "Entrar agora",
  "reg.keineMail": "Não recebeste o e-mail? Vê a pasta de spam — costuma chegar num minuto.",
  "profil.sprache": "Idioma",
  "profil.spracheHinweis": "Idioma da aplicação",
};

const it: Woerterbuch = {
  "sys.demoDaten": "Dati dimostrativi",
  "sys.jaZuruecksetzen": "Sì, ripristina",
  "verein.logo": "Stemma del club",
  "verein.logoHinweis": "JPG, PNG o WebP · max 2 MB",
  "verein.farben": "Colori del club",
  "mit.offeneAntraege": "Richieste in sospeso",
  "mit.antraegeLaden": "Caricamento richieste …",
  "mit.keineAntraegeKurz": "Nessuna richiesta",
  "mit.registrierung": "Registrazione",
  "mit.freigeben": "Approva",
  "allg.listeAktualisieren": "Aggiorna elenco",
  "mit.verwalten": "Gestisci tesseramenti",
  "mit.laden": "Caricamento membri …",
  "mit.sperren": "Blocca",
  "mit.keineVorhanden": "Ancora nessun tesseramento.",
  "mit.sperrliste": "Elenco bloccati",
  "verein.funktionenFrage": "Di quali funzioni ha bisogno il club?",
  "rol.niemand": "Al momento nessuno ha questo ruolo.",
  "sys.profileZusammen": "Unisci profili senza account",
  "sys.platzhalter": "Profilo provvisorio (senza account) …",
  "allg.nochNichts": "Ancora nulla",
  "sys.nichtBereit": "L'app non è pronta",
  "store.apple": "Scarica su App Store",
  "store.google": "Disponibile su Google Play",
  "verein.waehlen": "Scegli un club …",
  "verein.namePlatzhalter": "Nome del club, es. ASD Esempio",
  "kal.woechentlich": "Settimanale · domenica sera",
  "kal.monatlich": "Mensile",
  "kal.verbinden": "Collega al calendario del telefono",
  "recht.bedingungen": "Condizioni",
  "konto.loeschenLang": "Elimina account e dati personali",
  "sais.beendet": "Votazione chiusa — risultato definitivo",
  "sais.ehrung": "Atleta della stagione — premiazione alla festa d'estate",
  "tipp.jeTeam": "Pronostici per squadra",
  "tipp.niemand": "Ancora nessuno in questo girone.",
  "tipp.wartet": "In attesa del risultato",
  "tipp.ergebnisse": "Risultati e punti",
  "prot.keineAufgaben": "Nessuna attività aperta — bene! 🎉",
  "prot.neu": "Nuovo verbale",
  "prot.teilnehmer": "Partecipanti",
  "prot.speichern": "Salva verbale e attività",
  "prot.pflicht": "Inserisci titolo e testo del verbale.",
  "prot.vergangene": "Verbali precedenti",
  "bei.erinnerungen": "Promemoria di pagamento automatici",
  "bei.keineOffenen": "Nessuna quota in sospeso. 🎉",
  "sp.nichtFrei": "I tuoi sponsor non sono ancora attivi",
  "sp.zuSehen": "In mostra:",
  "sp.derSponsor": "Lo sponsor",
  "sp.dieAktion": "La promozione (facoltativa)",
  "sp.stehtAufPlatz": "Lo sponsor compare in questo spazio",
  "sp.entfernen": "Togli lo sponsor da questo spazio",
  "umf.neu": "Nuovo sondaggio del club",
  "umf.mindestens": "Inserisci almeno due risposte.",
  "allg.veroeffentlichen": "Pubblica",
  "tm.mannschaftWaehlen2": "Scegli una squadra …",
  "chat.kanaele": "Canali di chat",
  "sys.konten": "Panoramica account",
  "straf.titel": "Multe",
  "straf.keineAktiven": "Nessuna multa aperta.",
  "straf.historie": "Storico multe",
  "auf.titel": "Attività",
  "auf.keineEingetragen": "Non sei iscritto a nessuna attività.",
  "fahr.titel": "Passaggi",
  "fahr.keineKurz": "Nessun passaggio.",
  "mit.keineAnfragen": "Nessuna richiesta in sospeso.",
  "verein.profilBearbeiten": "Modifica profilo del club",
  "status.aktiv": "Attivo",
  "status.ausstehend": "In attesa",
  "status.inaktiv": "Inattivo",
  "status.gesperrt": "Bloccato",
  "tm.athletenTeams": "Squadre in cui gioco",
  "feld.telefonnummern": "Numeri di telefono",
  "feld.geburtstagZeigen": "Mostra il compleanno nel club",
  "gesch.w": "Femmina",
  "gesch.m": "Maschio",
  "gesch.d": "Non binario",
  "gesch.k": "Preferisco non dirlo",
  "push.aufGeraet": "Notifiche su questo dispositivo",
  "sich.autoLogout": "Disconnessione automatica",
  "sich.tage30": "Dopo 30 giorni",
  "sich.tage60": "Dopo 60 giorni",
  "sich.tage90": "Dopo 90 giorni",
  "zug.werben": "I club invitano club",
  "zug.codeKopieren": "Copia codice",
  "kal.abonnieren": "Abbonati al calendario",
  "kal.aktualisierung": "Aggiornamento",
  "kal.nie": "Mai automaticamente",
  "kal.taeglich": "Ogni giorno",
  "kal.auswahlAufheben": "Togli la selezione — usa le mie squadre",
  "straf.verwaltung": "Multe",
  "straf.bisherige": "Multe finora",
  "straf.alle": "Tutte le multe",
  "straf.historieLaedt": "Caricamento storico …",
  "tm.athletWaehlen2": "Scegli un giocatore …",
  "allg.aendern": "Modifica",
  "feld.personen": "Persone",
  "auf.ganzerVerein": "Tutto il club",
  "auf.verantwortlich": "Responsabile (anche più di uno)",
  "auf.laden": "Caricamento attività …",
  "auf.keine": "Nessuna attività aperta al momento.",
  "auf.uebernehmeIch": "Ci penso io",
  "auf.zurueckziehen": "Ritira",
  "fz.keine": "Ancora nessun veicolo.",
  "fz.kalenderLaedt": "Caricamento calendario …",
  "fz.keineBuchungen": "Nessuna prenotazione questo mese.",
  "fz.privat": "Prenotazione privata (senza squadra)",
  "tm.mannschaftWaehlen": "Scegli una squadra …",
  "tel.laedt": "Caricamento telefono …",
  "tel.keine": "Nessun telefono salvato.",
  "helf.satzVorladen": "Carica un modello …",
  "helf.stationen": "Postazioni di questo evento",
  "helf.alleEntfernen": "Rimuovi tutte",
  "helf.keineSaetze": "Ancora nessun modello.",
  "helf.satzLoeschen": "Elimina modello",
  "zug.zurueckziehen": "Ritira la richiesta",
  "sp.eigene": "Mostra i tuoi sponsor",
  "zug.vollzugang": "Richiedi accesso completo",
  "zug.keinAbo": "Non serve un abbonamento tuo",
  "mit.keine": "Nessun membro trovato.",
  "vid.keine": "Ancora nessun video per i tuoi ruoli.",
  "chat.wiederAnzeigen": "Tocca un nome per mostrare di nuovo la persona.",
  "chat.melden": "Segnala",
  "chat.blockieren": "Blocca",
  "chat.keiner": "Ancora nessuna chat",
  "chat.ausgeblendet": "Nascosto per te",
  "news.keineVeroeffentlicht": "Ancora nessuna notizia pubblicata.",
  "bei.bezahlt": "Pagato",
  "bei.offen": "Non ancora pagato",
  "bei.keineDaten": "Ancora nessuna quota registrata.",
  "bei.anzahlPersonen": "Numero totale di persone",
  "bei.weitereNamen": "Altri nomi senza account",
  "bei.kommaHinweis": "Separa più nomi con una virgola.",
  "fam.verknuepfung": "Collegamento familiare",
  "fam.rolle": "Ruolo nel collegamento",
  "fam.verbinden": "Collega",
  "fam.keinProfil": "Nessun profilo trovato.",
  "fam.kindAnlegen": "Aggiungi un figlio senza account",
  "tm.kapitaenZuweisen": "Assegna il capitano",
  "tm.athletWaehlen": "Scegli un giocatore …",
  "tm.keineZuordnung": "Non sei ancora in una squadra.",
  "tm.neuAnlegen": "Crea una squadra",
  "tm.erwachsene": "Squadra di adulti?",
  "tm.keineZuordnungKurz": "Nessuna squadra assegnata.",
  "home.keinSpiel": "Nessuna partita in programma per questa squadra.",
  "helf.niemandEingeteilt": "Nessuno assegnato a questo evento.",
  "fahr.keine": "Ancora nessun passaggio per questo evento.",
  "ev.reiheFrage": "Solo questa data o tutta la serie?",
  "home.geburtstag": "Compleanno oggi:",
  "home.willkommenKomma": "Bentornato,",
  "login.demo": "Accessi di prova",
  "sys.vorschlag": "Suggerimento · il nome corrisponde",
  "login.bleiben": "Resta connesso",
  "reg.alsWas": "Mi registro come",
  "reg.akzeptiere": "Accetto la",
  "recht.datenschutzerklaerung": "informativa sulla privacy",
  "mit.alle": "Tutti i membri",
  "mit.weitere": "Altri membri del club",
  "umf.tippen": "Tocca per votare",
  "allg.jetztEintragen": "Iscrivimi",
  "allg.alleAnsehen": "Vedi tutto",
  "allg.listeLaedt": "Caricamento elenco …",
  "news.keine": "Ancora nessuna notizia.",
  "helf.niemand": "Ancora nessun iscritto",
  "helf.jemanden": "Assegna a qualcuno",
  "helf.gesucht": "Cerchiamo volontari",
  "fahr.mitfahren": "Cerco passaggio",
  "fahr.loeschen": "Elimina il passaggio",
  "fahr.anbieten": "Offro un posto",
  "ev.nurDiesen": "Solo questa data",
  "ev.ganzeReihe": "Elimina tutta la serie",
  "ev.wirklichLoeschen": "Eliminare questo evento?",
  "bei.art": "Tipo di quota",
  "bei.mitglied": "Quota associativa",
  "bei.familie": "Quota famiglia",
  "verein.wechseln": "Cambia club",
  "verein.deine": "I tuoi club",
  "verein.beitrittAnfragen": "Richiedi l'iscrizione",
  "verein.beitrittAls": "Mi iscrivo come",
  "verein.finden": "Trova il tuo club",
  "verein.findenHinweis": "Cerca il club a cui vuoi iscriverti.",
  "verein.laden": "Caricamento club …",
  "verein.ladenFehler": "Impossibile caricare l'elenco dei club.",
  "verein.neuAnlegen": "Registra un nuovo club",
  "verein.anlegen": "Crea club",
  "verein.zurueckAuswahl": "Torna alla scelta del club",
  "verein.eigeneFarben": "Colori personalizzati",
  "allg.erneut": "Riprova",
  "allg.entsperren": "Sblocca",
  "allg.gesperrt": "Il club deve attivare questa sezione.",
  "allg.mehr": "Scopri di più",
  "tm.laden": "Caricamento squadre …",
  "tm.keine": "Ancora nessuna squadra.",
  "straf.waehlen": "Scegli la multa …",
  "straf.keine": "Nessuna multa assegnata.",
  "feld.beschreibung": "Descrizione (facoltativa)",
  "feld.nutzerSuchen": "Cerca membri",
  "feld.mannschaftFiltern": "Filtra per squadra",
  "kal.vorher": "Mese precedente",
  "kal.naechster": "Mese successivo",
  "sp.zurAktion": "Vedi offerta",
  "sp.website": "Vai al sito",
  "konto.loeschenFrage": "Eliminare l'account definitivamente?",
  "allg.entfernen": "Rimuovi",
  "allg.anlegen": "Crea",
  "allg.hinzufuegen": "Aggiungi",
  "allg.abmelden": "Esci",
  "allg.laedt": "Caricamento …",
  "allg.niemandGefunden": "Nessuno trovato.",
  "allg.ablehnen": "Rifiuta",
  "allg.annehmen": "Accetta",
  "allg.austragen": "Cancellati",
  "allg.uebernehmen": "Prendo io",
  "allg.eintragenKnopf": "Aggiungi",
  "feld.vollerName": "Nome e cognome",
  "feld.rueckennummer": "Numero di maglia",
  "feld.stadt": "Città",
  "feld.gegner": "Avversario",
  "tm.mannschaften": "Squadre",
  "recht.impressum": "Note legali",
  "recht.datenschutz": "Privacy",
  "recht.nutzung": "Condizioni d'uso",
  "tm.meineTeams": "Le mie squadre",
  "tm.alleTeams": "Tutte le squadre",
  "tm.kader": "Rosa",
  "tm.meinTeam": "La mia squadra",
  "tm.mannschaft": "Squadra",
  "pf.einstellungen": "Impostazioni",
  "pf.persoenlich": "Dati personali",
  "pf.konto": "Account e sicurezza",
  "pf.vereinMitglied": "Club e tesseramento",
  "pf.benachrichtigungen": "Notifiche e calendario",
  "pf.zugang": "Accesso e inviti",
  "pf.support": "Assistenza e feedback",
  "pf.einladen": "Invita amici",
  "pf.kontoLoeschen": "Elimina account",
  "pf.vereinVerwalten": "Gestisci club",
  "pf.vereinseinstellungen": "Impostazioni club",
  "ev.titel": "Calendario",
  "ev.eintragen": "Aggiungi evento",
  "ev.alle": "Tutti",
  "ev.training": "Allenamento",
  "ev.spiele": "Partite",
  "ev.events": "Eventi",
  "ev.alleTeams": "Tutte le squadre",
  "ev.datum": "Data",
  "ev.beginn": "Inizio",
  "ev.ende": "Fine",
  "ev.heimspiel": "Partita in casa",
  "ev.spiel": "Partita",
  "ev.vereinsevent": "Evento del club",
  "ev.wiederholend": "Ricorrente",
  "ev.werDabei": "Chi viene?",
  "ev.bistDuDabei": "Ci sei?",
  "ev.zugesagt": "Presente",
  "ev.abgesagt": "Assente",
  "ev.absagen": "Annulla",
  "ev.absageGrund": "Perché viene annullato?",
  "ev.jetztAbsagen": "Annulla ora",
  "ev.keineTermine": "Nessun evento in questo periodo.",
  "home.willkommen": "Bentornato",
  "home.naechstesSpiel": "Prossima partita",
  "home.naechstesTraining": "Prossimo allenamento",
  "home.mitmachen": "Partecipa",
  "home.aktionen": "Attività e votazioni",
  "home.tage": "GG",
  "home.std": "ORE",
  "home.min": "MIN",
  "allg.speichern": "Salva",
  "allg.abbrechen": "Annulla",
  "allg.loeschen": "Elimina",
  "allg.bearbeiten": "Modifica",
  "allg.schliessen": "Chiudi",
  "allg.zurueck": "Indietro",
  "allg.weiter": "Avanti",
  "allg.suchen": "Cerca …",
  "allg.keineEintraege": "Ancora nulla.",
  "nav.home": "Home",
  "nav.events": "Calendario",
  "nav.teams": "Squadre",
  "nav.chat": "Chat",
  "nav.profile": "Profilo",
  "nav.fees": "Quote",
  "nav.news": "Redazione",
  "nav.admin": "Amministrazione",
  "nav.sponsors": "Sponsor",
  "sub.season": "Atleta della stagione",
  "sub.tipp": "Pronostici",
  "sub.duty": "Turni volontari",
  "sub.postfach": "Notifiche",
  "sprache.titel": "Scegli la lingua",
  "sprache.hinweis": "In quale lingua vuoi usare l'app? Puoi cambiarla più tardi nel profilo.",
  "sprache.weiter": "Avanti",
  "login.willkommen": "Bentornato",
  "login.email": "Indirizzo e-mail",
  "login.passwort": "Password",
  "login.vergessen": "Password dimenticata?",
  "login.anmelden": "Accedi",
  "login.keinKonto": "Non hai ancora un account?",
  "login.registrieren": "Registrati",
  "reg.titel": "Crea account",
  "reg.vorname": "Nome",
  "reg.nachname": "Cognome",
  "reg.schonMitglied": "Sei già membro?",
  "reg.anmelden": "Accedi",
  "reg.fastGeschafft": "Ci siamo quasi",
  "reg.bestaetigen": "Riceverai un'e-mail. Confermala così possiamo essere certi che i tuoi dati siano corretti.",
  "reg.danach": "Dopodiché potrai accedere.",
  "reg.jetztAnmelden": "Accedi ora",
  "reg.keineMail": "Nessuna e-mail? Controlla la cartella spam — di solito arriva entro un minuto.",
  "profil.sprache": "Lingua",
  "profil.spracheHinweis": "Lingua dell'app",
};

const tr: Woerterbuch = {
  "sys.demoDaten": "Demo verileri",
  "sys.jaZuruecksetzen": "Evet, sıfırla",
  "verein.logo": "Kulüp arması",
  "verein.logoHinweis": "JPG, PNG veya WebP · en fazla 2 MB",
  "verein.farben": "Kulüp renkleri",
  "mit.offeneAntraege": "Bekleyen başvurular",
  "mit.antraegeLaden": "Başvurular yükleniyor …",
  "mit.keineAntraegeKurz": "Başvuru yok",
  "mit.registrierung": "Kayıt",
  "mit.freigeben": "Onayla",
  "allg.listeAktualisieren": "Listeyi yenile",
  "mit.verwalten": "Üyelikleri yönet",
  "mit.laden": "Üyeler yükleniyor …",
  "mit.sperren": "Engelle",
  "mit.keineVorhanden": "Henüz üyelik yok.",
  "mit.sperrliste": "Engellenenler",
  "verein.funktionenFrage": "Kulübünüzün hangi işlevlere ihtiyacı var?",
  "rol.niemand": "Şu anda bu role sahip kimse yok.",
  "sys.profileZusammen": "Hesapsız profilleri birleştir",
  "sys.platzhalter": "Geçici profil (hesapsız) …",
  "allg.nochNichts": "Henüz bir şey yok",
  "sys.nichtBereit": "Uygulama kullanıma hazır değil",
  "store.apple": "App Store'dan indir",
  "store.google": "Google Play'den al",
  "verein.waehlen": "Kulüp seç …",
  "verein.namePlatzhalter": "Kulüp adı, örn. Örnek SK",
  "kal.woechentlich": "Haftalık · pazar akşamı",
  "kal.monatlich": "Aylık",
  "kal.verbinden": "Cihaz takvimine bağla",
  "recht.bedingungen": "Koşullar",
  "konto.loeschenLang": "Hesabı ve kişisel verileri sil",
  "sais.beendet": "Oylama kapandı — sonuç kesin",
  "sais.ehrung": "Sezonun sporcusu — yaz şenliğinde ödül",
  "tipp.jeTeam": "Takım bazlı tahmin oyunu",
  "tipp.niemand": "Bu turda henüz kimse yok.",
  "tipp.wartet": "Sonuç bekleniyor",
  "tipp.ergebnisse": "Sonuçlar ve puanlar",
  "prot.keineAufgaben": "Açık görev yok — harika! 🎉",
  "prot.neu": "Yeni tutanak",
  "prot.teilnehmer": "Katılanlar",
  "prot.speichern": "Tutanağı ve görevleri kaydet",
  "prot.pflicht": "Lütfen başlık ve tutanak metnini gir.",
  "prot.vergangene": "Geçmiş tutanaklar",
  "bei.erinnerungen": "Otomatik ödeme hatırlatmaları",
  "bei.keineOffenen": "Ödenmemiş aidat yok. 🎉",
  "sp.nichtFrei": "Kendi sponsorların henüz açık değil",
  "sp.zuSehen": "Gösterilen:",
  "sp.derSponsor": "Sponsor",
  "sp.dieAktion": "Kampanya (isteğe bağlı)",
  "sp.stehtAufPlatz": "Sponsor bu alanda görünür",
  "sp.entfernen": "Sponsoru bu alandan kaldır",
  "umf.neu": "Yeni kulüp anketi",
  "umf.mindestens": "En az iki yanıt gir.",
  "allg.veroeffentlichen": "Yayınla",
  "tm.mannschaftWaehlen2": "Takım seç …",
  "chat.kanaele": "Sohbet kanalları",
  "sys.konten": "Hesap özeti",
  "straf.titel": "Cezalar",
  "straf.keineAktiven": "Açık ceza yok.",
  "straf.historie": "Ceza geçmişi",
  "auf.titel": "Görevler",
  "auf.keineEingetragen": "Hiçbir göreve kayıtlı değilsin.",
  "fahr.titel": "Araç paylaşımı",
  "fahr.keineKurz": "Araç paylaşımı yok.",
  "mit.keineAnfragen": "Bekleyen katılma isteği yok.",
  "verein.profilBearbeiten": "Kulüp profilini düzenle",
  "status.aktiv": "Aktif",
  "status.ausstehend": "Beklemede",
  "status.inaktiv": "Pasif",
  "status.gesperrt": "Engelli",
  "tm.athletenTeams": "Oynadığım takımlar",
  "feld.telefonnummern": "Telefon numaraları",
  "feld.geburtstagZeigen": "Doğum günümü kulüpte göster",
  "gesch.w": "Kadın",
  "gesch.m": "Erkek",
  "gesch.d": "Non-binary",
  "gesch.k": "Belirtmek istemiyorum",
  "push.aufGeraet": "Bu cihazda bildirimler",
  "sich.autoLogout": "Otomatik çıkış",
  "sich.tage30": "30 gün sonra",
  "sich.tage60": "60 gün sonra",
  "sich.tage90": "90 gün sonra",
  "zug.werben": "Kulüpler kulüp önerir",
  "zug.codeKopieren": "Kodu kopyala",
  "kal.abonnieren": "Takvime abone ol",
  "kal.aktualisierung": "Güncelleme",
  "kal.nie": "Hiçbir zaman otomatik",
  "kal.taeglich": "Günlük",
  "kal.auswahlAufheben": "Seçimi kaldır — takımlarımı kullan",
  "straf.verwaltung": "Cezalar",
  "straf.bisherige": "Önceki cezalar",
  "straf.alle": "Tüm cezalar",
  "straf.historieLaedt": "Geçmiş yükleniyor …",
  "tm.athletWaehlen2": "Oyuncu seç …",
  "allg.aendern": "Değiştir",
  "feld.personen": "Kişi",
  "auf.ganzerVerein": "Tüm kulüp",
  "auf.verantwortlich": "Sorumlu (birden fazla olabilir)",
  "auf.laden": "Görevler yükleniyor …",
  "auf.keine": "Şu anda açık görev yok.",
  "auf.uebernehmeIch": "Ben hallederim",
  "auf.zurueckziehen": "Geri çek",
  "fz.keine": "Henüz araç yok.",
  "fz.kalenderLaedt": "Takvim yükleniyor …",
  "fz.keineBuchungen": "Bu ay rezervasyon yok.",
  "fz.privat": "Özel rezervasyon (takımsız)",
  "tm.mannschaftWaehlen": "Takım seç …",
  "tel.laedt": "Telefon yükleniyor …",
  "tel.keine": "Kayıtlı telefon yok.",
  "helf.satzVorladen": "Şablon yükle …",
  "helf.stationen": "Bu etkinliğin görevleri",
  "helf.alleEntfernen": "Tümünü kaldır",
  "helf.keineSaetze": "Henüz şablon yok.",
  "helf.satzLoeschen": "Şablonu sil",
  "zug.zurueckziehen": "İsteği geri çek",
  "sp.eigene": "Kendi sponsorlarını göster",
  "zug.vollzugang": "Tam erişim iste",
  "zug.keinAbo": "Kendi aboneliğine gerek yok",
  "mit.keine": "Üye bulunamadı.",
  "vid.keine": "Rollerin için henüz video yok.",
  "chat.wiederAnzeigen": "Kişiyi yeniden göstermek için isme dokun.",
  "chat.melden": "Bildir",
  "chat.blockieren": "Engelle",
  "chat.keiner": "Henüz sohbetin yok",
  "chat.ausgeblendet": "Sana gizlendi",
  "news.keineVeroeffentlicht": "Henüz haber yayımlanmadı.",
  "bei.bezahlt": "Ödendi",
  "bei.offen": "Henüz ödenmedi",
  "bei.keineDaten": "Henüz aidat kaydı yok.",
  "bei.anzahlPersonen": "Toplam kişi sayısı",
  "bei.weitereNamen": "Hesabı olmayan diğer isimler",
  "bei.kommaHinweis": "Birden fazla ismi virgülle ayır.",
  "fam.verknuepfung": "Aile bağlantısı",
  "fam.rolle": "Bağlantıdaki rol",
  "fam.verbinden": "Bağla",
  "fam.keinProfil": "Eşleşen profil bulunamadı.",
  "fam.kindAnlegen": "Hesapsız çocuk ekle",
  "tm.kapitaenZuweisen": "Kaptan ata",
  "tm.athletWaehlen": "Oyuncu seç …",
  "tm.keineZuordnung": "Henüz bir takımda değilsin.",
  "tm.neuAnlegen": "Yeni takım oluştur",
  "tm.erwachsene": "Yetişkin takımı mı?",
  "tm.keineZuordnungKurz": "Takım atanmadı.",
  "home.keinSpiel": "Bu takım için planlanmış maç yok.",
  "helf.niemandEingeteilt": "Bu etkinliğe kimse atanmadı.",
  "fahr.keine": "Bu etkinlik için henüz araç paylaşımı yok.",
  "ev.reiheFrage": "Sadece bu tarih mi, tüm seri mi?",
  "home.geburtstag": "Bugün doğum günü:",
  "home.willkommenKomma": "Tekrar hoş geldin,",
  "login.demo": "Denemek için demo girişleri",
  "sys.vorschlag": "Öneri · isim eşleşiyor",
  "login.bleiben": "Oturumu açık tut",
  "reg.alsWas": "Şu olarak kaydoluyorum",
  "reg.akzeptiere": "Kabul ediyorum:",
  "recht.datenschutzerklaerung": "gizlilik politikası",
  "mit.alle": "Tüm üyeler",
  "mit.weitere": "Diğer kulüp üyeleri",
  "umf.tippen": "Oy vermek için dokun",
  "allg.jetztEintragen": "Şimdi kaydol",
  "allg.alleAnsehen": "Tümünü gör",
  "allg.listeLaedt": "Liste yükleniyor …",
  "news.keine": "Henüz haber yok.",
  "helf.niemand": "Henüz kimse yok",
  "helf.jemanden": "Birini görevlendir",
  "helf.gesucht": "Gönüllü aranıyor",
  "fahr.mitfahren": "Araç paylaş",
  "fahr.loeschen": "Yolculuğu sil",
  "fahr.anbieten": "Yer sun",
  "ev.nurDiesen": "Sadece bu tarih",
  "ev.ganzeReihe": "Tüm seriyi sil",
  "ev.wirklichLoeschen": "Bu etkinlik silinsin mi?",
  "bei.art": "Aidat türü",
  "bei.mitglied": "Üyelik aidatı",
  "bei.familie": "Aile aidatı",
  "verein.wechseln": "Kulüp değiştir",
  "verein.deine": "Kulüplerin",
  "verein.beitrittAnfragen": "Katılma isteği gönder",
  "verein.beitrittAls": "Şu olarak katılıyorum",
  "verein.finden": "Kulübünü bul",
  "verein.findenHinweis": "Katılmak istediğin kulübü ara.",
  "verein.laden": "Kulüpler yükleniyor …",
  "verein.ladenFehler": "Kulüp listesi yüklenemedi.",
  "verein.neuAnlegen": "Yeni kulüp kaydet",
  "verein.anlegen": "Kulüp oluştur",
  "verein.zurueckAuswahl": "Kulüp seçimine dön",
  "verein.eigeneFarben": "Kendi renkleri",
  "allg.erneut": "Tekrar dene",
  "allg.entsperren": "Engeli kaldır",
  "allg.gesperrt": "Bu bölümü kulübün açması gerekiyor.",
  "allg.mehr": "Daha fazla",
  "tm.laden": "Takımlar yükleniyor …",
  "tm.keine": "Henüz takım yok.",
  "straf.waehlen": "Ceza seç …",
  "straf.keine": "Henüz ceza yok.",
  "feld.beschreibung": "Açıklama (isteğe bağlı)",
  "feld.nutzerSuchen": "Üye ara",
  "feld.mannschaftFiltern": "Takıma göre filtrele",
  "kal.vorher": "Önceki ay",
  "kal.naechster": "Sonraki ay",
  "sp.zurAktion": "Teklifi gör",
  "sp.website": "Siteye git",
  "konto.loeschenFrage": "Hesap kalıcı olarak silinsin mi?",
  "allg.entfernen": "Kaldır",
  "allg.anlegen": "Oluştur",
  "allg.hinzufuegen": "Ekle",
  "allg.abmelden": "Çıkış yap",
  "allg.laedt": "Yükleniyor …",
  "allg.niemandGefunden": "Kimse bulunamadı.",
  "allg.ablehnen": "Reddet",
  "allg.annehmen": "Kabul et",
  "allg.austragen": "Kaydımı sil",
  "allg.uebernehmen": "Üstleniyorum",
  "allg.eintragenKnopf": "Ekle",
  "feld.vollerName": "Ad ve soyad",
  "feld.rueckennummer": "Forma numarası",
  "feld.stadt": "Şehir",
  "feld.gegner": "Rakip",
  "tm.mannschaften": "Takımlar",
  "recht.impressum": "Künye",
  "recht.datenschutz": "Gizlilik",
  "recht.nutzung": "Kullanım koşulları",
  "tm.meineTeams": "Takımlarım",
  "tm.alleTeams": "Tüm takımlar",
  "tm.kader": "Kadro",
  "tm.meinTeam": "Takımım",
  "tm.mannschaft": "Takım",
  "pf.einstellungen": "Ayarlar",
  "pf.persoenlich": "Kişisel bilgiler",
  "pf.konto": "Hesap ve güvenlik",
  "pf.vereinMitglied": "Kulüp ve üyelik",
  "pf.benachrichtigungen": "Bildirimler ve takvim",
  "pf.zugang": "Erişim ve davetler",
  "pf.support": "Destek ve geri bildirim",
  "pf.einladen": "Arkadaş davet et",
  "pf.kontoLoeschen": "Hesabı sil",
  "pf.vereinVerwalten": "Kulübü yönet",
  "pf.vereinseinstellungen": "Kulüp ayarları",
  "ev.titel": "Takvim",
  "ev.eintragen": "Etkinlik ekle",
  "ev.alle": "Tümü",
  "ev.training": "Antrenman",
  "ev.spiele": "Maçlar",
  "ev.events": "Etkinlikler",
  "ev.alleTeams": "Tüm takımlar",
  "ev.datum": "Tarih",
  "ev.beginn": "Başlangıç",
  "ev.ende": "Bitiş",
  "ev.heimspiel": "İç saha maçı",
  "ev.spiel": "Maç",
  "ev.vereinsevent": "Kulüp etkinliği",
  "ev.wiederholend": "Tekrarlanan",
  "ev.werDabei": "Kimler geliyor?",
  "ev.bistDuDabei": "Geliyor musun?",
  "ev.zugesagt": "Katılıyorum",
  "ev.abgesagt": "Katılmıyorum",
  "ev.absagen": "İptal et",
  "ev.absageGrund": "Neden iptal ediliyor?",
  "ev.jetztAbsagen": "Şimdi iptal et",
  "ev.keineTermine": "Bu dönemde etkinlik yok.",
  "home.willkommen": "Tekrar hoş geldin",
  "home.naechstesSpiel": "Sonraki maç",
  "home.naechstesTraining": "Sonraki antrenman",
  "home.mitmachen": "Katıl",
  "home.aktionen": "Etkinlikler ve oylamalar",
  "home.tage": "GÜN",
  "home.std": "SAAT",
  "home.min": "DK",
  "allg.speichern": "Kaydet",
  "allg.abbrechen": "İptal",
  "allg.loeschen": "Sil",
  "allg.bearbeiten": "Düzenle",
  "allg.schliessen": "Kapat",
  "allg.zurueck": "Geri",
  "allg.weiter": "Devam",
  "allg.suchen": "Ara …",
  "allg.keineEintraege": "Henüz bir şey yok.",
  "nav.home": "Ana sayfa",
  "nav.events": "Takvim",
  "nav.teams": "Takımlar",
  "nav.chat": "Sohbet",
  "nav.profile": "Profil",
  "nav.fees": "Aidatlar",
  "nav.news": "Haberler",
  "nav.admin": "Yönetim",
  "nav.sponsors": "Sponsorlar",
  "sub.season": "Sezonun sporcusu",
  "sub.tipp": "Tahmin oyunu",
  "sub.duty": "Gönüllü görevleri",
  "sub.postfach": "Bildirimler",
  "sprache.titel": "Dilini seç",
  "sprache.hinweis": "Uygulamayı hangi dilde kullanmak istersin? Bunu daha sonra profilinden değiştirebilirsin.",
  "sprache.weiter": "Devam",
  "login.willkommen": "Tekrar hoş geldin",
  "login.email": "E-posta adresi",
  "login.passwort": "Şifre",
  "login.vergessen": "Şifreni mi unuttun?",
  "login.anmelden": "Giriş yap",
  "login.keinKonto": "Hesabın yok mu?",
  "login.registrieren": "Kayıt ol",
  "reg.titel": "Hesap oluştur",
  "reg.vorname": "Ad",
  "reg.nachname": "Soyad",
  "reg.schonMitglied": "Zaten üye misin?",
  "reg.anmelden": "Giriş yap",
  "reg.fastGeschafft": "Neredeyse tamam",
  "reg.bestaetigen": "Bir e-posta alacaksın. Bilgilerinin doğru olduğundan emin olabilmemiz için lütfen onayla.",
  "reg.danach": "Ardından giriş yapabilirsin.",
  "reg.jetztAnmelden": "Şimdi giriş yap",
  "reg.keineMail": "E-posta gelmedi mi? Spam klasörüne bak — genellikle bir dakika içinde gelir.",
  "profil.sprache": "Dil",
  "profil.spracheHinweis": "Uygulama dili",
};

const fr: Woerterbuch = {
  "sys.demoDaten": "Données de démonstration",
  "sys.jaZuruecksetzen": "Oui, réinitialiser",
  "verein.logo": "Écusson du club",
  "verein.logoHinweis": "JPG, PNG ou WebP · 2 Mo max",
  "verein.farben": "Couleurs du club",
  "mit.offeneAntraege": "Demandes en attente",
  "mit.antraegeLaden": "Chargement des demandes …",
  "mit.keineAntraegeKurz": "Aucune demande",
  "mit.registrierung": "Inscription",
  "mit.freigeben": "Approuver",
  "allg.listeAktualisieren": "Actualiser la liste",
  "mit.verwalten": "Gérer les adhésions",
  "mit.laden": "Chargement des membres …",
  "mit.sperren": "Bloquer",
  "mit.keineVorhanden": "Aucune adhésion pour l'instant.",
  "mit.sperrliste": "Liste des bloqués",
  "verein.funktionenFrage": "De quelles fonctions ton club a-t-il besoin ?",
  "rol.niemand": "Personne n'a ce rôle actuellement.",
  "sys.profileZusammen": "Fusionner les profils sans compte",
  "sys.platzhalter": "Profil provisoire (sans compte) …",
  "allg.nochNichts": "Rien pour l'instant",
  "sys.nichtBereit": "L'application n'est pas prête",
  "store.apple": "Télécharger sur l'App Store",
  "store.google": "Disponible sur Google Play",
  "verein.waehlen": "Choisir un club …",
  "verein.namePlatzhalter": "Nom du club, p. ex. FC Exemple",
  "kal.woechentlich": "Hebdomadaire · dimanche soir",
  "kal.monatlich": "Mensuel",
  "kal.verbinden": "Relier à l'agenda du téléphone",
  "recht.bedingungen": "Conditions",
  "konto.loeschenLang": "Supprimer le compte et les données personnelles",
  "sais.beendet": "Vote clos — résultat définitif",
  "sais.ehrung": "Athlète de la saison — remise à la fête d'été",
  "tipp.jeTeam": "Pronostics par équipe",
  "tipp.niemand": "Personne dans cette poule pour l'instant.",
  "tipp.wartet": "En attente du résultat",
  "tipp.ergebnisse": "Résultats et points",
  "prot.keineAufgaben": "Aucune tâche ouverte — parfait ! 🎉",
  "prot.neu": "Nouveau compte rendu",
  "prot.teilnehmer": "Participants",
  "prot.speichern": "Enregistrer le compte rendu et les tâches",
  "prot.pflicht": "Saisis un titre et le texte du compte rendu.",
  "prot.vergangene": "Comptes rendus précédents",
  "bei.erinnerungen": "Rappels de paiement automatiques",
  "bei.keineOffenen": "Aucune cotisation en attente. 🎉",
  "sp.nichtFrei": "Tes sponsors ne sont pas encore activés",
  "sp.zuSehen": "Affiché :",
  "sp.derSponsor": "Le sponsor",
  "sp.dieAktion": "L'offre (facultative)",
  "sp.stehtAufPlatz": "Le sponsor apparaît à cet emplacement",
  "sp.entfernen": "Retirer le sponsor de cet emplacement",
  "umf.neu": "Nouveau sondage du club",
  "umf.mindestens": "Saisis au moins deux réponses.",
  "allg.veroeffentlichen": "Publier",
  "tm.mannschaftWaehlen2": "Choisir une équipe …",
  "chat.kanaele": "Canaux de discussion",
  "sys.konten": "Aperçu des comptes",
  "straf.titel": "Amendes",
  "straf.keineAktiven": "Aucune amende en cours.",
  "straf.historie": "Historique des amendes",
  "auf.titel": "Tâches",
  "auf.keineEingetragen": "Inscrit à aucune tâche.",
  "fahr.titel": "Covoiturages",
  "fahr.keineKurz": "Aucun covoiturage.",
  "mit.keineAnfragen": "Aucune demande en attente.",
  "verein.profilBearbeiten": "Modifier le profil du club",
  "status.aktiv": "Actif",
  "status.ausstehend": "En attente",
  "status.inaktiv": "Inactif",
  "status.gesperrt": "Bloqué",
  "tm.athletenTeams": "Équipes où je joue",
  "feld.telefonnummern": "Numéros de téléphone",
  "feld.geburtstagZeigen": "Afficher mon anniversaire au club",
  "gesch.w": "Femme",
  "gesch.m": "Homme",
  "gesch.d": "Non binaire",
  "gesch.k": "Je préfère ne pas dire",
  "push.aufGeraet": "Notifications sur cet appareil",
  "sich.autoLogout": "Déconnexion automatique",
  "sich.tage30": "Après 30 jours",
  "sich.tage60": "Après 60 jours",
  "sich.tage90": "Après 90 jours",
  "zug.werben": "Les clubs parrainent des clubs",
  "zug.codeKopieren": "Copier le code",
  "kal.abonnieren": "S'abonner à l'agenda",
  "kal.aktualisierung": "Actualisation",
  "kal.nie": "Jamais automatiquement",
  "kal.taeglich": "Chaque jour",
  "kal.auswahlAufheben": "Annuler la sélection — utiliser mes équipes",
  "straf.verwaltung": "Amendes",
  "straf.bisherige": "Amendes précédentes",
  "straf.alle": "Toutes les amendes",
  "straf.historieLaedt": "Chargement de l'historique …",
  "tm.athletWaehlen2": "Choisir un joueur …",
  "allg.aendern": "Modifier",
  "feld.personen": "Personnes",
  "auf.ganzerVerein": "Tout le club",
  "auf.verantwortlich": "Responsable (plusieurs possibles)",
  "auf.laden": "Chargement des tâches …",
  "auf.keine": "Aucune tâche ouverte pour l'instant.",
  "auf.uebernehmeIch": "Je m'en occupe",
  "auf.zurueckziehen": "Retirer",
  "fz.keine": "Aucun véhicule enregistré.",
  "fz.kalenderLaedt": "Chargement de l'agenda …",
  "fz.keineBuchungen": "Aucune réservation ce mois-ci.",
  "fz.privat": "Réservation privée (sans équipe)",
  "tm.mannschaftWaehlen": "Choisir une équipe …",
  "tel.laedt": "Chargement du numéro …",
  "tel.keine": "Aucun numéro enregistré.",
  "helf.satzVorladen": "Charger un modèle …",
  "helf.stationen": "Postes de cet événement",
  "helf.alleEntfernen": "Tout retirer",
  "helf.keineSaetze": "Aucun modèle créé.",
  "helf.satzLoeschen": "Supprimer le modèle",
  "zug.zurueckziehen": "Retirer la demande",
  "sp.eigene": "Afficher tes sponsors",
  "zug.vollzugang": "Demander l'accès complet",
  "zug.keinAbo": "Pas besoin d'abonnement propre",
  "mit.keine": "Aucun membre trouvé.",
  "vid.keine": "Pas encore de vidéos pour tes rôles.",
  "chat.wiederAnzeigen": "Touche un nom pour réafficher la personne.",
  "chat.melden": "Signaler",
  "chat.blockieren": "Bloquer",
  "chat.keiner": "Pas encore de discussion",
  "chat.ausgeblendet": "Masqué pour toi",
  "news.keineVeroeffentlicht": "Aucune actualité publiée.",
  "bei.bezahlt": "Payé",
  "bei.offen": "Pas encore payé",
  "bei.keineDaten": "Aucune cotisation enregistrée.",
  "bei.anzahlPersonen": "Nombre total de personnes",
  "bei.weitereNamen": "Autres noms sans compte",
  "bei.kommaHinweis": "Sépare plusieurs noms par des virgules.",
  "fam.verknuepfung": "Lien familial",
  "fam.rolle": "Rôle dans le lien",
  "fam.verbinden": "Relier",
  "fam.keinProfil": "Aucun profil trouvé.",
  "fam.kindAnlegen": "Ajouter un enfant sans compte",
  "tm.kapitaenZuweisen": "Désigner le capitaine",
  "tm.athletWaehlen": "Choisir un joueur …",
  "tm.keineZuordnung": "Tu n'es dans aucune équipe.",
  "tm.neuAnlegen": "Créer une équipe",
  "tm.erwachsene": "Équipe adulte ?",
  "tm.keineZuordnungKurz": "Aucune équipe attribuée.",
  "home.keinSpiel": "Aucun match prévu pour cette équipe.",
  "helf.niemandEingeteilt": "Personne affecté à cet événement.",
  "fahr.keine": "Pas encore de covoiturage.",
  "ev.reiheFrage": "Cette date ou toute la série ?",
  "home.geburtstag": "Anniversaire aujourd'hui :",
  "home.willkommenKomma": "Bon retour,",
  "login.demo": "Accès de démonstration",
  "sys.vorschlag": "Suggestion · le nom correspond",
  "login.bleiben": "Rester connecté",
  "reg.alsWas": "Je m'inscris en tant que",
  "reg.akzeptiere": "J'accepte la",
  "recht.datenschutzerklaerung": "politique de confidentialité",
  "mit.alle": "Tous les membres",
  "mit.weitere": "Autres membres du club",
  "umf.tippen": "Touche pour voter",
  "allg.jetztEintragen": "M'inscrire",
  "allg.alleAnsehen": "Tout voir",
  "allg.listeLaedt": "Chargement de la liste …",
  "news.keine": "Pas encore d'actualité.",
  "helf.niemand": "Personne inscrit pour l'instant",
  "helf.jemanden": "Affecter quelqu'un",
  "helf.gesucht": "Bénévoles recherchés",
  "fahr.mitfahren": "Chercher une place",
  "fahr.loeschen": "Supprimer le covoiturage",
  "fahr.anbieten": "Proposer une place",
  "ev.nurDiesen": "Cette date uniquement",
  "ev.ganzeReihe": "Supprimer toute la série",
  "ev.wirklichLoeschen": "Supprimer cet événement ?",
  "bei.art": "Type de cotisation",
  "bei.mitglied": "Cotisation membre",
  "bei.familie": "Cotisation famille",
  "verein.wechseln": "Changer de club",
  "verein.deine": "Tes clubs",
  "verein.beitrittAnfragen": "Demander à rejoindre",
  "verein.beitrittAls": "Je rejoins en tant que",
  "verein.finden": "Trouver ton club",
  "verein.findenHinweis": "Cherche le club que tu veux rejoindre.",
  "verein.laden": "Chargement des clubs …",
  "verein.ladenFehler": "La liste des clubs n'a pas pu être chargée.",
  "verein.neuAnlegen": "Enregistrer un nouveau club",
  "verein.anlegen": "Créer le club",
  "verein.zurueckAuswahl": "Retour au choix du club",
  "verein.eigeneFarben": "Couleurs personnalisées",
  "allg.erneut": "Réessayer",
  "allg.entsperren": "Débloquer",
  "allg.gesperrt": "Ton club doit activer cette section.",
  "allg.mehr": "En savoir plus",
  "tm.laden": "Chargement des équipes …",
  "tm.keine": "Pas encore d'équipe.",
  "straf.waehlen": "Choisir une amende …",
  "straf.keine": "Aucune amende pour l'instant.",
  "feld.beschreibung": "Description (facultative)",
  "feld.nutzerSuchen": "Rechercher un membre",
  "feld.mannschaftFiltern": "Filtrer par équipe",
  "kal.vorher": "Mois précédent",
  "kal.naechster": "Mois suivant",
  "sp.zurAktion": "Voir l'offre",
  "sp.website": "Voir le site",
  "konto.loeschenFrage": "Supprimer définitivement le compte ?",
  "allg.entfernen": "Retirer",
  "allg.anlegen": "Créer",
  "allg.hinzufuegen": "Ajouter",
  "allg.abmelden": "Se déconnecter",
  "allg.laedt": "Chargement …",
  "allg.niemandGefunden": "Personne trouvée.",
  "allg.ablehnen": "Refuser",
  "allg.annehmen": "Accepter",
  "allg.austragen": "Me désinscrire",
  "allg.uebernehmen": "Je prends",
  "allg.eintragenKnopf": "Ajouter",
  "feld.vollerName": "Nom et prénom",
  "feld.rueckennummer": "Numéro de maillot",
  "feld.stadt": "Ville",
  "feld.gegner": "Adversaire",
  "tm.mannschaften": "Équipes",
  "recht.impressum": "Mentions légales",
  "recht.datenschutz": "Confidentialité",
  "recht.nutzung": "Conditions d'utilisation",
  "tm.meineTeams": "Mes équipes",
  "tm.alleTeams": "Toutes les équipes",
  "tm.kader": "Effectif",
  "tm.meinTeam": "Mon équipe",
  "tm.mannschaft": "Équipe",
  "pf.einstellungen": "Réglages",
  "pf.persoenlich": "Données personnelles",
  "pf.konto": "Compte et sécurité",
  "pf.vereinMitglied": "Club et adhésion",
  "pf.benachrichtigungen": "Notifications et agenda",
  "pf.zugang": "Accès et parrainage",
  "pf.support": "Assistance et retours",
  "pf.einladen": "Inviter des amis",
  "pf.kontoLoeschen": "Supprimer le compte",
  "pf.vereinVerwalten": "Gérer le club",
  "pf.vereinseinstellungen": "Réglages du club",
  "ev.titel": "Agenda",
  "ev.eintragen": "Ajouter un événement",
  "ev.alle": "Tous",
  "ev.training": "Entraînement",
  "ev.spiele": "Matchs",
  "ev.events": "Événements",
  "ev.alleTeams": "Toutes les équipes",
  "ev.datum": "Date",
  "ev.beginn": "Début",
  "ev.ende": "Fin",
  "ev.heimspiel": "Match à domicile",
  "ev.spiel": "Match",
  "ev.vereinsevent": "Événement du club",
  "ev.wiederholend": "Récurrent",
  "ev.werDabei": "Qui vient ?",
  "ev.bistDuDabei": "Tu viens ?",
  "ev.zugesagt": "Présent",
  "ev.abgesagt": "Absent",
  "ev.absagen": "Annuler",
  "ev.absageGrund": "Pourquoi cette annulation ?",
  "ev.jetztAbsagen": "Annuler maintenant",
  "ev.keineTermine": "Aucun événement sur cette période.",
  "home.willkommen": "Bon retour",
  "home.naechstesSpiel": "Prochain match",
  "home.naechstesTraining": "Prochain entraînement",
  "home.mitmachen": "Participer",
  "home.aktionen": "Activités et votes",
  "home.tage": "JOURS",
  "home.std": "H",
  "home.min": "MIN",
  "allg.speichern": "Enregistrer",
  "allg.abbrechen": "Annuler",
  "allg.loeschen": "Supprimer",
  "allg.bearbeiten": "Modifier",
  "allg.schliessen": "Fermer",
  "allg.zurueck": "Retour",
  "allg.weiter": "Continuer",
  "allg.suchen": "Rechercher …",
  "allg.keineEintraege": "Rien pour l'instant.",
  "nav.home": "Accueil",
  "nav.events": "Agenda",
  "nav.teams": "Équipes",
  "nav.chat": "Chat",
  "nav.profile": "Profil",
  "nav.fees": "Cotisations",
  "nav.news": "Rédaction",
  "nav.admin": "Administration",
  "nav.sponsors": "Sponsors",
  "sub.season": "Athlète de la saison",
  "sub.tipp": "Pronostics",
  "sub.duty": "Bénévoles",
  "sub.postfach": "Notifications",
  "sprache.titel": "Choisis ta langue",
  "sprache.hinweis": "Dans quelle langue veux-tu utiliser l'application ? Tu pourras la changer plus tard dans ton profil.",
  "sprache.weiter": "Continuer",
  "login.willkommen": "Bon retour",
  "login.email": "Adresse e-mail",
  "login.passwort": "Mot de passe",
  "login.vergessen": "Mot de passe oublié ?",
  "login.anmelden": "Se connecter",
  "login.keinKonto": "Pas encore de compte ?",
  "login.registrieren": "S'inscrire",
  "reg.titel": "Créer un compte",
  "reg.vorname": "Prénom",
  "reg.nachname": "Nom",
  "reg.schonMitglied": "Déjà membre ?",
  "reg.anmelden": "Se connecter",
  "reg.fastGeschafft": "Presque terminé",
  "reg.bestaetigen": "Tu vas recevoir un e-mail. Merci de le confirmer pour que nous soyons sûrs que tes données sont correctes.",
  "reg.danach": "Ensuite, tu pourras te connecter.",
  "reg.jetztAnmelden": "Se connecter",
  "reg.keineMail": "Pas d'e-mail ? Regarde dans les indésirables — il arrive généralement en une minute.",
  "profil.sprache": "Langue",
  "profil.spracheHinweis": "Langue de l'application",
};

const WOERTERBUECHER: Record<string, Woerterbuch> = { de, en, es, pt, it, tr, fr };

export const SPRACHE_SPEICHER = "cmo.sprache";

/* Die gewaehlte Sprache aus dem Geraet lesen.
   Sie steht dort UND am Konto: Im Geraet, weil die Wahl vor der Anmeldung
   getroffen wird und es dann noch kein Konto gibt; am Konto, damit sie auf
   einem zweiten Geraet nicht erneut abgefragt wird. */
export function gespeicherteSprache(): Sprachcode | null {
  if (typeof window === "undefined") return null;
  try {
    const wert = window.localStorage.getItem(SPRACHE_SPEICHER);
    return SPRACHEN.some((s) => s.code === wert) ? (wert as Sprachcode) : null;
  } catch {
    /* Privater Modus, gesperrte Website-Daten: Dann wird eben jedes Mal
       gefragt - besser als ein Absturz beim Start. */
    return null;
  }
}

export function spracheMerken(code: string) {
  if (typeof window === "undefined") return;
  try { window.localStorage.setItem(SPRACHE_SPEICHER, code); } catch { /* siehe oben */ }
}

/* Uebersetzen. Fehlt ein Schluessel, kommt der deutsche Text - nicht der
   Schluessel. Ein deutscher Satz ist unschoen, "profil.titel" ist unbrauchbar. */
export function uebersetze(code: string, schluessel: string): string {
  return WOERTERBUECHER[code]?.[schluessel] ?? de[schluessel] ?? schluessel;
}
