/* Sprachen der App.
 *
 * WARUM EINE EIGENE DATEI
 * page.tsx hat rund 11.000 Zeilen. Die Texte dort hineinzuschreiben haette sie
 * um Tausende weitere verlaengert - und beim Uebersetzen muesste man jedes Mal
 * durch die ganze App scrollen. Hier stehen sie beieinander und lassen sich
 * Sprache fuer Sprache vervollstaendigen.
 *
 * WIE DIE UEBERSETZUNG FEHLSCHLAEGT
 * Fehlt ein Schluessel in einer Sprache, faellt t() auf Deutsch zurueck - nicht
 * auf den Schluessel selbst. Ein Nutzer sieht dann einen deutschen Satz, was
 * unschoen ist; er saehe sonst "profil.titel", was unbrauchbar ist.
 *
 * STAND
 * Uebersetzt sind die Bildschirme, die ein neuer Nutzer zuerst sieht:
 * Sprachwahl, Anmeldung, Registrierung. Der Rest der App bleibt vorerst
 * deutsch - die Umstellung erfolgt in Schritten, damit nicht die halbe App
 * zwischen zwei Sprachen steht.
 */

export const SPRACHEN = [
  { code: "de", name: "Deutsch",    flagge: "🇩🇪" },
  { code: "en", name: "English",    flagge: "🇬🇧" },
  { code: "es", name: "Español",    flagge: "🇪🇸" },
  { code: "pt", name: "Português",  flagge: "🇵🇹" },
  { code: "it", name: "Italiano",   flagge: "🇮🇹" },
  { code: "tr", name: "Türkçe",     flagge: "🇹🇷" },
  { code: "fr", name: "Français",   flagge: "🇫🇷" },
] as const;

export type Sprachcode = (typeof SPRACHEN)[number]["code"];

type Woerterbuch = Record<string, string>;

const de: Woerterbuch = {
  "allg.entfernen": "Entfernen",
  "allg.anlegen": "Anlegen",
  "allg.hinzufuegen": "Hinzufügen",
  "allg.abmelden": "Abmelden",
  "allg.laedt": "Wird geladen …",
  "allg.niemandGefunden": "Niemand gefunden.",
  "allg.ablehnen": "Ablehnen",
  "allg.annehmen": "Annehmen",
  "allg.austragen": "Austragen",
  "allg.uebernehmen": "Übernehmen",
  "allg.eintragenKnopf": "Eintragen",
  "feld.vollerName": "Vor- und Nachname",
  "feld.rueckennummer": "Rückennummer",
  "feld.stadt": "Stadt",
  "feld.gegner": "Gegner",
  "tm.mannschaften": "Mannschaften",
  "recht.impressum": "Impressum",
  "recht.datenschutz": "Datenschutz",
  "recht.nutzung": "Nutzungsbedingungen",
  "tm.meineTeams": "Meine Teams",
  "tm.alleTeams": "Alle Mannschaften",
  "tm.kader": "Athlet/innen",
  "tm.meinTeam": "Mein Team",
  "tm.mannschaft": "Mannschaft",
  "pf.einstellungen": "Einstellungen",
  "pf.persoenlich": "Persönliche Daten",
  "pf.konto": "Konto & Sicherheit",
  "pf.vereinMitglied": "Verein & Mitgliedschaft",
  "pf.benachrichtigungen": "Benachrichtigungen & Kalender",
  "pf.zugang": "Zugang & Empfehlungen",
  "pf.support": "Support & Feedback",
  "pf.einladen": "Freunde einladen",
  "pf.kontoLoeschen": "Konto löschen",
  "pf.vereinVerwalten": "Verein verwalten",
  "pf.vereinseinstellungen": "Vereinseinstellungen",
  "ev.titel": "Termine",
  "ev.eintragen": "Termin eintragen",
  "ev.alle": "Alle",
  "ev.training": "Training",
  "ev.spiele": "Spiele",
  "ev.events": "Events",
  "ev.alleTeams": "Alle Mannschaften",
  "ev.datum": "Datum",
  "ev.beginn": "Beginn",
  "ev.ende": "Ende",
  "ev.heimspiel": "Heimspiel",
  "ev.spiel": "Spiel",
  "ev.vereinsevent": "Vereins-Event",
  "ev.wiederholend": "Wiederholend",
  "ev.werDabei": "Wer ist dabei?",
  "ev.bistDuDabei": "Bist du dabei?",
  "ev.zugesagt": "Zugesagt",
  "ev.abgesagt": "Abgesagt",
  "ev.absagen": "Absagen",
  "ev.absageGrund": "Warum wird abgesagt?",
  "ev.jetztAbsagen": "Jetzt absagen",
  "ev.keineTermine": "Keine Termine in diesem Zeitraum.",
  "home.willkommen": "Willkommen zurück",
  "home.naechstesSpiel": "Nächstes Spiel",
  "home.naechstesTraining": "Nächstes Training",
  "home.mitmachen": "Mitmachen",
  "home.aktionen": "Aktionen & Abstimmungen",
  "home.tage": "TAGE",
  "home.std": "STD",
  "home.min": "MIN",
  "allg.speichern": "Speichern",
  "allg.abbrechen": "Abbrechen",
  "allg.loeschen": "Löschen",
  "allg.bearbeiten": "Bearbeiten",
  "allg.schliessen": "Schließen",
  "allg.zurueck": "Zurück",
  "allg.weiter": "Weiter",
  "allg.suchen": "Suchen …",
  "allg.keineEintraege": "Noch keine Einträge.",
  "nav.home": "Home",
  "nav.events": "Termine",
  "nav.teams": "Teams",
  "nav.chat": "Chat",
  "nav.profile": "Profil",
  "nav.fees": "Beiträge",
  "nav.news": "Redaktion",
  "nav.admin": "Verwaltung",
  "nav.sponsors": "Sponsoren",
  "sub.season": "Athlet/in der Saison",
  "sub.tipp": "Tippspiel",
  "sub.duty": "Helferplanung",
  "sub.postfach": "Benachrichtigungen",
  "sprache.titel": "Sprache wählen",
  "sprache.hinweis": "In welcher Sprache möchtest du die App nutzen? Du kannst das später im Profil ändern.",
  "sprache.weiter": "Weiter",

  "login.willkommen": "Willkommen zurück",
  "login.email": "E-Mail-Adresse",
  "login.passwort": "Passwort",
  "login.vergessen": "Passwort vergessen?",
  "login.anmelden": "Anmelden",
  "login.keinKonto": "Noch kein Konto?",
  "login.registrieren": "Jetzt registrieren",

  "reg.titel": "Konto erstellen",
  "reg.vorname": "Vorname",
  "reg.nachname": "Nachname",
  "reg.schonMitglied": "Schon Mitglied?",
  "reg.anmelden": "Anmelden",
  "reg.fastGeschafft": "Fast geschafft",
  "reg.bestaetigen": "Du erhältst eine E-Mail. Bitte bestätige sie, damit wir sicher gehen können, dass deine Daten korrekt sind.",
  "reg.danach": "Anschließend kannst du dich anmelden.",
  "reg.jetztAnmelden": "Jetzt anmelden",
  "reg.keineMail": "Keine E-Mail erhalten? Sieh im Spam-Ordner nach — sie kommt meist innerhalb einer Minute.",

  "profil.sprache": "Sprache",
  "profil.spracheHinweis": "Sprache der App",
};

const en: Woerterbuch = {
  "allg.entfernen": "Remove",
  "allg.anlegen": "Create",
  "allg.hinzufuegen": "Add",
  "allg.abmelden": "Sign out",
  "allg.laedt": "Loading …",
  "allg.niemandGefunden": "Nobody found.",
  "allg.ablehnen": "Decline",
  "allg.annehmen": "Accept",
  "allg.austragen": "Sign off",
  "allg.uebernehmen": "Take it",
  "allg.eintragenKnopf": "Add",
  "feld.vollerName": "First and last name",
  "feld.rueckennummer": "Shirt number",
  "feld.stadt": "Town",
  "feld.gegner": "Opponent",
  "tm.mannschaften": "Teams",
  "recht.impressum": "Legal notice",
  "recht.datenschutz": "Privacy",
  "recht.nutzung": "Terms of use",
  "tm.meineTeams": "My teams",
  "tm.alleTeams": "All teams",
  "tm.kader": "Squad",
  "tm.meinTeam": "My team",
  "tm.mannschaft": "Team",
  "pf.einstellungen": "Settings",
  "pf.persoenlich": "Personal details",
  "pf.konto": "Account & security",
  "pf.vereinMitglied": "Club & membership",
  "pf.benachrichtigungen": "Notifications & calendar",
  "pf.zugang": "Access & referrals",
  "pf.support": "Support & feedback",
  "pf.einladen": "Invite friends",
  "pf.kontoLoeschen": "Delete account",
  "pf.vereinVerwalten": "Manage club",
  "pf.vereinseinstellungen": "Club settings",
  "ev.titel": "Schedule",
  "ev.eintragen": "Add event",
  "ev.alle": "All",
  "ev.training": "Training",
  "ev.spiele": "Matches",
  "ev.events": "Events",
  "ev.alleTeams": "All teams",
  "ev.datum": "Date",
  "ev.beginn": "Start",
  "ev.ende": "End",
  "ev.heimspiel": "Home match",
  "ev.spiel": "Match",
  "ev.vereinsevent": "Club event",
  "ev.wiederholend": "Recurring",
  "ev.werDabei": "Who's coming?",
  "ev.bistDuDabei": "Are you coming?",
  "ev.zugesagt": "Attending",
  "ev.abgesagt": "Not attending",
  "ev.absagen": "Cancel event",
  "ev.absageGrund": "Why is it cancelled?",
  "ev.jetztAbsagen": "Cancel now",
  "ev.keineTermine": "No events in this period.",
  "home.willkommen": "Welcome back",
  "home.naechstesSpiel": "Next match",
  "home.naechstesTraining": "Next training",
  "home.mitmachen": "Get involved",
  "home.aktionen": "Activities & votes",
  "home.tage": "DAYS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Save",
  "allg.abbrechen": "Cancel",
  "allg.loeschen": "Delete",
  "allg.bearbeiten": "Edit",
  "allg.schliessen": "Close",
  "allg.zurueck": "Back",
  "allg.weiter": "Continue",
  "allg.suchen": "Search …",
  "allg.keineEintraege": "Nothing here yet.",
  "nav.home": "Home",
  "nav.events": "Schedule",
  "nav.teams": "Teams",
  "nav.chat": "Chat",
  "nav.profile": "Profile",
  "nav.fees": "Fees",
  "nav.news": "News desk",
  "nav.admin": "Admin",
  "nav.sponsors": "Sponsors",
  "sub.season": "Athlete of the season",
  "sub.tipp": "Prediction game",
  "sub.duty": "Volunteer roster",
  "sub.postfach": "Notifications",
  "sprache.titel": "Choose your language",
  "sprache.hinweis": "Which language would you like to use? You can change this later in your profile.",
  "sprache.weiter": "Continue",
  "login.willkommen": "Welcome back",
  "login.email": "Email address",
  "login.passwort": "Password",
  "login.vergessen": "Forgot your password?",
  "login.anmelden": "Sign in",
  "login.keinKonto": "No account yet?",
  "login.registrieren": "Sign up",
  "reg.titel": "Create account",
  "reg.vorname": "First name",
  "reg.nachname": "Last name",
  "reg.schonMitglied": "Already a member?",
  "reg.anmelden": "Sign in",
  "reg.fastGeschafft": "Almost done",
  "reg.bestaetigen": "You will receive an email. Please confirm it so we can be sure your details are correct.",
  "reg.danach": "After that you can sign in.",
  "reg.jetztAnmelden": "Sign in now",
  "reg.keineMail": "No email? Check your spam folder — it usually arrives within a minute.",
  "profil.sprache": "Language",
  "profil.spracheHinweis": "App language",
};

const es: Woerterbuch = {
  "allg.entfernen": "Quitar",
  "allg.anlegen": "Crear",
  "allg.hinzufuegen": "Añadir",
  "allg.abmelden": "Cerrar sesión",
  "allg.laedt": "Cargando …",
  "allg.niemandGefunden": "Nadie encontrado.",
  "allg.ablehnen": "Rechazar",
  "allg.annehmen": "Aceptar",
  "allg.austragen": "Darse de baja",
  "allg.uebernehmen": "Asumir",
  "allg.eintragenKnopf": "Añadir",
  "feld.vollerName": "Nombre y apellidos",
  "feld.rueckennummer": "Dorsal",
  "feld.stadt": "Ciudad",
  "feld.gegner": "Rival",
  "tm.mannschaften": "Equipos",
  "recht.impressum": "Aviso legal",
  "recht.datenschutz": "Privacidad",
  "recht.nutzung": "Condiciones de uso",
  "tm.meineTeams": "Mis equipos",
  "tm.alleTeams": "Todos los equipos",
  "tm.kader": "Plantilla",
  "tm.meinTeam": "Mi equipo",
  "tm.mannschaft": "Equipo",
  "pf.einstellungen": "Ajustes",
  "pf.persoenlich": "Datos personales",
  "pf.konto": "Cuenta y seguridad",
  "pf.vereinMitglied": "Club y membresía",
  "pf.benachrichtigungen": "Notificaciones y calendario",
  "pf.zugang": "Acceso y recomendaciones",
  "pf.support": "Soporte y sugerencias",
  "pf.einladen": "Invitar amigos",
  "pf.kontoLoeschen": "Eliminar cuenta",
  "pf.vereinVerwalten": "Gestionar club",
  "pf.vereinseinstellungen": "Ajustes del club",
  "ev.titel": "Agenda",
  "ev.eintragen": "Añadir evento",
  "ev.alle": "Todos",
  "ev.training": "Entrenamiento",
  "ev.spiele": "Partidos",
  "ev.events": "Eventos",
  "ev.alleTeams": "Todos los equipos",
  "ev.datum": "Fecha",
  "ev.beginn": "Inicio",
  "ev.ende": "Fin",
  "ev.heimspiel": "Partido en casa",
  "ev.spiel": "Partido",
  "ev.vereinsevent": "Evento del club",
  "ev.wiederholend": "Periódico",
  "ev.werDabei": "¿Quién viene?",
  "ev.bistDuDabei": "¿Vienes?",
  "ev.zugesagt": "Asisto",
  "ev.abgesagt": "No asisto",
  "ev.absagen": "Cancelar",
  "ev.absageGrund": "¿Por qué se cancela?",
  "ev.jetztAbsagen": "Cancelar ahora",
  "ev.keineTermine": "No hay eventos en este periodo.",
  "home.willkommen": "Bienvenido de nuevo",
  "home.naechstesSpiel": "Próximo partido",
  "home.naechstesTraining": "Próximo entrenamiento",
  "home.mitmachen": "Participa",
  "home.aktionen": "Actividades y votaciones",
  "home.tage": "DÍAS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Guardar",
  "allg.abbrechen": "Cancelar",
  "allg.loeschen": "Eliminar",
  "allg.bearbeiten": "Editar",
  "allg.schliessen": "Cerrar",
  "allg.zurueck": "Atrás",
  "allg.weiter": "Continuar",
  "allg.suchen": "Buscar …",
  "allg.keineEintraege": "Todavía no hay nada.",
  "nav.home": "Inicio",
  "nav.events": "Agenda",
  "nav.teams": "Equipos",
  "nav.chat": "Chat",
  "nav.profile": "Perfil",
  "nav.fees": "Cuotas",
  "nav.news": "Redacción",
  "nav.admin": "Administración",
  "nav.sponsors": "Patrocinadores",
  "sub.season": "Atleta de la temporada",
  "sub.tipp": "Quiniela",
  "sub.duty": "Turnos de voluntarios",
  "sub.postfach": "Notificaciones",
  "sprache.titel": "Elige tu idioma",
  "sprache.hinweis": "¿En qué idioma quieres usar la aplicación? Puedes cambiarlo más tarde en tu perfil.",
  "sprache.weiter": "Continuar",
  "login.willkommen": "Bienvenido de nuevo",
  "login.email": "Correo electrónico",
  "login.passwort": "Contraseña",
  "login.vergessen": "¿Olvidaste tu contraseña?",
  "login.anmelden": "Iniciar sesión",
  "login.keinKonto": "¿Aún no tienes cuenta?",
  "login.registrieren": "Regístrate",
  "reg.titel": "Crear cuenta",
  "reg.vorname": "Nombre",
  "reg.nachname": "Apellido",
  "reg.schonMitglied": "¿Ya eres miembro?",
  "reg.anmelden": "Iniciar sesión",
  "reg.fastGeschafft": "Casi listo",
  "reg.bestaetigen": "Recibirás un correo electrónico. Confírmalo para que podamos asegurarnos de que tus datos son correctos.",
  "reg.danach": "Después podrás iniciar sesión.",
  "reg.jetztAnmelden": "Iniciar sesión",
  "reg.keineMail": "¿No recibiste el correo? Revisa la carpeta de spam — suele llegar en un minuto.",
  "profil.sprache": "Idioma",
  "profil.spracheHinweis": "Idioma de la aplicación",
};

const pt: Woerterbuch = {
  "allg.entfernen": "Remover",
  "allg.anlegen": "Criar",
  "allg.hinzufuegen": "Adicionar",
  "allg.abmelden": "Terminar sessão",
  "allg.laedt": "A carregar …",
  "allg.niemandGefunden": "Ninguém encontrado.",
  "allg.ablehnen": "Recusar",
  "allg.annehmen": "Aceitar",
  "allg.austragen": "Retirar-me",
  "allg.uebernehmen": "Assumir",
  "allg.eintragenKnopf": "Adicionar",
  "feld.vollerName": "Nome completo",
  "feld.rueckennummer": "Número",
  "feld.stadt": "Cidade",
  "feld.gegner": "Adversário",
  "tm.mannschaften": "Equipas",
  "recht.impressum": "Ficha técnica",
  "recht.datenschutz": "Privacidade",
  "recht.nutzung": "Termos de utilização",
  "tm.meineTeams": "As minhas equipas",
  "tm.alleTeams": "Todas as equipas",
  "tm.kader": "Plantel",
  "tm.meinTeam": "A minha equipa",
  "tm.mannschaft": "Equipa",
  "pf.einstellungen": "Definições",
  "pf.persoenlich": "Dados pessoais",
  "pf.konto": "Conta e segurança",
  "pf.vereinMitglied": "Clube e filiação",
  "pf.benachrichtigungen": "Notificações e calendário",
  "pf.zugang": "Acesso e recomendações",
  "pf.support": "Apoio e sugestões",
  "pf.einladen": "Convidar amigos",
  "pf.kontoLoeschen": "Eliminar conta",
  "pf.vereinVerwalten": "Gerir clube",
  "pf.vereinseinstellungen": "Definições do clube",
  "ev.titel": "Agenda",
  "ev.eintragen": "Adicionar evento",
  "ev.alle": "Todos",
  "ev.training": "Treino",
  "ev.spiele": "Jogos",
  "ev.events": "Eventos",
  "ev.alleTeams": "Todas as equipas",
  "ev.datum": "Data",
  "ev.beginn": "Início",
  "ev.ende": "Fim",
  "ev.heimspiel": "Jogo em casa",
  "ev.spiel": "Jogo",
  "ev.vereinsevent": "Evento do clube",
  "ev.wiederholend": "Recorrente",
  "ev.werDabei": "Quem vem?",
  "ev.bistDuDabei": "Vens?",
  "ev.zugesagt": "Vou",
  "ev.abgesagt": "Não vou",
  "ev.absagen": "Cancelar",
  "ev.absageGrund": "Porquê o cancelamento?",
  "ev.jetztAbsagen": "Cancelar agora",
  "ev.keineTermine": "Não há eventos neste período.",
  "home.willkommen": "Bem-vindo de volta",
  "home.naechstesSpiel": "Próximo jogo",
  "home.naechstesTraining": "Próximo treino",
  "home.mitmachen": "Participa",
  "home.aktionen": "Atividades e votações",
  "home.tage": "DIAS",
  "home.std": "HRS",
  "home.min": "MIN",
  "allg.speichern": "Guardar",
  "allg.abbrechen": "Cancelar",
  "allg.loeschen": "Eliminar",
  "allg.bearbeiten": "Editar",
  "allg.schliessen": "Fechar",
  "allg.zurueck": "Voltar",
  "allg.weiter": "Continuar",
  "allg.suchen": "Procurar …",
  "allg.keineEintraege": "Ainda não há nada.",
  "nav.home": "Início",
  "nav.events": "Agenda",
  "nav.teams": "Equipas",
  "nav.chat": "Chat",
  "nav.profile": "Perfil",
  "nav.fees": "Quotas",
  "nav.news": "Redação",
  "nav.admin": "Administração",
  "nav.sponsors": "Patrocinadores",
  "sub.season": "Atleta da época",
  "sub.tipp": "Bolão",
  "sub.duty": "Escala de voluntários",
  "sub.postfach": "Notificações",
  "sprache.titel": "Escolhe o teu idioma",
  "sprache.hinweis": "Em que idioma queres usar a aplicação? Podes alterar mais tarde no teu perfil.",
  "sprache.weiter": "Continuar",
  "login.willkommen": "Bem-vindo de volta",
  "login.email": "Endereço de e-mail",
  "login.passwort": "Palavra-passe",
  "login.vergessen": "Esqueceste a palavra-passe?",
  "login.anmelden": "Entrar",
  "login.keinKonto": "Ainda não tens conta?",
  "login.registrieren": "Registar",
  "reg.titel": "Criar conta",
  "reg.vorname": "Nome próprio",
  "reg.nachname": "Apelido",
  "reg.schonMitglied": "Já és membro?",
  "reg.anmelden": "Entrar",
  "reg.fastGeschafft": "Quase pronto",
  "reg.bestaetigen": "Vais receber um e-mail. Confirma-o para termos a certeza de que os teus dados estão corretos.",
  "reg.danach": "Depois disso podes entrar.",
  "reg.jetztAnmelden": "Entrar agora",
  "reg.keineMail": "Não recebeste o e-mail? Vê a pasta de spam — costuma chegar num minuto.",
  "profil.sprache": "Idioma",
  "profil.spracheHinweis": "Idioma da aplicação",
};

const it: Woerterbuch = {
  "allg.entfernen": "Rimuovi",
  "allg.anlegen": "Crea",
  "allg.hinzufuegen": "Aggiungi",
  "allg.abmelden": "Esci",
  "allg.laedt": "Caricamento …",
  "allg.niemandGefunden": "Nessuno trovato.",
  "allg.ablehnen": "Rifiuta",
  "allg.annehmen": "Accetta",
  "allg.austragen": "Cancellati",
  "allg.uebernehmen": "Prendo io",
  "allg.eintragenKnopf": "Aggiungi",
  "feld.vollerName": "Nome e cognome",
  "feld.rueckennummer": "Numero di maglia",
  "feld.stadt": "Città",
  "feld.gegner": "Avversario",
  "tm.mannschaften": "Squadre",
  "recht.impressum": "Note legali",
  "recht.datenschutz": "Privacy",
  "recht.nutzung": "Condizioni d'uso",
  "tm.meineTeams": "Le mie squadre",
  "tm.alleTeams": "Tutte le squadre",
  "tm.kader": "Rosa",
  "tm.meinTeam": "La mia squadra",
  "tm.mannschaft": "Squadra",
  "pf.einstellungen": "Impostazioni",
  "pf.persoenlich": "Dati personali",
  "pf.konto": "Account e sicurezza",
  "pf.vereinMitglied": "Club e tesseramento",
  "pf.benachrichtigungen": "Notifiche e calendario",
  "pf.zugang": "Accesso e inviti",
  "pf.support": "Assistenza e feedback",
  "pf.einladen": "Invita amici",
  "pf.kontoLoeschen": "Elimina account",
  "pf.vereinVerwalten": "Gestisci club",
  "pf.vereinseinstellungen": "Impostazioni club",
  "ev.titel": "Calendario",
  "ev.eintragen": "Aggiungi evento",
  "ev.alle": "Tutti",
  "ev.training": "Allenamento",
  "ev.spiele": "Partite",
  "ev.events": "Eventi",
  "ev.alleTeams": "Tutte le squadre",
  "ev.datum": "Data",
  "ev.beginn": "Inizio",
  "ev.ende": "Fine",
  "ev.heimspiel": "Partita in casa",
  "ev.spiel": "Partita",
  "ev.vereinsevent": "Evento del club",
  "ev.wiederholend": "Ricorrente",
  "ev.werDabei": "Chi viene?",
  "ev.bistDuDabei": "Ci sei?",
  "ev.zugesagt": "Presente",
  "ev.abgesagt": "Assente",
  "ev.absagen": "Annulla",
  "ev.absageGrund": "Perché viene annullato?",
  "ev.jetztAbsagen": "Annulla ora",
  "ev.keineTermine": "Nessun evento in questo periodo.",
  "home.willkommen": "Bentornato",
  "home.naechstesSpiel": "Prossima partita",
  "home.naechstesTraining": "Prossimo allenamento",
  "home.mitmachen": "Partecipa",
  "home.aktionen": "Attività e votazioni",
  "home.tage": "GG",
  "home.std": "ORE",
  "home.min": "MIN",
  "allg.speichern": "Salva",
  "allg.abbrechen": "Annulla",
  "allg.loeschen": "Elimina",
  "allg.bearbeiten": "Modifica",
  "allg.schliessen": "Chiudi",
  "allg.zurueck": "Indietro",
  "allg.weiter": "Avanti",
  "allg.suchen": "Cerca …",
  "allg.keineEintraege": "Ancora nulla.",
  "nav.home": "Home",
  "nav.events": "Calendario",
  "nav.teams": "Squadre",
  "nav.chat": "Chat",
  "nav.profile": "Profilo",
  "nav.fees": "Quote",
  "nav.news": "Redazione",
  "nav.admin": "Amministrazione",
  "nav.sponsors": "Sponsor",
  "sub.season": "Atleta della stagione",
  "sub.tipp": "Pronostici",
  "sub.duty": "Turni volontari",
  "sub.postfach": "Notifiche",
  "sprache.titel": "Scegli la lingua",
  "sprache.hinweis": "In quale lingua vuoi usare l'app? Puoi cambiarla più tardi nel profilo.",
  "sprache.weiter": "Avanti",
  "login.willkommen": "Bentornato",
  "login.email": "Indirizzo e-mail",
  "login.passwort": "Password",
  "login.vergessen": "Password dimenticata?",
  "login.anmelden": "Accedi",
  "login.keinKonto": "Non hai ancora un account?",
  "login.registrieren": "Registrati",
  "reg.titel": "Crea account",
  "reg.vorname": "Nome",
  "reg.nachname": "Cognome",
  "reg.schonMitglied": "Sei già membro?",
  "reg.anmelden": "Accedi",
  "reg.fastGeschafft": "Ci siamo quasi",
  "reg.bestaetigen": "Riceverai un'e-mail. Confermala così possiamo essere certi che i tuoi dati siano corretti.",
  "reg.danach": "Dopodiché potrai accedere.",
  "reg.jetztAnmelden": "Accedi ora",
  "reg.keineMail": "Nessuna e-mail? Controlla la cartella spam — di solito arriva entro un minuto.",
  "profil.sprache": "Lingua",
  "profil.spracheHinweis": "Lingua dell'app",
};

const tr: Woerterbuch = {
  "allg.entfernen": "Kaldır",
  "allg.anlegen": "Oluştur",
  "allg.hinzufuegen": "Ekle",
  "allg.abmelden": "Çıkış yap",
  "allg.laedt": "Yükleniyor …",
  "allg.niemandGefunden": "Kimse bulunamadı.",
  "allg.ablehnen": "Reddet",
  "allg.annehmen": "Kabul et",
  "allg.austragen": "Kaydımı sil",
  "allg.uebernehmen": "Üstleniyorum",
  "allg.eintragenKnopf": "Ekle",
  "feld.vollerName": "Ad ve soyad",
  "feld.rueckennummer": "Forma numarası",
  "feld.stadt": "Şehir",
  "feld.gegner": "Rakip",
  "tm.mannschaften": "Takımlar",
  "recht.impressum": "Künye",
  "recht.datenschutz": "Gizlilik",
  "recht.nutzung": "Kullanım koşulları",
  "tm.meineTeams": "Takımlarım",
  "tm.alleTeams": "Tüm takımlar",
  "tm.kader": "Kadro",
  "tm.meinTeam": "Takımım",
  "tm.mannschaft": "Takım",
  "pf.einstellungen": "Ayarlar",
  "pf.persoenlich": "Kişisel bilgiler",
  "pf.konto": "Hesap ve güvenlik",
  "pf.vereinMitglied": "Kulüp ve üyelik",
  "pf.benachrichtigungen": "Bildirimler ve takvim",
  "pf.zugang": "Erişim ve davetler",
  "pf.support": "Destek ve geri bildirim",
  "pf.einladen": "Arkadaş davet et",
  "pf.kontoLoeschen": "Hesabı sil",
  "pf.vereinVerwalten": "Kulübü yönet",
  "pf.vereinseinstellungen": "Kulüp ayarları",
  "ev.titel": "Takvim",
  "ev.eintragen": "Etkinlik ekle",
  "ev.alle": "Tümü",
  "ev.training": "Antrenman",
  "ev.spiele": "Maçlar",
  "ev.events": "Etkinlikler",
  "ev.alleTeams": "Tüm takımlar",
  "ev.datum": "Tarih",
  "ev.beginn": "Başlangıç",
  "ev.ende": "Bitiş",
  "ev.heimspiel": "İç saha maçı",
  "ev.spiel": "Maç",
  "ev.vereinsevent": "Kulüp etkinliği",
  "ev.wiederholend": "Tekrarlanan",
  "ev.werDabei": "Kimler geliyor?",
  "ev.bistDuDabei": "Geliyor musun?",
  "ev.zugesagt": "Katılıyorum",
  "ev.abgesagt": "Katılmıyorum",
  "ev.absagen": "İptal et",
  "ev.absageGrund": "Neden iptal ediliyor?",
  "ev.jetztAbsagen": "Şimdi iptal et",
  "ev.keineTermine": "Bu dönemde etkinlik yok.",
  "home.willkommen": "Tekrar hoş geldin",
  "home.naechstesSpiel": "Sonraki maç",
  "home.naechstesTraining": "Sonraki antrenman",
  "home.mitmachen": "Katıl",
  "home.aktionen": "Etkinlikler ve oylamalar",
  "home.tage": "GÜN",
  "home.std": "SAAT",
  "home.min": "DK",
  "allg.speichern": "Kaydet",
  "allg.abbrechen": "İptal",
  "allg.loeschen": "Sil",
  "allg.bearbeiten": "Düzenle",
  "allg.schliessen": "Kapat",
  "allg.zurueck": "Geri",
  "allg.weiter": "Devam",
  "allg.suchen": "Ara …",
  "allg.keineEintraege": "Henüz bir şey yok.",
  "nav.home": "Ana sayfa",
  "nav.events": "Takvim",
  "nav.teams": "Takımlar",
  "nav.chat": "Sohbet",
  "nav.profile": "Profil",
  "nav.fees": "Aidatlar",
  "nav.news": "Haberler",
  "nav.admin": "Yönetim",
  "nav.sponsors": "Sponsorlar",
  "sub.season": "Sezonun sporcusu",
  "sub.tipp": "Tahmin oyunu",
  "sub.duty": "Gönüllü görevleri",
  "sub.postfach": "Bildirimler",
  "sprache.titel": "Dilini seç",
  "sprache.hinweis": "Uygulamayı hangi dilde kullanmak istersin? Bunu daha sonra profilinden değiştirebilirsin.",
  "sprache.weiter": "Devam",
  "login.willkommen": "Tekrar hoş geldin",
  "login.email": "E-posta adresi",
  "login.passwort": "Şifre",
  "login.vergessen": "Şifreni mi unuttun?",
  "login.anmelden": "Giriş yap",
  "login.keinKonto": "Hesabın yok mu?",
  "login.registrieren": "Kayıt ol",
  "reg.titel": "Hesap oluştur",
  "reg.vorname": "Ad",
  "reg.nachname": "Soyad",
  "reg.schonMitglied": "Zaten üye misin?",
  "reg.anmelden": "Giriş yap",
  "reg.fastGeschafft": "Neredeyse tamam",
  "reg.bestaetigen": "Bir e-posta alacaksın. Bilgilerinin doğru olduğundan emin olabilmemiz için lütfen onayla.",
  "reg.danach": "Ardından giriş yapabilirsin.",
  "reg.jetztAnmelden": "Şimdi giriş yap",
  "reg.keineMail": "E-posta gelmedi mi? Spam klasörüne bak — genellikle bir dakika içinde gelir.",
  "profil.sprache": "Dil",
  "profil.spracheHinweis": "Uygulama dili",
};

const fr: Woerterbuch = {
  "allg.entfernen": "Retirer",
  "allg.anlegen": "Créer",
  "allg.hinzufuegen": "Ajouter",
  "allg.abmelden": "Se déconnecter",
  "allg.laedt": "Chargement …",
  "allg.niemandGefunden": "Personne trouvée.",
  "allg.ablehnen": "Refuser",
  "allg.annehmen": "Accepter",
  "allg.austragen": "Me désinscrire",
  "allg.uebernehmen": "Je prends",
  "allg.eintragenKnopf": "Ajouter",
  "feld.vollerName": "Nom et prénom",
  "feld.rueckennummer": "Numéro de maillot",
  "feld.stadt": "Ville",
  "feld.gegner": "Adversaire",
  "tm.mannschaften": "Équipes",
  "recht.impressum": "Mentions légales",
  "recht.datenschutz": "Confidentialité",
  "recht.nutzung": "Conditions d'utilisation",
  "tm.meineTeams": "Mes équipes",
  "tm.alleTeams": "Toutes les équipes",
  "tm.kader": "Effectif",
  "tm.meinTeam": "Mon équipe",
  "tm.mannschaft": "Équipe",
  "pf.einstellungen": "Réglages",
  "pf.persoenlich": "Données personnelles",
  "pf.konto": "Compte et sécurité",
  "pf.vereinMitglied": "Club et adhésion",
  "pf.benachrichtigungen": "Notifications et agenda",
  "pf.zugang": "Accès et parrainage",
  "pf.support": "Assistance et retours",
  "pf.einladen": "Inviter des amis",
  "pf.kontoLoeschen": "Supprimer le compte",
  "pf.vereinVerwalten": "Gérer le club",
  "pf.vereinseinstellungen": "Réglages du club",
  "ev.titel": "Agenda",
  "ev.eintragen": "Ajouter un événement",
  "ev.alle": "Tous",
  "ev.training": "Entraînement",
  "ev.spiele": "Matchs",
  "ev.events": "Événements",
  "ev.alleTeams": "Toutes les équipes",
  "ev.datum": "Date",
  "ev.beginn": "Début",
  "ev.ende": "Fin",
  "ev.heimspiel": "Match à domicile",
  "ev.spiel": "Match",
  "ev.vereinsevent": "Événement du club",
  "ev.wiederholend": "Récurrent",
  "ev.werDabei": "Qui vient ?",
  "ev.bistDuDabei": "Tu viens ?",
  "ev.zugesagt": "Présent",
  "ev.abgesagt": "Absent",
  "ev.absagen": "Annuler",
  "ev.absageGrund": "Pourquoi cette annulation ?",
  "ev.jetztAbsagen": "Annuler maintenant",
  "ev.keineTermine": "Aucun événement sur cette période.",
  "home.willkommen": "Bon retour",
  "home.naechstesSpiel": "Prochain match",
  "home.naechstesTraining": "Prochain entraînement",
  "home.mitmachen": "Participer",
  "home.aktionen": "Activités et votes",
  "home.tage": "JOURS",
  "home.std": "H",
  "home.min": "MIN",
  "allg.speichern": "Enregistrer",
  "allg.abbrechen": "Annuler",
  "allg.loeschen": "Supprimer",
  "allg.bearbeiten": "Modifier",
  "allg.schliessen": "Fermer",
  "allg.zurueck": "Retour",
  "allg.weiter": "Continuer",
  "allg.suchen": "Rechercher …",
  "allg.keineEintraege": "Rien pour l'instant.",
  "nav.home": "Accueil",
  "nav.events": "Agenda",
  "nav.teams": "Équipes",
  "nav.chat": "Chat",
  "nav.profile": "Profil",
  "nav.fees": "Cotisations",
  "nav.news": "Rédaction",
  "nav.admin": "Administration",
  "nav.sponsors": "Sponsors",
  "sub.season": "Athlète de la saison",
  "sub.tipp": "Pronostics",
  "sub.duty": "Bénévoles",
  "sub.postfach": "Notifications",
  "sprache.titel": "Choisis ta langue",
  "sprache.hinweis": "Dans quelle langue veux-tu utiliser l'application ? Tu pourras la changer plus tard dans ton profil.",
  "sprache.weiter": "Continuer",
  "login.willkommen": "Bon retour",
  "login.email": "Adresse e-mail",
  "login.passwort": "Mot de passe",
  "login.vergessen": "Mot de passe oublié ?",
  "login.anmelden": "Se connecter",
  "login.keinKonto": "Pas encore de compte ?",
  "login.registrieren": "S'inscrire",
  "reg.titel": "Créer un compte",
  "reg.vorname": "Prénom",
  "reg.nachname": "Nom",
  "reg.schonMitglied": "Déjà membre ?",
  "reg.anmelden": "Se connecter",
  "reg.fastGeschafft": "Presque terminé",
  "reg.bestaetigen": "Tu vas recevoir un e-mail. Merci de le confirmer pour que nous soyons sûrs que tes données sont correctes.",
  "reg.danach": "Ensuite, tu pourras te connecter.",
  "reg.jetztAnmelden": "Se connecter",
  "reg.keineMail": "Pas d'e-mail ? Regarde dans les indésirables — il arrive généralement en une minute.",
  "profil.sprache": "Langue",
  "profil.spracheHinweis": "Langue de l'application",
};

const WOERTERBUECHER: Record<string, Woerterbuch> = { de, en, es, pt, it, tr, fr };

export const SPRACHE_SPEICHER = "cmo.sprache";

/* Die gewaehlte Sprache aus dem Geraet lesen.
   Sie steht dort UND am Konto: Im Geraet, weil die Wahl vor der Anmeldung
   getroffen wird und es dann noch kein Konto gibt; am Konto, damit sie auf
   einem zweiten Geraet nicht erneut abgefragt wird. */
export function gespeicherteSprache(): Sprachcode | null {
  if (typeof window === "undefined") return null;
  try {
    const wert = window.localStorage.getItem(SPRACHE_SPEICHER);
    return SPRACHEN.some((s) => s.code === wert) ? (wert as Sprachcode) : null;
  } catch {
    /* Privater Modus, gesperrte Website-Daten: Dann wird eben jedes Mal
       gefragt - besser als ein Absturz beim Start. */
    return null;
  }
}

export function spracheMerken(code: string) {
  if (typeof window === "undefined") return;
  try { window.localStorage.setItem(SPRACHE_SPEICHER, code); } catch { /* siehe oben */ }
}

/* Uebersetzen. Fehlt ein Schluessel, kommt der deutsche Text - nicht der
   Schluessel. Ein deutscher Satz ist unschoen, "profil.titel" ist unbrauchbar. */
export function uebersetze(code: string, schluessel: string): string {
  return WOERTERBUECHER[code]?.[schluessel] ?? de[schluessel] ?? schluessel;
}
