#!/usr/bin/env node
/* Werkzeug zum Uebersetzen von app/page.tsx.
 *
 * WARUM EIN WERKZEUG
 * Die Datei hat rund 11.700 Zeilen und ueber hundert Komponenten. Jede
 * Textstelle von Hand zu ersetzen heisst: Stelle finden, pruefen ob die
 * umgebende Komponente die Uebersetzungsfunktion ueberhaupt kennt, notfalls
 * eine Zeile ergaenzen, dann ersetzen. Bei 369 Texten sind das rund 1.500
 * Handgriffe - und beim fuenfzigsten vergisst man den zweiten Schritt.
 *
 * Genau dieser zweite Schritt ist der gefaehrliche: Fehlt "const t = useT()",
 * ist t undefined, und die Ansicht stuerzt beim Oeffnen ab. Der Build meldet
 * das NICHT - es ist ein Laufzeitfehler.
 *
 * Das Werkzeug macht beides zusammen und meldet, was es nicht sicher
 * zuordnen kann, statt zu raten.
 *
 * AUFRUF
 *   node scripts/uebersetzen.mjs pruefen      zeigt, was zu tun waere
 *   node scripts/uebersetzen.mjs anwenden     schreibt die Aenderungen
 */

import { readFileSync, writeFileSync } from "node:fs";

const DATEI = "app/page.tsx";
const modus = process.argv[2] || "pruefen";

/* Was ersetzt werden soll: deutscher Text -> Schluessel.
   Nur Texte, die in JEDEM Zusammenhang dasselbe bedeuten. Ein Wort wie
   "Termin" kann Ueberschrift oder Knopf sein - solche kommen hier NICHT
   hinein, sondern werden einzeln behandelt. */
const ERSETZUNGEN = {
  "Nachricht melden - ": "chat.meldenBetreff",
  "Verein · ": "verein.mitPunktRaum",
  "Abgesagt": "ev.abgesagtLabel",
  "Abonnement erstellen": "zug.aboErstellen",
  "Abschließen": "allg.abschliessen",
  "Adresse": "feld.adresse",
  "Als Startansicht speichern": "allg.alsStartansicht",
  "Als dieses Konto fortfahren": "login.alsKontoFortfahren",
  "Anbieten": "ev.anbieten",
  "Anfrage abgelehnt.": "fzg.anfrageAbgelehnt",
  "Anfrage angenommen.": "fzg.anfrageAngenommen",
  "Anfrage liegt vor": "zug.anfrageLiegtVor",
  "Anfrage senden": "zug.anfrageSenden",
  "Anmelden": "login.anmeldenKnopf",
  "Anwenden": "help.anwenden",
  "Anzeige": "sp.anzeige",
  "Archivieren": "tm.archivieren",
  "Athlet/in": "rol.athletLabel",
  "Athleten-Mannschaften gespeichert.": "tm.athletenMannschaftenGespeichert",
  "Athleten-Teams": "tm.athletenTeamsKurz",
  "Athletenwahl": "sais.athletenwahl",
  "Aufgabe wurde angelegt.": "auf.wurdeAngelegt",
  "Aufgabe wurde geändert.": "auf.wurdeGeaendert",
  "Auswärts": "ev.auswaerts",
  "Automatisierung": "sys.automatisierung",
  "Beenden": "mit.beenden",
  "Beitragsdatensatz wurde gespeichert.": "bei.datensatzGespeichert",
  "Betreiber": "sp.betreiber",
  "Bild ersetzen": "allg.bildErsetzen",
  "Das bisherige Passwort ist nicht korrekt.": "sich.altesPasswortFalsch",
  "Datensatz anlegen": "bei.datensatzAnlegen",
  "Eigenen Sponsor eintragen": "sp.eigenenEintragen",
  "Eintrag": "help.eintragLabel",
  "Eltern": "fam.eltern",
  "Endzeit": "feld.endzeit",
  "Erinnerung senden": "bei.erinnerungSenden",
  "Erledigt": "auf.erledigt",
  "Events": "ev.events2",
  "Fahrzeug bearbeiten": "fzg.bearbeiten",
  "Fahrzeug buchen": "fzg.buchen",
  "Familie": "fam.familie",
  "Familienprofile": "fam.profile",
  "Farben speichern": "verein.farbenSpeichern",
  "Fehler per E-Mail melden": "pf.fehlerMelden",
  "Freigegeben": "tipp.freigegeben",
  "Freundliche Erinnerung": "bei.freundlicheErinnerung",
  "Funktionen": "sys.funktionen",
  "Geburtsdatum": "feld.geburtsdatum",
  "Heim": "ev.heim",
  "Helferplan": "help.helferplan",
  "Helferplanung": "help.helferplanung",
  "Historie ausblenden": "sais.historieAusblenden",
  "Ihr Sponsor": "sp.ihrSponsor",
  "Im Apple App Store bewerten": "pf.appleBewerten",
  "Im Google Play Store bewerten": "pf.googleBewerten",
  "Kalenderverbindung aktualisiert.": "kal.verbindungAktualisiert",
  "Kein Termin geplant": "ev.keinTerminGeplant",
  "Kinder": "fam.kinder",
  "Kontaktdaten": "feld.kontaktdaten",
  "Kostenlose Stufe": "zug.kostenloseStufe",
  "Mahnung": "bei.mahnung",
  "Mannschaft anlegen": "tm.anlegen",
  "Mannschaft wurde angelegt.": "tm.wurdeAngelegt",
  "Mannschaft wurde archiviert.": "tm.wurdeArchiviert",
  "Mannschaften speichern": "tm.mannschaftenSpeichern",
  "Mannschaftszuordnung gespeichert.": "tm.zuordnungGespeichert",
  "Mitglied": "rol.mitgliedLabel",
  "Mitglied entfernt": "mit.entfernt",
  "Mitglied gesperrt": "mit.gesperrt",
  "Mitgliedschaft beendet": "mit.mitgliedschaftBeendet",
  "Mitgliedschaft wurde abgelehnt.": "mit.wurdeAbgelehnt",
  "Mitgliedschaft wurde beendet.": "mit.wurdeBeendet",
  "Mitgliedschaft wurde freigegeben.": "mit.wurdeFreigegeben",
  "Mitgliedschaft wurde reaktiviert.": "mit.wurdeReaktiviert",
  "Neue Fahrzeugbuchung": "fzg.neueBuchung",
  "Neue News": "news.neu",
  "Neue Umfrage": "umf.neuAnlegen",
  "Neues Fahrzeug": "fzg.neues",
  "Neues Vorstandsprotokoll": "prot.neuesProtokoll",
  "News bearbeiten": "news.bearbeiten",
  "Nichts offen": "auf.nichtsOffen",
  "Noch offen": "bei.nochOffen",
  "Noch ohne Mannschaft": "tm.nochOhneMannschaft",
  "Offen": "bei.offen2",
  "Passwort erfolgreich geändert.": "sich.passwortGeaendert",
  "Person": "help.personLabel",
  "Privat": "fzg.privat",
  "Profil ohne eigene E-Mail": "pf.ohneEigeneMail",
  "Profile wurden zusammengeführt.": "mit.profileZusammengefuehrt",
  "Profileinstellungen": "pf.einstellungen2",
  "Protokoll-Aufgaben": "prot.aufgaben",
  "Protokolle": "prot.protokolle",
  "Push aktivieren": "push.aktivieren",
  "Push deaktivieren": "push.deaktivieren",
  "Push-Benachrichtigungen wurden deaktiviert.": "push.wurdenDeaktiviert",
  "Reaktivieren": "mit.reaktivieren",
  "Regel wurde gespeichert.": "straf.regelGespeichert",
  "Rollen": "sys.rollen",
  "Saison-Historie anzeigen": "sais.historieAnzeigen",
  "Satz wurde angelegt.": "help.satzAngelegt",
  "Spiele": "ev.spiele2",
  "Spielergebnisse": "sys.spielergebnisse",
  "Sponsor bearbeiten": "sp.bearbeiten",
  "Sponsor unseres Vereins": "sp.unseresVereins",
  "Sponsorenmanager": "sp.manager",
  "Stammdaten": "pf.stammdaten",
  "Stammdaten speichern": "pf.stammdatenSpeichern",
  "Startzeit": "feld.startzeit",
  "Station entfernt.": "help.stationEntfernt",
  "Strafe als bezahlt markiert.": "straf.alsBezahlt",
  "Strafe als offen markiert.": "straf.alsOffen",
  "Strafe wurde entfernt.": "straf.wurdeEntfernt",
  "Strafe wurde zugewiesen.": "straf.wurdeZugewiesen",
  "System": "sys.system",
  "Teilnehmende": "ev.teilnehmende",
  "Teilnehmer": "prot.teilnehmerKurz",
  "Termine": "ev.termineTitel",
  "Tipp abgeben": "tipp.abgeben",
  "Tipps": "tipp.tipps",
  "Trainingstermine": "ev.trainingstermine",
  "Umfrage-Antworten": "umf.antworten",
  "Umfrage-Stimmen": "umf.stimmen",
  "Umfragen": "umf.umfragen",
  "Unbekannt": "allg.unbekannt",
  "Verein": "verein.vereinLabel",
  "Verein suchen oder anlegen": "verein.suchenOderAnlegen",
  "Vereins-News": "news.vereinsNews",
  "Vereinseinstellungen": "verein.einstellungen",
  "Vereinsfarben gespeichert.": "verein.farbenGespeichert",
  "Vereinslogo gespeichert.": "verein.logoGespeichert",
  "Vereinsprofil": "verein.profil",
  "Vereinsprofil gespeichert.": "verein.profilGespeichert",
  "Vereinsverwaltung": "sys.vereinsverwaltung",
  "Verwaltung": "sys.verwaltung",
  "Voll": "help.voll",
  "Vorstand": "rol.vorstand",
  "Vorstand informiert": "prot.vorstandInformiert",
  "Warten auf Freigabe": "mit.wartenAufFreigabe",
  "Weitere Angaben": "pf.weitereAngaben",
  "Weiterem Verein beitreten": "verein.weiteremBeitreten",
  "Zahlungserinnerungen": "bei.zahlungserinnerungen",
  "Zugesagt": "ev.zugesagtLabel",
  "Zuordnung speichern": "tm.zuordnungSpeichern",
  "Zuweisen": "straf.zuweisen",
  "Alle Personen auswählen, die ebenfalls zu diesem Familienbeitrag gehören.": "bei.familieWaehlen",
  "Anderen Nutzer suchen …": "ph.anderenNutzerSuchen",
  "Anzeigen & Kampagnen": "sp.anzeigenKampagnen",
  "Athlet/in auswählen und anschließend seine Mannschaften festlegen.": "tm.athletWaehlenHinweis",
  "Athlet/in suchen …": "ph.athletSuchen",
  "Bezahlt ✓": "bei.bezahltHaken",
  "Bild hochladen (max. 2 MB)": "allg.bildHochladen",
  "Bis": "allg.bis",
  "Buchung wirklich stornieren?": "fzg.stornoFrage",
  "Danach legst du das erste Konto an — es wird automatisch Vereins-Administrator.": "verein.erstesKonto",
  "Das neue Passwort ist zu schwach. Nimm ein längeres oder ungewöhnlicheres.": "sich.passwortSchwach",
  "Der Sponsor wird nicht mehr angezeigt — die Laufzeit ist beendet.": "sp.laufzeitBeendet",
  "Die Löschung entfernt dein Konto und alle personenbezogenen Daten dauerhaft.": "konto.loeschungHinweis",
  "Diese Nachricht dauerhaft loeschen?": "chat.loeschenFrage",
  "Dieses Konto ist gesperrt. Bitte wende dich an die Vereinsleitung.": "login.kontoGesperrt",
  "E-Mail-Adressen": "feld.emailAdressen",
  "Eingetragen ✓": "help.eingetragenHaken",
  "Einladungslink:": "zug.einladungslink",
  "Elternteil suchen …": "ph.elternteilSuchen",
  "Er verschwindet für alle. Rückgängig machen lässt sich das nicht.": "allg.unwiderruflich",
  "Ergebnis korrigieren & neu berechnen": "tipp.ergebnisKorrigieren",
  "Ergebnis speichern & Punkte berechnen": "tipp.ergebnisSpeichern",
  "Erledigt?": "auf.erledigtFrage",
  "Fahrgemeinschaft wirklich entfernen?": "ev.fahrgemeinschaftEntfernenFrage",
  "Fahrgemeinschaft: Platz anbieten": "ev.platzAnbieten",
  "Fahrzeugbuchungen sind nur mit einem echten Vereinskonto verfügbar.": "fzg.nurEchterVerein",
  "Für Heimspiel-Helferdienste noch nicht 16 Jahre alt.": "help.unter16",
  "Für diese Mannschaft liegt noch keine abgeschlossene Saison vor.": "sais.keineAbgeschlossene",
  "Für diese Mannschaft sind noch keine aktiven Athlet/innen hinterlegt.": "tm.keineAktivenAthleten",
  "Gesendet ✓": "allg.gesendetHaken",
  "Helferdienst-berechtigt ✓ (16+)": "help.berechtigt",
  "Nach längerer Inaktivität wird dieses Konto automatisch abgemeldet.": "sich.autoLogoutHinweis",
  "Nachricht melden -": "chat.meldenVor",
  "Nein": "allg.nein",
  "Nie": "kal.nieKurz",
  "Noch keine Mannschaften angelegt — das geht im Reiter „Mannschaften“.": "tm.keineAngelegt",
  "Nur-Lese-Ansicht aller Vereinsmitglieder. Änderungen sind hier nicht möglich.": "mit.nurLesen",
  "Nutzer suchen …": "ph.nutzerSuchen",
  "Ohne Auswahl bliebe der Kalender leer — wähle mindestens eine Art.": "kal.mindestensEine",
  "Punkte wurden berechnet ✓": "tipp.punkteBerechnet",
  "Rollen & Trainer": "rol.rollenTrainer",
  "Speichert …": "allg.speichertKurz",
  "Strafe wirklich entfernen?": "straf.entfernenFrage",
  "Theke, Grill, Kuchenbuffet …": "ph.stationenBeispiel",
  "Titel des Events *": "ph.titelEvent",
  "Titel des Spiels *": "ph.titelSpiel",
  "Titel des Trainings *": "ph.titelTraining",
  "Verein ·": "verein.mitPunkt",
  "Von": "allg.von",
  "Vorhandenen Athlet/in suchen …": "ph.vorhandenenAthletSuchen",
  "Vorhandenes Elternteil suchen …": "ph.vorhandenesElternteilSuchen",
  "Wir": "ev.wir",
  "Ziel erreicht 🎉": "auf.zielErreicht",
  "Euro (€)": "waehr.eur",
  "Schweizer Franken (CHF)": "waehr.chf",
  "Britisches Pfund (£)": "waehr.gbp",
  "US-Dollar ($)": "waehr.usd",
  "Dänische Krone": "waehr.dkk",
  "Norwegische Krone": "waehr.nok",
  "Schwedische Krone": "waehr.sek",
  "Polnischer Złoty": "waehr.pln",
  "Tschechische Krone": "waehr.czk",
  "Kind noch nicht registriert? Optional vorläufig anlegen": "reg.kindVorlaeufig",
  "Für diese Mannschaft ist derzeit kein Training geplant.": "tm.keinTraining",
  "Datum *": "feld.datumPflicht",
  "Beginn *": "feld.beginnPflicht",
  "Ende *": "feld.endePflicht",
  "Mitglied auswählen, um Beiträge und Rechnungen zu verwalten.": "bei.mitgliedWaehlen",
  "Elternteil – Athlet/in oder Kind hinzufügen": "fam.elternteilHinzu",
  "Athlet/in / Kind – Elternteil hinzufügen": "fam.kindHinzu",
  "Die Kapitänsrolle gilt immer für die ausgewählte Mannschaft.": "rol.kapitaenHinweis",
  "Danach können Athlet/innen das Team in ihrem Profil auswählen.": "rol.danachProfil",
  "Nur dann gibt es Strafenkatalog & Zuweisungen für dieses Team.": "rol.nurDannStrafen",
  "Dieser Mannschaft sind noch keine Athlet/innen zugeordnet.": "tm.keineAthletenZugeordnet",
  "Regeln und Kosten werden für jede Mannschaft getrennt geführt.": "straf.getrennt",
  "Für diese Mannschaft sind noch keine Regeln hinterlegt.": "straf.keineRegelnTeam",
  "Aufgaben sind nur mit einem echten Vereinskonto verfügbar.": "auf.nurEchterVerein",
  "Vergib zuerst unter „Rollen & Trainer“ die Rolle Athlet/in.": "tm.rolleAthletZuerst",
  "Du kannst deine Stimme bis zum Stichtag noch ändern.": "umf.stimmeAendern",
  "Betreute Mannschaft · maximal ein Teammanager je Mannschaft": "rol.teammanagerHinweis",
  "Nach der Freigabe kann sich das Mitglied sofort anmelden.": "mit.sofortAnmelden",
  "Neue Registrierungen erscheinen automatisch hier.": "mit.neueAutomatisch",
  "Nicht freigeschaltet": "sys.nichtFreigeschaltet",
  "Primärfarbe": "verein.primaerfarbe",
  "Sekundärfarbe": "verein.sekundaerfarbe",
  "Wird gespeichert …": "allg.wirdGespeichert",
  "Konnte nicht gespeichert werden.": "allg.speichernFehler",
  "Kein Verein gefunden.": "verein.keinerGefunden",
  "Bitte einen Mannschaftsnamen eingeben.": "tm.nameEingeben",
  "Übersicht": "allg.uebersicht",
  "Zu viele Anmeldeversuche in kurzer Zeit. Bitte warte ein paar Minuten und versuche es dann noch einmal.": "login.zuVieleVersuche",
  "Bitte gib deinen Namen an.": "reg.nameAngeben",
  "Bitte zuerst deine E-Mail-Adresse eintragen.": "login.emailZuerst",
  "Das Passwort muss mindestens 8 Zeichen haben.": "reg.passwortMindestens8",
  "Sichere Registrierung über Supabase": "reg.sicherUeberSupabase",
  "Die Liste konnte nicht geladen werden.": "allg.listeLadenFehler",
  "Für Training und Spiel wird eine Mannschaft gebraucht. Lege zuerst unter „Mannschaften“ eine an.": "ev.mannschaftNoetig",
  "Der Termin konnte nicht gelöscht werden. Prüfe deine Verbindung und versuche es noch einmal.": "ev.loeschenFehler",
  "Als Vereins-Sysadmin kannst du jede Mannschaft auswählen.": "tm.sysadminAlle",
  "Der Beitragsdatensatz konnte nicht gelöscht werden.": "bei.datensatzLoeschenFehler",
  "Das News-Bild konnte nicht hochgeladen werden.": "news.bildUploadFehler",
  "Das Kinderprofil konnte nicht gespeichert werden.": "fam.kindProfilFehler",
  "Kapitän gespeichert": "tm.kapitaenGespeichert",
  "Die Mannschaft konnte nicht geändert werden.": "tm.aendernFehler",
  "Die Regel konnte nicht gespeichert werden.": "straf.regelSpeichernFehler",
  "Bitte einen Titel eingeben.": "allg.titelEingeben",
  "Fahrzeug konnte nicht geändert werden.": "fzg.aendernFehler",
  "Buchung konnte nicht angelegt werden.": "fzg.buchungAnlegenFehler",
  "Aktion nicht möglich.": "allg.aktionNichtMoeglich",
  "Alle Stationen entfernt.": "help.alleStationenEntfernt",
  "Für euren Verein liegt bereits eine Anfrage vor. Wir melden uns.": "zug.anfrageBereitsVorhanden",
  "Anfragen konnten nicht geladen werden.": "zug.anfragenLadenFehler",
  "Diese Mitgliederausweisnummer wird bereits verwendet.": "mit.ausweisnummerVergeben",
  "Kein Push-Token erhalten.": "push.keinToken",
  "Das neue Passwort muss mindestens 8 Zeichen haben und übereinstimmen.": "sich.neuesPasswortRegeln",
  "Kalender konnte nicht verbunden werden.": "kal.verbindenFehler",
  "Einladungslink kopiert — jetzt einfügen und verschicken.": "zug.einladungslinkKopiert",
  "Die offenen Punkte konnten nicht geladen werden.": "auf.offenePunkteFehler",
  "Der Platz ist ausgeblendet — hier sieht niemand etwas.": "sp.platzAusgeblendet",
  "Das Bild konnte nicht gelesen werden.": "allg.bildLesenFehler",
  "Die Person kann nicht entfernt werden, weil noch Einträge an ihr hängen. Beende die Mitgliedschaft stattdessen.": "mit.personNichtEntfernbar",
  "Wird zusammengeführt …": "sys.wirdZusammengefuehrt",
  "Deine Stimme konnte nicht entfernt werden.": "umf.stimmeEntfernenFehler",
  "Der Haken an der Aufgabe konnte nicht gespeichert werden.": "auf.hakenSpeichernFehler",
  "Der Verein konnte nicht angelegt werden. Bitte pruefe die Angaben.": "verein.anlegenFehler",
  "Die Beitragsverwaltung konnte nicht geladen werden.": "bei.verwaltungLadenFehler",
  "Die Anfrage konnte nicht gesendet werden. Bitte versuche es später noch einmal.": "zug.anfrageSendenFehler",
  "Die Startansicht konnte nicht gespeichert werden.": "pf.startansichtFehler",
  "Konnte nicht entfernt werden.": "allg.entfernenFehler",
  "Die Mannschaft des Teammanagers konnte nicht gespeichert werden.": "tm.managerMannschaftFehler",
  "Wird angelegt …": "allg.wirdAngelegt",
  "Diese Mannschaft ist bereits vorhanden.": "tm.bereitsVorhanden",
  "Deine Stimme konnte nicht gespeichert werden.": "umf.stimmeFehler",
  "Das Passwort ist zu kurz. Nimm mindestens 8 Zeichen.": "sich.passwortZuKurz",
  "Es ist noch kein Verein eingetragen.": "verein.keinerEingetragen",
  "Zurücksetzen ist nur mit einem echten Konto möglich.": "konto.zuruecksetzenNurEcht",
  "Die Passwörter stimmen nicht überein.": "reg.passwoerterUngleich",
  "Demo-Prototyp — es werden keine echten Daten übertragen.": "sys.demoPrototyp",
  "Bitte eine gültige Anzahl freier Plätze angeben.": "fzg.freiePlaetzeUngueltig",
  "Dir ist noch keine Mannschaft zugewiesen. Die Vereinsverwaltung kann das eintragen.": "tm.keineZugewiesen",
  "Der Termin wurde nicht gelöscht. Entweder fehlt dir das Recht für diese Mannschaft, oder er ist bereits entfernt.": "ev.loeschenFehlgeschlagen",
  "Du kannst nur deine im Profil hinterlegten Mannschaften auswählen.": "tm.nurEigeneWaehlen",
  "kein Kanal sichtbar": "chat.keinKanalSichtbar",
  "Das News-Bild konnte nicht vorbereitet werden.": "news.bildFehler",
  "Die Verknüpfung konnte nicht gelöscht werden.": "fam.verknuepfungLoeschenFehler",
  "Kapitän speichern": "tm.kapitaenSpeichern",
  "Mannschaft wurde geändert.": "tm.geaendert",
  "Die Regel konnte nicht gelöscht werden.": "straf.regelLoeschenFehler",
  "Aufgabe konnte nicht geändert werden.": "auf.aendernFehler",
  "Fahrzeug konnte nicht angelegt werden.": "fzg.anlegenFehler",
  "Buchung bestätigt — die anfragende Person wurde benachrichtigt.": "fzg.buchungBestaetigt",
  "Eine Person ist": "allg.einePersonIst",
  "Noch niemandem zugewiesen": "auf.niemandZugewiesen",
  "Die Anfrage konnte nicht gesendet werden.": "allg.anfrageSendenFehler",
  "Aktion konnte nicht ausgeführt werden.": "allg.aktionFehler",
  "Die Daten konnten nicht gespeichert werden.": "allg.datenSpeichernFehler",
  "Nur im Browser verfügbar.": "sys.nurImBrowser",
  "Passwort stimmt nicht": "login.passwortFalsch",
  "Ohne Auswahl kommen die Mannschaften, in denen du oder deine Kinder stehen — dazu alle vereinsweiten Termine.": "kal.ohneAuswahl",
  "Deine Badges": "pf.badges",
  "Bitte ein Bild auswählen.": "allg.bildWaehlen",
  "Der Platz ist gerade leer.": "allg.platzLeer",
  "Das Vereinslogo konnte nicht hochgeladen werden.": "verein.logoUploadFehler",
  "Die Person konnte nicht entfernt werden.": "mit.personEntfernenFehler",
  "Zusammenführen": "mit.zusammenfuehren",
  "Die Umfrage konnte nicht angelegt werden.": "umf.anlegenFehler",
  "Die Einstellung konnte nicht gespeichert werden.": "sys.einstellungFehler",
  "Der Verein konnte nicht angelegt werden.": "verein.anlegenFehler2",
  "Die Vereins-News konnten nicht geladen werden.": "news.ladenFehler",
  "Löschen ist nur mit einem echten Konto möglich.": "konto.loeschenNurEcht",
  "Nicht moeglich.": "allg.nichtMoeglich",
  "Keine E-Mail hinterlegt": "pf.keineEmail",
  "Wird gelöscht …": "allg.wirdGeloescht",
  "Konnte nicht gelöscht werden.": "allg.loeschenFehler",
  "Das Vereinsprofil konnte nicht geladen werden.": "verein.profilLadenFehler",
  "Diese E-Mail-Adresse sieht nicht richtig aus. Bitte prüfe sie auf Tippfehler.": "reg.emailUngueltig",
  "Bitte Vereinsname, Kurzname und Vereinsregisternummer angeben.": "verein.pflichtfelder",
  "Mail ist unterwegs": "reg.mailUnterwegs",
  "Für diese E-Mail existiert bei diesem Verein bereits ein Konto.": "reg.kontoExistiert",
  "Das ist deine Startansicht": "pf.startansicht",
  "Bitte gib an, von wo du losfährst.": "fzg.abfahrtsortFehlt",
  "Bitte gib einen Titel und einen Ort an.": "ev.titelUndOrt",
  "Die Terminreihe konnte nicht gelöscht werden. Prüfe deine Verbindung und versuche es noch einmal.": "ev.reiheLoeschenFehler",
  "Als Kapitän oder Teammanager kannst du nur für deine hinterlegte Mannschaft eintragen.": "tm.nurEigeneMannschaft",
  "Die Nachricht konnte nicht geloescht werden.": "chat.nachrichtLoeschenFehler",
  "Die News konnte nicht geändert werden.": "news.aendernFehler",
  "Du verwaltest dein Familienprofil selbst.": "fam.selbstVerwalten",
  "Deine Mannschaften konnten nicht geladen werden.": "tm.meineLadenFehler",
  "Die Mannschaft konnte nicht archiviert werden.": "tm.archivierenFehler",
  "Regel wurde gelöscht.": "straf.regelGeloescht",
  "Aufgabe konnte nicht angelegt werden.": "auf.anlegenFehler",
  "Bitte Start- und Enddatum angeben.": "ev.startEndeDatum",
  "Anfrage abgelehnt — die anfragende Person wurde benachrichtigt.": "mit.anfrageAbgelehnt",
  "Die Station konnte nicht entfernt werden.": "help.stationEntfernenFehler",
  "Sätze konnten nicht geladen werden.": "help.saetzeLadenFehler",
  "Anfrage zurückziehen?": "mit.anfrageZurueckziehenFrage",
  "Bitte einen Namen eingeben.": "allg.nameEingeben",
  "Persönliche Daten gespeichert.": "pf.datenGespeichert",
  "Push konnte nicht aktiviert werden.": "push.aktivierenFehler",
  "Das Passwort konnte nicht geändert werden. ": "sich.passwortAendernFehler",
  "Nur die gewählten Mannschaften, dazu alle vereinsweiten Termine.": "kal.nurGewaehlteTeams",
  "Die Änderung konnte nicht gespeichert werden.": "allg.aenderungSpeichernFehler",
  "Das Bild darf höchstens 2 MB groß sein.": "allg.bildMaxGroesse",
  "Werbefläche eingeblendet": "sp.werbeflaecheEingeblendet",
  "Das Vereinsprofil konnte nicht aktualisiert werden.": "verein.profilAktualisierenFehler",
  "Die offenen Mitgliedsanträge konnten nicht geladen werden.": "mit.antraegeLadenFehler",
  "Athlet/in der Saison": "sais.athletDerSaison",
  "Die Antworten konnten nicht gespeichert werden.": "umf.antwortenSpeichernFehler",
  "Die Erinnerung wurde verschickt, aber nicht vermerkt — sie könnte doppelt kommen.": "bei.erinnerungNichtVermerkt",
  "Das Vereinsprofil konnte nicht geladen werden": "verein.profilNichtGeladen",
  "Die App ist nicht mit der Datenbank verbunden. Bitte melde das dem Verein.": "sys.keineDatenbank",
  "Das Konto konnte nicht vollständig gelöscht werden. Bitte wende dich an den Support.": "konto.loeschenFehler",
  "Die Mannschaften konnten nicht geladen werden.": "tm.ladenFehler",
  "Die Sitzung ist abgelaufen. Bitte melde dich erneut an.": "login.sitzungAbgelaufen",
  "Endgültig löschen": "allg.endgueltigLoeschen",
  "Kein Fälligkeitsdatum": "auf.keinFaelligkeitsdatum",
  "E-Mail oder Passwort ist falsch.": "login.falscheDaten",
  "Die Registrierung ist gerade nicht möglich. Bitte versuche es in ein paar Minuten noch einmal.": "reg.geradeNichtMoeglich",
  "Vereinslogo ausgewählt": "verein.logoAusgewaehlt",
  "Das Zurücksetzen ist gerade nicht möglich. Bitte versuche es in ein paar Minuten noch einmal.": "login.zuruecksetzenNichtMoeglich",
  "Bitte akzeptiere die Nutzungsbedingungen und die Datenschutzerklärung.": "reg.bitteAkzeptieren",
  "keine Termine geplant": "ev.keineGeplant",
  "Fahrgemeinschaft konnte nicht angelegt werden.": "fzg.fahrgemeinschaftFehler",
  "Das Ende muss nach dem Beginn liegen.": "ev.endeNachBeginn",
  "Die Terminreihe wurde nicht gelöscht. Entweder fehlt dir das Recht für diese Mannschaft, oder sie ist bereits entfernt.": "ev.reiheNichtGeloescht",
  "Alle": "ev.alle2",
  "Die Nachricht konnte nicht gesendet werden.": "chat.sendenFehler",
  "Die News konnte nicht gespeichert werden.": "news.speichernFehler",
  "＋ Verknüpfen": "fam.verknuepfenKnopf",
  "Wird geladen ...": "allg.wirdGeladen",
  "Der Strafenkatalog konnte nicht geladen werden.": "straf.katalogLadenFehler",
  "Bitte Athlet/in und Strafe auswählen.": "straf.athletUndStrafeWaehlen",
  "Aufgabe angelegt, aber die Verantwortlichen konnten nicht gesetzt werden.": "auf.angelegtOhneVerantwortliche",
  "Bitte eine Mannschaft auswählen oder auf „Privat“ umschalten.": "ev.mannschaftOderPrivat",
  "Konnte nicht storniert werden.": "allg.stornoFehler",
  "Eine Eintragung wurde": "help.eintragungWurde",
  "Satz konnte nicht angelegt werden.": "help.satzAnlegenFehler",
  " — für weitere Mitglieder braucht ihr den Vollzugang.": "zug.vollzugangHinweis",
  "Das Vereinsprofil konnte nicht gespeichert werden.": "verein.profilSpeichernFehler",
  "Persönliche Daten": "pf.persoenlich2",
  "Push-Benachrichtigungen sind jetzt aktiv.": "push.jetztAktiv",
  "Danke, dass du CMO bewertest. Wähle den Store deines Geräts.": "sys.bewertenStore",
  "Auswahl übernehmen": "allg.auswahlUebernehmen",
  "Kein Tippspiel": "tipp.keines",
  "Das Bild konnte nicht hochgeladen werden.": "allg.bildUploadFehler",
  "Werbefläche ausgeblendet": "sp.werbungAusgeblendet",
  "Vereinslogo auswählen": "verein.logoWaehlen",
  "Die Zahl der Zugänge deines Vereins ist ausgeschöpft. Unter Profil → Einstellungen → Zugang & Empfehlungen kann die Vereinsleitung mehr Zugänge anfragen.": "zug.ausgeschoepft",
  "Mitgliedsanträge": "mit.antraege",
  "Die Umfrage konnte nicht umgeschaltet werden.": "umf.umschaltenFehler",
  "Die Benachrichtigungen konnten nicht geladen werden.": "push.ladenFehler",
  "Für dieses Konto besteht noch keine Mitgliedschaft in einem Verein.": "konto.keineMitgliedschaft",
  "Die Vereinsregistrierung konnte nicht fertiggestellt werden.": "verein.registrierungFehler",
  "Dein Konto ist angelegt. Bitte bestätige jetzt die E-Mail — danach meldest du dich an und suchst deinen Verein.": "reg.kontoAngelegt",
  "geändert": "allg.geaendert",
  "Zu viele Versuche. Warte einen Moment und versuche es dann noch einmal.": "sich.zuVieleVersuche",
  " (Du)": "allg.duSuffix",
  "Bitte hinterlege zuerst eine Telefonnummer in deinem Profil (Profil → Kontaktdaten), um ein Fahrzeug zu buchen.": "fzg.telefonNoetig",
  "Diese E-Mail-Adresse ist noch nicht bestätigt. Sieh in deinem Postfach nach.": "login.mailNichtBestaetigt",
  "Noch nicht fällig": "bei.nochNichtFaellig",
  "Vereinslogo optional auswählen": "verein.logoWaehlenOptional",
  "Falls ein Konto mit dieser Adresse besteht, ist eine E-Mail mit einem Link unterwegs. Prüfe auch den Spam-Ordner.": "login.resetMailUnterwegs",
  "Zuerst dein Konto. Deinen Verein suchst du gleich danach aus — oder legst einen neuen an.": "reg.zuerstKonto",
  "Keine Kandidat/innen hinterlegt": "sais.keineKandidaten",
  "Eintragen nicht möglich (evtl. schon voll).": "help.eintragenNichtMoeglichVoll",
  "Der Termin konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es noch einmal.": "ev.speichernFehler",
  "Die Kalenderverbindung braucht ein echtes Vereinskonto.": "kal.brauchtVereinskonto",
  "Bitte eine gültige Beitragshöhe eingeben.": "bei.hoeheUngueltig",
  "In dieser Gruppe schreiben Trainer, Kapitäne und freigegebene Teammitglieder.": "chat.werSchreibtGruppe",
  "Bild ändern": "allg.bildAendern",
  "Die Trainer-Mannschaften konnten nicht geladen werden.": "tm.trainerTeamsLadenFehler",
  "Der Spieler konnte nicht angelegt werden.": "tm.spielerAnlegenFehler",
  "Die vergebenen Strafen konnten nicht geladen werden.": "straf.vergebeneLadenFehler",
  "Bitte eine Saisonbezeichnung eingeben, z. B. 2025/26.": "sais.bezeichnungFehlt",
  "Eintragen nicht möglich.": "help.eintragenNichtMoeglich",
  "Bitte einen Namen für die private Buchung angeben.": "fzg.privatNameFehlt",
  "Wird gebucht …": "fzg.wirdGebucht",
  "Eine Eintragung geht": "help.eineEintragungVerloren",
  "Diesen Satz inklusive aller Stationen wirklich löschen?": "help.satzMitStationenLoeschen",
  "Wird gesendet ...": "allg.wirdGesendet",
  "Die Athleten-Mannschaften konnten nicht gespeichert werden.": "tm.athletenTeamsSpeichernFehler",
  "Push wird auf diesem Gerät/Browser nicht unterstützt.": "push.nichtUnterstuetzt",
  "Push konnte nicht deaktiviert werden.": "push.deaktivierenFehler",
  "Danke, dass du CMO bewerten möchtest.": "sys.dankeBewertung",
  "noch keine Funktion da": "allg.nochKeineFunktion",
  "Die Tipprunden konnten nicht geladen werden.": "tipp.rundenLadenFehler",
  "Ohne Namen des Sponsors geht es nicht.": "sp.nameFehlt",
  "Auswärtsspiel": "ev.auswaertsspiel",
  "Die Vereinsfarben konnten nicht gespeichert werden.": "verein.farbenSpeichernFehler",
  "Mitgliedschaft wurde abgelehnt. Eine neue Anfrage ist jederzeit möglich.": "mit.abgelehnt",
  "Sätze & Stationen": "help.saetzeStationen",
  "Die Einteilung konnte nicht gespeichert werden. Fremde Personen darf nur die Vereinsleitung einteilen.": "help.einteilungSpeichernFehler",
  "Konnte nicht als gelesen vermerkt werden.": "news.gelesenFehler",
  "Für dieses Konto besteht noch keine Mitgliedschaft in diesem Verein.": "mit.keineMitgliedschaft",
  "Der neue Verein konnte nicht geladen werden.": "verein.neuLadenFehler",
  "Bitte bestätige jetzt die E-Mail. Danach kannst du dich anmelden und die Vereinsregistrierung abschließen.": "reg.mailBestaetigenDannAnmelden",
  "Die Anmeldung hat nicht geklappt. Bitte versuche es noch einmal.": "login.fehlgeschlagen",
  "Die Registrierung hat nicht geklappt. Bitte versuche es noch einmal.": "reg.fehlgeschlagen",
  "Kapitän wurde für diese Mannschaft gespeichert.": "tm.kapitaenGespeichert2",
  "Die Entscheidung konnte nicht gespeichert werden.": "allg.entscheidungNichtGespeichert",
  "Die Anmeldung ist gerade nicht möglich. Bitte versuche es in ein paar Minuten noch einmal.": "login.geradeNichtMoeglich",
  "Mitglieder-App für Vereine": "allg.mitgliederApp",
  "Noch keine Mitgliedschaft": "mit.keineMitgliedschaft2",
  "Noch kein Konto?": "login.keinKonto2",
  "Kind / Athlet/in verknüpfen": "fam.kindVerknuepfen",
  "Platz 1 von 24": "tipp.platzVon",
  " (du)": "allg.duKlammer",
  "Der Termin wurde nicht gespeichert — dir fehlt das Recht, für diese Mannschaft einzutragen.": "ev.keinRechtEintragen",
  "Die Kalenderverbindung konnte nicht angelegt werden.": "kal.verbindungFehler",
  "Diese Rechnungsnummer ist bereits vergeben.": "bei.rechnungsnummerVergeben",
  "Nur berechtigte Rollen können hier schreiben.": "chat.nurBerechtigte",
  "Bild auswählen (optional)": "allg.bildWaehlen2",
  "Der Mannschaftskader konnte nicht geladen werden.": "tm.kaderLadenFehler",
  "Athlet/innen können höchstens drei Mannschaften zugeordnet sein.": "tm.maxDreiMannschaften",
  "Die Saison-Historie konnte nicht geladen werden.": "sais.historieLadenFehler",
  "Der Saison-Reset konnte nicht durchgeführt werden.": "sais.resetFehler",
  "Die Fahrzeuge konnten nicht geladen werden.": "fzg.ladenFehler",
  "Das Ende muss nach dem Start liegen.": "fzg.endeNachStart",
  "Vorlage konnte nicht angewendet werden.": "help.vorlageNichtAngewendet",
  "Alle Stationen dieses Termins entfernen?": "help.alleStationenEntfernen",
  "Satz konnte nicht gelöscht werden.": "help.satzNichtGeloescht",
  "Rechnung ist unterwegs": "bei.rechnungUnterwegs",
  "Bitte Vor- und Nachname ausfüllen.": "pf.namePflicht",
  "Berechtigung wurde nicht erteilt.": "push.nichtErteilt",
  "Zum Home-Bildschirm hinzufuegen": "sys.homeBildschirm",
  "Nummer wird erstellt …": "sys.nummerWirdErstellt",
  "Im Demo-Modus kann kein echtes Konto gelöscht werden.": "konto.demoLoeschen",
  "Austritt nicht möglich.": "tipp.austrittNichtMoeglich",
  "Wann soll der Sponsor erscheinen? Bitte Startzeitpunkt angeben.": "sp.startzeitpunkt",
  "Die Trainer-Mannschaften konnten nicht gespeichert werden.": "tm.trainerTeamsNichtGespeichert",
  "Die Sperre konnte nicht gesetzt werden.": "mit.sperreNichtGesetzt",
  "Die Auswahl konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es noch einmal.": "verein.auswahlNichtGespeichert",
  "Dein Tipp konnte nicht gespeichert werden. Steht das Ergebnis schon fest?": "tipp.nichtGespeichert",
  "Die Einteilung konnte nicht entfernt werden.": "help.einteilungNichtEntfernt",
  "Die Benachrichtigung konnte nicht entfernt werden.": "push.benachrichtigungNichtEntfernt",
  "Deine Registrierung wartet noch auf die Freigabe durch den Vereins-Administrator.": "reg.wartetFreigabe",
  "Das Vereinsprofil konnte nicht fertiggestellt werden.": "verein.profilNichtFertig",
  "Das Konto wurde erstellt, aber das Vereinsprofil konnte nicht angelegt werden.": "reg.kontoOhneVereinsprofil",
  "Keine Verbindung. Prüfe dein Internet und versuche es noch einmal.": "allg.keineVerbindung",
  "Aufnahme noch nicht bestätigt": "mit.aufnahmeOffen",
  "Die Strafe konnte nicht zugewiesen werden.": "straf.zuweisenFehler",
  "Die Mitgliederliste konnte nicht geladen werden.": "mit.listeFehler",
  "Für diese E-Mail existiert bereits ein Konto. Melde dich an oder setze dein Passwort zurück.": "reg.mailVergeben",
  "Du gehörst noch keinem Verein an.": "verein.nochKeiner",
  "Dein Konto ist angelegt. Sobald der Verein deine Aufnahme bestätigt, kannst du dich anmelden und alle Funktionen nutzen.": "reg.kontoAngelegt2",
  "Wird geöffnet …": "allg.wirdGeoeffnet",
  "Elternteil verknüpfen": "fam.elternteilVerknuepfen",
  "Nur für Vereinsmitglieder": "allg.nurMitglieder",
  "Du bietest einen Platz an ✓": "fzg.platzAngeboten",
  "Die Absage konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es noch einmal.": "ev.absageFehler",
  "Es kam keine Kalenderadresse zurück.": "kal.keineAdresse",
  "Der Beitrag konnte nicht gespeichert werden.": "bei.speichernFehler",
  "Die News konnte nicht gelöscht werden.": "news.loeschenFehler",
  "Großeltern": "fam.grosseltern",
  "Bitte zuerst einen Athlet/in auswählen.": "tm.athletZuerstWaehlen",
  "Die Mannschaftszuordnung konnte nicht gespeichert werden.": "tm.zuordnungFehler",
  "Bitte einen Titel und einen gültigen Betrag eingeben.": "bei.titelBetragPflicht",
  "gelöscht": "allg.geloescht",
  "Die Buchungen konnten nicht geladen werden.": "fzg.buchungenFehler",
  "Das Fahrzeug ist in diesem Zeitraum bereits gebucht.": "fzg.zeitraumBelegt",
  "Dieser Satz enthält noch keine Stationen. Trage sie unter Verwaltung → Helferdienst-Sätze ein.": "help.satzOhneStationen",
  "Die Stationen konnten nicht entfernt werden.": "help.stationenEntfernenFehler",
  "Station konnte nicht hinzugefügt werden.": "help.stationHinzufuegenFehler",
  "Wir haben euch die Rechnung geschickt. Nach dem Zahlungseingang schalten wir den Verein frei.": "zug.rechnungGeschickt",
  "Alle E-Mail-Adressen entfernen? Du erhältst dann keine Vereinsnachrichten mehr per Mail.": "pf.alleMailsEntfernen",
  "Token konnte nicht gespeichert werden.": "push.tokenFehler",
  "Wird bearbeitet …": "allg.wirdBearbeitet",
  "Kalendersynchronisierung benötigt ein echtes Konto.": "kal.echtesKontoNoetig",
  "Bitte melde dich erneut an.": "sich.erneutAnmelden",
  "Beitritt nicht möglich.": "verein.beitrittFehler",
  "Bis wann soll der Sponsor erscheinen? Bitte Endzeitpunkt angeben.": "sp.endzeitpunktFehlt",
  "Bitte JPG, PNG oder WebP auswählen.": "allg.bildFormatWaehlen",
  "Die Sperre konnte nicht aufgehoben werden.": "mit.entsperrenFehler",
  "Aufgaben für den Verein verteilen und abhaken.": "auf.beschreibung",
  "Das Ergebnis konnte nicht gespeichert werden.": "tipp.ergebnisFehler",
  "Das Protokoll konnte nicht gespeichert werden.": "prot.speichernFehler",
  "Die Benachrichtigungen konnten nicht entfernt werden.": "push.entfernenFehler",
  "Dieses Vereinsprofil ist derzeit nicht aktiv.": "verein.profilInaktiv",
  "Bitte wähle zuerst einen Verein aus.": "verein.zuerstWaehlen",
  "Dein Konto wurde erstellt. Der Vereins-Administrator muss deine Mitgliedschaft noch freigeben.": "reg.freigabeNoetig",
  "Änderungen speichern": "allg.aenderungenSpeichern",
  "Wird gesendet …": "allg.wirdGesendet2",
  "Bezahlt-Status konnte nicht geändert werden.": "bei.bezahltStatusFehler",
  "Die Rollenänderung konnte nicht gespeichert werden.": "mit.rollenaenderungFehler",
  "Die Bestätigungsmail konnte gerade nicht verschickt werden. Bitte versuche es in ein paar Minuten noch einmal — dein Konto ist noch nicht fertig eingerichtet.": "reg.bestaetigungsmailFehler",
  "Wähle den Verein, in den du möchtest.": "verein.waehlenZiel",
  "Für dieses Konto besteht in diesem Verein noch keine Mitgliedschaft. Wende dich an die Vereinsverwaltung oder wähle einen anderen Verein.": "verein.keineMitgliedschaft",
  "Anmeldung läuft …": "login.laeuft",
  "Konto wird erstellt …": "reg.kontoWirdErstellt",
  "Deine Antwort konnte nicht gespeichert werden.": "umf.antwortNichtGespeichert",
  "Bitte wähle eine Mannschaft aus.": "tm.bitteWaehlen",
  "Die Absage wurde nicht gespeichert. Entweder fehlt dir das Recht für diese Mannschaft, oder der Termin gibt es nicht mehr.": "ev.absageNichtGespeichert",
  "Vereins-Events sind für alle Mitglieder sichtbar, unabhängig von Mannschaft.": "ev.vereinseventSichtbar",
  "Der Zahlungsstatus konnte nicht gespeichert werden.": "bei.zahlungsstatusFehler",
  "Bitte JPG, PNG oder WebP mit maximal 5 MB auswählen.": "allg.bildFormatHinweis",
  "Die Verknüpfung konnte nicht gespeichert werden.": "fam.verknuepfungFehler",
  "Der Kapitän konnte nicht gespeichert werden.": "tm.kapitaenFehler",
  "Die Mannschaft konnte nicht angelegt werden.": "tm.anlegenFehler",
  "Für diese Mannschaft darfst du den Katalog nur ansehen.": "straf.nurAnsehen",
  "Die Aufgaben konnten nicht geladen werden.": "auf.ladenFehler",
  "Bitte alle Felder ausfüllen.": "allg.alleFelderAusfuellen",
  "Buchung konnte nicht geändert werden.": "fzg.buchungAendernFehler",
  "Eine Station wurde übernommen.": "help.stationUebernommen",
  "eine Eintragung": "help.eineEintragung",
  "Bitte Name und E-Mail angeben.": "allg.nameUndMailAngeben",
  "Einige Daten konnten nicht geladen werden.": "allg.datenTeilweiseFehler",
  "Änderung verworfen — deine E-Mail-Adresse ist unverändert.": "konto.mailAenderungVerworfen",
  "Push konnte nicht eingerichtet werden.": "push.einrichtenFehler",
  "Passwortänderung ist nur mit einem echten Konto möglich.": "sich.passwortNurEchtesKonto",
  "Bitte wähle mindestens eine Terminart aus.": "ev.mindestensEineTerminart",
  "Das Konto konnte nicht vollständig gelöscht werden. Bitte kontaktiere den Support.": "konto.loeschenUnvollstaendig",
  "Tipp ändern": "tipp.tippAendern",
  "Der Sponsor kann nicht enden, bevor er beginnt.": "sp.endeVorBeginn",
  "Das Vereinslogo darf höchstens 2 MB groß sein.": "verein.logoGroesse",
  "Der Status konnte nicht geändert werden.": "allg.statusAendernFehler",
  "Die Profile konnten nicht zusammengeführt werden.": "sys.profileZusammenfuehrenFehler",
  "Das Ergebnis konnte nicht entfernt werden.": "tipp.ergebnisEntfernenFehler",
  "Das Protokoll ist gespeichert, die Aufgaben darin konnten aber nicht angelegt werden. Bitte trage sie noch einmal ein.": "prot.aufgabenNichtAngelegt",
  "Die Reihenfolge konnte nicht gespeichert werden.": "allg.reihenfolgeFehler",
  "Die Familienverknüpfungen konnten nicht geladen werden.": "fam.verknuepfungenLadenFehler",
  "Dieser Verein hat dich gesperrt. Ein Beitritt ist nicht möglich.": "verein.gesperrtKeinBeitritt",
  "Im laufenden Betrieb gibt es nichts zurückzusetzen. Einzelne Termine, News und Umfragen lassen sich dort löschen, wo sie stehen.": "sys.nichtsZurueckzusetzen",
  "Namen suchen …": "ph.namenSuchen",
  "Mitglied suchen …": "ph.mitgliedSuchen",
  "Land suchen …": "ph.landSuchen",
  "Nachricht schreiben…": "ph.nachrichtSchreiben",
  "Text der News…": "ph.newsText",
  "Neue Aufgabe eintippen…": "ph.neueAufgabe",
  "Protokolltext / Notizen der Sitzung…": "ph.protokolltext",
  "Kurzname, z. B. TUSB": "ph.kurzname",
  "Vereinsregisternummer": "ph.registernummer",
  "Empfehlungscode (optional)": "ph.empfehlungscode",
  "Name des Kindes": "ph.nameKind",
  "Passwort bestätigen": "ph.passwortBestaetigen",
  "Freie Plätze, z. B. 3": "ph.freiePlaetze",
  "Abfahrtsadresse *, z. B. Hauptstraße 12, Iserlohn": "ph.abfahrtsadresse",
  "Notiz (optional), z. B. Kofferraum begrenzt": "ph.notizKofferraum",
  "z. B. Halle gesperrt, zu wenige Zusagen": "ph.absagegrundBeispiel",
  "Ort *": "ph.ortPflicht",
  "Jahr": "ph.jahr",
  "Beitragshöhe €": "ph.beitragshoehe",
  "z. B. Max Mustermann, Lea Mustermann": "ph.namenBeispiel",
  "Rechnungsnummer (optional)": "ph.rechnungsnummer",
  "Titel": "ph.titel",
  "Mannschaftsname, z. B. U17": "ph.mannschaftsnameBsp",
  "Kategorie, z. B. Jugend oder Herren": "ph.kategorieBeispiel",
  "Mannschaftsname": "ph.mannschaftsname",
  "Kategorie": "ph.kategorie",
  "Titel, z. B. Zuspätkommen": "ph.strafeTitel",
  "Kosten": "ph.kosten",
  "z. B. 2025/26": "ph.saisonBeispiel",
  "Titel, z. B. Kuchen backen": "ph.aufgabeTitel",
  "Bezeichnung, z. B. Vereinsbus": "ph.fahrzeugName",
  "Kennzeichen": "ph.kennzeichen",
  "Anzahl Plätze": "ph.anzahlPlaetze",
  "Name / Zweck": "ph.nameZweck",
  "z. B. 14": "ph.beispiel14",
  "Ansprechpartner *": "ph.ansprechpartner",
  "E-Mail für die Rechnung *": "ph.rechnungsmail",
  "Telefon (optional)": "ph.telefonOptional",
  "Wie viele Mitglieder bekommen einen Zugang?": "ph.wieVieleZugaenge",
  "Anmerkung (optional)": "ph.anmerkung",
  "Anzeigename": "ph.anzeigename",
  "Kontakt-E-Mail im Verein": "ph.kontaktmail",
  "Mitglied seit": "ph.mitgliedSeit",
  "Mitgliederausweisnummer": "ph.ausweisnummer",
  "Akademischer Titel (optional)": "ph.akadTitel",
  "Telefonnummer": "ph.telefonnummer",
  "Nationalität": "ph.nationalitaet",
  "Straße und Hausnummer": "ph.strasse",
  "Altes Passwort": "ph.altesPasswort",
  "Neues Passwort": "ph.neuesPasswort",
  "Neues Passwort wiederholen": "ph.neuesPasswortWdh",
  "Titel, z. B. Vorstandssitzung August": "ph.sitzungTitel",
  "Name des Sponsors": "ph.sponsorName",
  "Kurzer Text (optional)": "ph.kurzerText",
  "z. B. 10 % für alle Mitglieder": "ph.rabattBeispiel",
  "Was genau bekommt man, und wie?": "ph.aktionDetail",
  "Frage oder Titel": "ph.frageTitel",
  "Station …": "ph.station",
  "Deine Zu- oder Absage": "aria.zusage",
  "Station wählen": "aria.stationWaehlen",
  "Kalenderübersicht ein- oder ausblenden": "aria.kalenderUmschalten",
  "Termine mit dem Telefonkalender verbinden": "aria.kalenderVerbinden",
  "Als Standardansicht speichern": "aria.standardansicht",
  "Nachricht senden": "aria.nachrichtSenden",
  "Strafe entfernen": "aria.strafeEntfernen",
  "Anfrage annehmen": "aria.anfrageAnnehmen",
  "Anfrage ablehnen": "aria.anfrageAblehnen",
  "Buchung stornieren": "aria.buchungStornieren",
  "Telefonnummer kopieren": "aria.telefonKopieren",
  "Zurück zum Profil": "aria.zurueckProfil",
  "Unsere Tore tippen": "aria.unsereToreTippen",
  "Tore des Gegners tippen": "aria.gegnerToreTippen",
  "Neu laden": "aria.neuLaden",
  "Bild entfernen": "aria.bildEntfernen",
  "Nach oben verschieben": "aria.nachOben",
  "Nach unten verschieben": "aria.nachUnten",
  "Unsere Tore": "label.unsereTore",
  "Tore des Gegners": "label.gegnerTore",
  "Abbrechen": "allg.abbrechen",
  "Speichern": "allg.speichern",
  "Löschen": "allg.loeschen",
  "Bearbeiten": "allg.bearbeiten",
  "Zurück": "allg.zurueck",
  "Entfernen": "allg.entfernen",
  "Anlegen": "allg.anlegen",
  "Hinzufügen": "allg.hinzufuegen",
  "Schließen": "allg.schliessen",
  "Abmelden": "allg.abmelden",
  "Wird geladen …": "allg.laedt",
  "Niemand gefunden.": "allg.niemandGefunden",
  "Ablehnen": "allg.ablehnen",
  "Annehmen": "allg.annehmen",
  "Austragen": "allg.austragen",
  "Übernehmen": "allg.uebernehmen",
  "Eintragen": "allg.eintragenKnopf",
  "Vor- und Nachname": "feld.vollerName",
  "E-Mail-Adresse": "login.email",
  "Passwort": "login.passwort",
  "Rückennummer": "feld.rueckennummer",
  "Mannschaft": "tm.mannschaft",
  "Mannschaften": "tm.mannschaften",
  "Stadt": "feld.stadt",
  "Gegner": "feld.gegner",
  "Impressum": "recht.impressum",
  "Datenschutz": "recht.datenschutz",
  "Nutzungsbedingungen": "recht.nutzung",
  "Verein wechseln": "verein.wechseln",
  "Deine Vereine": "verein.deine",
  "Beitritt anfragen": "verein.beitrittAnfragen",
  "Ich trete bei als": "verein.beitrittAls",
  "Verein finden": "verein.finden",
  "Suche den Verein, dem du beitreten möchtest.": "verein.findenHinweis",
  "Vereine werden geladen …": "verein.laden",
  "Die Vereinsliste konnte nicht geladen werden.": "verein.ladenFehler",
  "Erneut versuchen": "allg.erneut",
  "Neuen Verein registrieren": "verein.neuAnlegen",
  "Verein anlegen": "verein.anlegen",
  "Zurück zur Vereinsauswahl": "verein.zurueckAuswahl",
  "Eigene Farben": "verein.eigeneFarben",
  "Mannschaften werden geladen …": "tm.laden",
  "Noch keine Mannschaften angelegt.": "tm.keine",
  "Strafe wählen …": "straf.waehlen",
  "Noch keine Strafen vergeben.": "straf.keine",
  "Entsperren": "allg.entsperren",
  "Vorname": "reg.vorname",
  "Nachname": "reg.nachname",
  "Beschreibung (optional)": "feld.beschreibung",
  "Nutzer suchen": "feld.nutzerSuchen",
  "Mannschaft filtern": "feld.mannschaftFiltern",
  "Vorheriger Monat": "kal.vorher",
  "Nächster Monat": "kal.naechster",
  "Diesen Bereich schaltet der Verein frei.": "allg.gesperrt",
  "Mehr erfahren": "allg.mehr",
  "Zur Aktion": "sp.zurAktion",
  "Website ansehen": "sp.website",
  "Konto endgültig löschen?": "konto.loeschenFrage",
  "Jetzt registrieren": "login.registrieren",
  "Nächstes Spiel": "home.naechstesSpiel",
  "Nächstes Training": "home.naechstesTraining",
  "Angemeldet bleiben": "login.bleiben",
  "Passwort vergessen?": "login.vergessen",
  "Zum Login": "reg.jetztAnmelden",
  "Konto erstellen": "reg.titel",
  "Fast geschafft": "reg.fastGeschafft",
  "Ich registriere mich als": "reg.alsWas",
  "Ich akzeptiere die": "reg.akzeptiere",
  "Datenschutzerklärung": "recht.datenschutzerklaerung",
  "Alle Mitglieder": "mit.alle",
  "Tippe, um abzustimmen": "umf.tippen",
  "Jetzt eintragen": "allg.jetztEintragen",
  "Alle ansehen": "allg.alleAnsehen",
  "Noch keine News.": "news.keine",
  "Liste wird geladen …": "allg.listeLaedt",
  "Noch niemand eingetragen": "helf.niemand",
  "Jemanden eintragen": "helf.jemanden",
  "Mitfahren": "fahr.mitfahren",
  "Fahrgemeinschaft löschen": "fahr.loeschen",
  "Platz anbieten": "fahr.anbieten",
  "Helfer:innen gesucht": "helf.gesucht",
  "Termin eintragen": "ev.eintragen",
  "Training": "ev.training",
  "Spiel": "ev.spiel",
  "Vereins-Event": "ev.vereinsevent",
  "Heimspiel": "ev.heimspiel",
  "Wiederholend": "ev.wiederholend",
  "Alle Mannschaften": "ev.alleTeams",
  "Nur diesen Termin": "ev.nurDiesen",
  "Ganze Reihe löschen": "ev.ganzeReihe",
  "Diesen Termin wirklich löschen?": "ev.wirklichLoeschen",
  "Beitragsart": "bei.art",
  "Mitgliedsbeitrag": "bei.mitglied",
  "Familienbeitrag": "bei.familie",
  "Weitere Vereinsmitglieder": "mit.weitere",
  "Melden": "chat.melden",
  "Blockieren": "chat.blockieren",
  "Noch kein Chat für dich": "chat.keiner",
  "Für dich ausgeblendet": "chat.ausgeblendet",
  "Noch keine News veröffentlicht.": "news.keineVeroeffentlicht",
  "Bezahlt": "bei.bezahlt",
  "Noch nicht bezahlt": "bei.offen",
  "Noch keine Beitragsdatensätze vorhanden.": "bei.keineDaten",
  "Anzahl der Personen insgesamt": "bei.anzahlPersonen",
  "Weitere Namen ohne Benutzerkonto": "bei.weitereNamen",
  "Mehrere Namen bitte durch Komma trennen.": "bei.kommaHinweis",
  "Familienverknüpfung": "fam.verknuepfung",
  "Rolle in der Verknüpfung": "fam.rolle",
  "Verbinden": "fam.verbinden",
  "Kein passendes Profil gefunden.": "fam.keinProfil",
  "Kind ohne Account vorläufig anlegen": "fam.kindAnlegen",
  "Kapitänsrolle zuweisen": "tm.kapitaenZuweisen",
  "Athlet/in auswählen …": "tm.athletWaehlen",
  "Du bist aktuell keiner Mannschaft zugeordnet.": "tm.keineZuordnung",
  "Neue Mannschaft anlegen": "tm.neuAnlegen",
  "Erwachsenenmannschaft?": "tm.erwachsene",
  "Noch keiner Mannschaft zugeordnet.": "tm.keineZuordnungKurz",
  "Für diese Mannschaft ist derzeit kein Spiel geplant.": "home.keinSpiel",
  "Für diesen Termin ist niemand eingeteilt.": "helf.niemandEingeteilt",
  "Noch keine Fahrgemeinschaft für diesen Termin.": "fahr.keine",
  "Nur diesen Termin oder die ganze Reihe?": "ev.reiheFrage",
  "Heute Geburtstag:": "home.geburtstag",
  "Willkommen zurück,": "home.willkommenKomma",
  "Demo-Zugänge zum Ausprobieren": "login.demo",
  "Vorschlag · Name stimmt überein": "sys.vorschlag",
  "Strafenverwaltung": "straf.verwaltung",
  "Bisherige Strafen": "straf.bisherige",
  "Alle Strafen": "straf.alle",
  "Historie wird geladen …": "straf.historieLaedt",
  "Athlet/in wählen …": "tm.athletWaehlen2",
  "Ändern": "allg.aendern",
  "Datum": "ev.datum",
  "Personen": "feld.personen",
  "Ganzer Verein": "auf.ganzerVerein",
  "Verantwortlich (mehrere möglich)": "auf.verantwortlich",
  "Aufgaben werden geladen …": "auf.laden",
  "Aktuell keine offenen Vereinsaufgaben.": "auf.keine",
  "Ich übernehme das": "auf.uebernehmeIch",
  "Zurückziehen": "auf.zurueckziehen",
  "Noch keine Fahrzeuge hinterlegt.": "fz.keine",
  "Kalender wird geladen …": "fz.kalenderLaedt",
  "Keine Buchungen in diesem Monat.": "fz.keineBuchungen",
  "Private Buchung (keine Mannschaft)": "fz.privat",
  "Mannschaft wählen …": "tm.mannschaftWaehlen",
  "Telefonnummer wird geladen …": "tel.laedt",
  "Keine Telefonnummer hinterlegt.": "tel.keine",
  "Satz vorladen …": "helf.satzVorladen",
  "Stationen an diesem Termin": "helf.stationen",
  "Alle entfernen": "helf.alleEntfernen",
  "Noch keine Sätze angelegt.": "helf.keineSaetze",
  "Satz löschen": "helf.satzLoeschen",
  "Anfrage zurückziehen": "zug.zurueckziehen",
  "Eigene Sponsoren zeigen": "sp.eigene",
  "Vollzugang anfragen": "zug.vollzugang",
  "Kein eigenes Abo nötig": "zug.keinAbo",
  "Keine Mitglieder gefunden.": "mit.keine",
  "Für deine aktuellen Rollen gibt es noch keine Videos.": "vid.keine",
  "Tippe einen Namen an, um die Person wieder anzuzeigen.": "chat.wiederAnzeigen",
  "Anschließend kannst du dich anmelden.": "reg.danach",
  "Ich akzeptiere die": "reg.akzeptiere",
  "Strafen": "straf.titel",
  "Keine aktiven Strafen.": "straf.keineAktiven",
  "Strafen-Historie": "straf.historie",
  "Aufgaben": "auf.titel",
  "Für keine Aufgabe eingetragen.": "auf.keineEingetragen",
  "Fahrgemeinschaften": "fahr.titel",
  "Keine Fahrgemeinschaften.": "fahr.keineKurz",
  "Aktuell keine offenen Beitrittsanfragen.": "mit.keineAnfragen",
  "Vereinsprofil bearbeiten": "verein.profilBearbeiten",
  "Aktiv": "status.aktiv",
  "Ausstehend": "status.ausstehend",
  "Inaktiv": "status.inaktiv",
  "Gesperrt": "status.gesperrt",
  "Athleten-Mannschaften": "tm.athletenTeams",
  "Telefonnummern": "feld.telefonnummern",
  "Geburtstag im Verein anzeigen": "feld.geburtstagZeigen",
  "Weiblich": "gesch.w",
  "Männlich": "gesch.m",
  "Divers": "gesch.d",
  "Keine Angabe": "gesch.k",
  "Push-Benachrichtigungen auf diesem Gerät": "push.aufGeraet",
  "Automatischer Logout": "sich.autoLogout",
  "Nach 30 Tagen": "sich.tage30",
  "Nach 60 Tagen": "sich.tage60",
  "Nach 90 Tagen": "sich.tage90",
  "Vereine werben Vereine": "zug.werben",
  "Code kopieren": "zug.codeKopieren",
  "Termine abonnieren": "kal.abonnieren",
  "Aktualisierung": "kal.aktualisierung",
  "Nie automatisch": "kal.nie",
  "Täglich": "kal.taeglich",
  "Auswahl aufheben — meine Mannschaften verwenden": "kal.auswahlAufheben",
  "Zur Aktion": "sp.zurAktion",
  "Website ansehen": "sp.website",
  "Konto löschen": "pf.kontoLoeschen",
  "Verein anlegen": "verein.anlegen",
  "Wöchentlich · Sonntagabend": "kal.woechentlich",
  "Monatlich": "kal.monatlich",
  "Mit Gerätekalender verbinden": "kal.verbinden",
  "Bedingungen": "recht.bedingungen",
  "Konto und persönliche Daten löschen": "konto.loeschenLang",
  "Abstimmung beendet — Ergebnis final": "sais.beendet",
  "Athlet/in der Saison — Ehrung beim Sommerfest": "sais.ehrung",
  "Tippspiel je Mannschaft": "tipp.jeTeam",
  "Noch niemand in dieser Runde.": "tipp.niemand",
  "Wartet auf Ergebnis": "tipp.wartet",
  "Ergebnisse & Punkte": "tipp.ergebnisse",
  "Keine offenen Aufgaben — sehr gut! 🎉": "prot.keineAufgaben",
  "Neues Protokoll erfassen": "prot.neu",
  "Teilnehmer:innen": "prot.teilnehmer",
  "Protokoll & Aufgaben speichern": "prot.speichern",
  "Bitte Titel und Protokolltext ausfüllen.": "prot.pflicht",
  "Vergangene Protokolle": "prot.vergangene",
  "Automatische Zahlungserinnerungen": "bei.erinnerungen",
  "Aktuell keine offenen Beiträge. 🎉": "bei.keineOffenen",
  "Eigene Sponsoren sind noch nicht freigeschaltet": "sp.nichtFrei",
  "Zu sehen:": "sp.zuSehen",
  "Der Sponsor": "sp.derSponsor",
  "Die Aktion (optional)": "sp.dieAktion",
  "Der Sponsor steht auf dem Platz": "sp.stehtAufPlatz",
  "Sponsor von diesem Platz entfernen": "sp.entfernen",
  "Neue Mitmach-Umfrage": "umf.neu",
  "Mindestens zwei Antwortmöglichkeiten eintragen.": "umf.mindestens",
  "Veröffentlichen": "allg.veroeffentlichen",
  "Mannschaft auswählen …": "tm.mannschaftWaehlen2",
  "Chat-Kanäle": "chat.kanaele",
  "Konten-Übersicht": "sys.konten",
  "Demo-Daten": "sys.demoDaten",
  "Ja, zurücksetzen": "sys.jaZuruecksetzen",
  "Profilbild des Vereins": "verein.logo",
  "JPG, PNG oder WebP · maximal 2 MB": "verein.logoHinweis",
  "Vereinsfarben": "verein.farben",
  "Offene Mitgliedsanträge": "mit.offeneAntraege",
  "Mitgliedsanträge werden geladen …": "mit.antraegeLaden",
  "Keine offenen Anträge": "mit.keineAntraegeKurz",
  "Registrierung": "mit.registrierung",
  "Freigeben": "mit.freigeben",
  "Liste aktualisieren": "allg.listeAktualisieren",
  "Mitgliedschaften verwalten": "mit.verwalten",
  "Mitglieder werden geladen …": "mit.laden",
  "Sperren": "mit.sperren",
  "Keine Mitgliedschaften vorhanden.": "mit.keineVorhanden",
  "Sperrliste": "mit.sperrliste",
  "Welche Funktionen braucht ihr?": "verein.funktionenFrage",
  "Niemand hat aktuell diese Rolle.": "rol.niemand",
  "Profile ohne Konto zusammenführen": "sys.profileZusammen",
  "Platzhalter-Profil (ohne Konto) …": "sys.platzhalter",
  "Noch nichts da": "allg.nochNichts",
  "Die App ist nicht einsatzbereit": "sys.nichtBereit",
  "Im App Store laden": "store.apple",
  "Bei Google Play laden": "store.google",
  "Verein auswählen …": "verein.waehlen",
  "Vereinsname, z. B. TuS Beispieldorf": "verein.namePlatzhalter",
  "Zu sehen:": "sp.zuSehen",
};

let quelle = readFileSync(DATEI, "utf8");
const zeilen = quelle.split("\n");

/* In welcher Funktion liegt eine Zeile? Ermittelt ueber die letzte
   Funktionsdeklaration am Zeilenanfang davor - in dieser Datei stehen alle
   Komponenten auf der obersten Ebene, deshalb reicht das. */
function funktionVon(zeilennummer) {
  for (let i = zeilennummer; i >= 0; i--) {
    const treffer = zeilen[i].match(/^function ([A-Z][A-Za-z0-9_]*)\s*\(/);
    if (treffer) return { name: treffer[1], zeile: i };
  }
  return null;
}

const zuErgaenzen = new Set();
const berichte = [];
let ersetzungen = 0;

for (const [deutsch, schluessel] of Object.entries(ERSETZUNGEN)) {
  const escaped = deutsch.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  /* Drei Formen, in denen ein Text vorkommt. Attribute brauchen geschweifte
     Klammern, Textknoten nicht - deshalb getrennt. */
  const formen = [
    { muster: new RegExp(`>${escaped}<`, "g"), ersatz: `>{t("${schluessel}")}<` },
    { muster: new RegExp(`placeholder="${escaped}"`, "g"), ersatz: `placeholder={t("${schluessel}")}` },
    { muster: new RegExp(`aria-label="${escaped}"`, "g"), ersatz: `aria-label={t("${schluessel}")}` },
  ];
  for (const { muster, ersatz } of formen) {
    let treffer;
    const kopie = new RegExp(muster.source, "g");
    while ((treffer = kopie.exec(quelle)) !== null) {
      const zeilennummer = quelle.slice(0, treffer.index).split("\n").length - 1;
      const funktion = funktionVon(zeilennummer);
      if (!funktion) { berichte.push(`  ? Zeile ${zeilennummer + 1}: keine Funktion gefunden fuer "${deutsch}"`); continue; }
      zuErgaenzen.add(funktion.name);
      ersetzungen++;
    }
    quelle = quelle.replace(muster, ersatz);
  }
}

/* useT() dort ergaenzen, wo es fehlt. */
const neuZeilen = quelle.split("\n");
let ergaenzt = 0;
for (const name of zuErgaenzen) {
  const start = neuZeilen.findIndex((z) => new RegExp(`^function ${name}\\s*\\(`).test(z));
  if (start < 0) continue;
  /* Schon vorhanden? Innerhalb der naechsten 12 Zeilen nachsehen. */
  const kopf = neuZeilen.slice(start, start + 12).join("\n");
  /* "const t" kann mitten in der Zeile stehen - bei einzeiligen
     Komponenten setzt dieses Werkzeug den Haken hinter die Klammer. */
  if (/\bconst t = /.test(kopf)) continue;
  /* Nach der oeffnenden Klammer der Funktion einfuegen - die kann ueber
     mehrere Zeilen gehen (lange Parameterlisten). */
  let ende = start;
  while (ende < neuZeilen.length && !neuZeilen[ende].includes(") {")) ende++;
  if (ende >= neuZeilen.length) { berichte.push(`  ? ${name}: Funktionskopf nicht gefunden`); continue; }
  /* EINZEILIGE KOMPONENTEN. Manche stehen komplett in einer Zeile:
     function X({...}) { const [a,b]=useState(); ... }
     Eine Zeile DANACH einzufuegen landet ausserhalb der Funktion - der Haken
     stuende dann auf oberster Ebene, was React verbietet. Genau das ist bei
     SecuritySettings und ReferralSettings passiert; der Linter hat es
     gemeldet ("React Hook cannot be called at the top level").
     Bei einer Zeile, die nach "{" noch Code enthaelt, wird deshalb DIREKT
     hinter der Klammer eingesetzt statt in einer neuen Zeile. */
  const nachKlammer = neuZeilen[ende].slice(neuZeilen[ende].indexOf(") {") + 3).trim();
  if (nachKlammer.length > 0) {
    neuZeilen[ende] = neuZeilen[ende].replace(") {", ") { const t = useT();");
  } else {
    neuZeilen.splice(ende + 1, 0, "  const t = useT();");
  }
  ergaenzt++;
}

console.log(`  ${ersetzungen} Textstellen, ${zuErgaenzen.size} Komponenten betroffen, ${ergaenzt} mal useT ergaenzt`);
berichte.forEach((z) => console.log(z));

if (modus === "anwenden") {
  writeFileSync(DATEI, neuZeilen.join("\n"), "utf8");
  console.log("  geschrieben");
} else {
  console.log("  (nur Probelauf - mit 'anwenden' schreiben)");
}
